function T = plot_topo_naca_re_polar_0353(polarCsv, varargin)
%PLOT_TOPO_NACA_RE_POLAR_0353 Plot calibrated NACA polar-proxy sweep.
%
% T = plot_topo_naca_re_polar_0353(polarCsv, 'OutputDir', outDir, ...
%     'ShowFigures', true/false)
%
% Expected input: naca_re_polar_proxy_0353.csv generated by
% scripts/run_topo_darcy_naca_re_sweep_0353.sh.  The function also accepts the
% 0350 polar-proxy CSV if the extra Re columns are absent.

p = inputParser;
addRequired(p, 'polarCsv', @(s)ischar(s) || isstring(s));
addParameter(p, 'OutputDir', 'runs/topo_matlab_plots_0353', @(s)ischar(s) || isstring(s));
addParameter(p, 'ShowFigures', true, @(x)islogical(x) || isnumeric(x));
addParameter(p, 'Prefix', 'naca_re_polar_proxy_0353', @(s)ischar(s) || isstring(s));
parse(p, polarCsv, varargin{:});

polarCsv = char(p.Results.polarCsv);
outDir = char(p.Results.OutputDir);
showFigures = logical(p.Results.ShowFigures);
prefix = char(p.Results.Prefix);
if ~exist(outDir, 'dir')
    mkdir(outDir);
end

opts = detectImportOptions(polarCsv, 'Delimiter', ',');
if any(strcmp(opts.VariableNames, 'naca'))
    try
        opts = setvartype(opts, 'naca', 'char');
    catch
    end
end
T = readtable(polarCsv, opts);

required = {'aoaDeg','dragProxy_mean','liftProxy_mean','liftOverDragProxy','darcyPower_mean'};
assert_all_present(required, T.Properties.VariableNames, polarCsv);

T = sortrows(T, 'aoaDeg');

sortedCsv = fullfile(outDir, [prefix '_sorted.csv']);
writetable(T, sortedCsv);
fprintf('[0353-matlab] wrote %s\n', sortedCsv);

visibleState = ternary(showFigures, 'on', 'off');

plot_xy(T.aoaDeg, T.liftProxy_mean, maybe_col(T,'liftProxy_std'), ...
    'AoA [deg]', 'liftProxy mean', 'NACA lift proxy vs AoA', ...
    fullfile(outDir, [prefix '_lift_proxy']));

plot_xy(T.aoaDeg, T.dragProxy_mean, maybe_col(T,'dragProxy_std'), ...
    'AoA [deg]', 'dragProxy mean', 'NACA drag proxy vs AoA', ...
    fullfile(outDir, [prefix '_drag_proxy']));

plot_xy(T.aoaDeg, T.liftOverDragProxy, [], ...
    'AoA [deg]', 'liftProxy / dragProxy', 'NACA signed finesse proxy vs AoA', ...
    fullfile(outDir, [prefix '_finesse_signed']));

if any(strcmp(T.Properties.VariableNames, 'absLiftOverAbsDrag'))
    plot_xy(T.aoaDeg, T.absLiftOverAbsDrag, [], ...
        'AoA [deg]', '|liftProxy| / |dragProxy|', 'NACA absolute finesse proxy vs AoA', ...
        fullfile(outDir, [prefix '_finesse_abs']));
end

plot_xy(T.aoaDeg, T.darcyPower_mean, maybe_col(T,'darcyPower_std'), ...
    'AoA [deg]', 'darcyPower mean', 'NACA Darcy power vs AoA', ...
    fullfile(outDir, [prefix '_darcy_power']));

% Polar-like lift-vs-drag curve.
fig = figure('Visible', visibleState);
plot(T.dragProxy_mean, T.liftProxy_mean, '-o', 'LineWidth', 1.5);
grid on;
xlabel('dragProxy mean');
ylabel('liftProxy mean');
title('NACA polar proxy: lift vs drag');
for i = 1:height(T)
    text(T.dragProxy_mean(i), T.liftProxy_mean(i), sprintf('  %.0f^\\circ', T.aoaDeg(i)), ...
        'FontSize', 8, 'Interpreter', 'tex');
end
save_fig(fig, fullfile(outDir, [prefix '_lift_vs_drag']));
if ~showFigures
    close(fig);
end

% Compact report with the most useful columns for papers/reports.
compactNames = {'naca','aoaDeg','U0','chord','nuEffRef','ReEff','kBT','gamma','Nx','Ny', ...
    'dragProxy_mean','dragProxy_std','liftProxy_mean','liftProxy_std', ...
    'liftOverDragProxy','absLiftOverAbsDrag','darcyPower_mean','darcyPower_std', ...
    'solidLeakOverSpeed_mean','meanSpeedRms_mean','solidLeakRms_mean','meanChi_mean','meanAlpha_mean'};
present = compactNames(ismember(compactNames, T.Properties.VariableNames));
C = T(:, present);
compactCsv = fullfile(outDir, [prefix '_compact.csv']);
writetable(C, compactCsv);
fprintf('[0353-matlab] wrote %s\n', compactCsv);

    function plot_xy(x, y, yerr, xl, yl, ttl, base)
        fig2 = figure('Visible', visibleState);
        if isempty(yerr)
            plot(x, y, '-o', 'LineWidth', 1.5);
        else
            errorbar(x, y, yerr, '-o', 'LineWidth', 1.5);
        end
        grid on;
        xlabel(xl);
        ylabel(yl);
        title(ttl);
        save_fig(fig2, base);
        if ~showFigures
            close(fig2);
        end
    end
end

function v = maybe_col(T, name)
if any(strcmp(T.Properties.VariableNames, name))
    v = T.(name);
else
    v = [];
end
end

function save_fig(fig, base)
png = [base '.png'];
pdf = [base '.pdf'];
saveas(fig, png);
saveas(fig, pdf);
fprintf('[0353-matlab] wrote %s\n', png);
fprintf('[0353-matlab] wrote %s\n', pdf);
end

function assert_all_present(required, names, source)
missing = setdiff(required, names);
if ~isempty(missing)
    error('Missing columns in %s: %s. Detected columns: %s', source, strjoin(missing, ', '), strjoin(names, ', '));
end
end

function out = ternary(cond, a, b)
if cond
    out = a;
else
    out = b;
end
end
