-- V4.25 historical scope-closure marker.
--
-- At V4.25, V4.22/V4.23 were correctly removed because their implementation
-- existed only in SRC_GPU-SURF-x8q-ablation and was not yet integrated into surf.
-- V4.27 later restores those curations after the autonomous Neumann lineage was
-- cherry-picked into the canonical surf branch and extends it through x9e-fix3.
--
-- This file intentionally has no SQL effect: it preserves the documentary fact
-- that V4.25 was a branch-boundary correction at that point in history.
