-- V4.31: mobile-material-solid / FSI curation x15 -> x18d (2026-09-15)
-- Source-only documentary curation. Generated products and SQLite dump are rebuilt.
PRAGMA foreign_keys=ON;

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x15a','MILESTONE','x15a','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x15a','0493x15a','x15a','0493x15a','solides mobiles / FSI','Audit du bilan de force du chi-solid fixe','Instrumente le budget de force/réaction du piston chi fixe et établit la fermeture mécanique avant l’étude de perméabilité.','DIAGNOSTIC','MOBILE_SOLID','REVIEW: bilan mécanique exploitable; imperméabilité non encore établie.','B','2026-09-12',NULL,NULL,'Précurseur direct des mesures x15b/x15c.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x15b','MILESTONE','x15b','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x15b','0493x15b','x15b','0493x15b','solides mobiles / FSI','Décomposition exacte chiVP/Brinkman','Sépare exactement les contributions Brinkman et chiVP; montre qu’une fermeture du budget mécanique peut coexister avec un solide poreux.','DIAGNOSTIC','MOBILE_SOLID','Résultat mécanique validé; ne constitue pas une fermeture matérielle imperméable.','B','2026-09-12',NULL,NULL,'À faible alpha, la réaction est dominée par chiVP (~94%).','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x15c','MILESTONE','x15c','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x15c','0493x15c','x15c','0493x15c','solides mobiles / FSI','Mesure directe de perméabilité du chi-solid','Mesure les crossings à travers un slab et démontre que mean+chiVP reste poreux malgré une bonne fermeture de force.','DIAGNOSTIC','MOBILE_SOLID','PASS comme diagnostic de perméabilité; résultat physique: paroi volumique poreuse.','A','2026-09-12',NULL,NULL,'Summary exact archivé.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x15e','MILESTONE','x15e','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x15e','0493x15e','x15e','0493x15e','solides mobiles / FSI','Qualification de la chaîne historique forte','Avec mean_outward_bath, alpha=800000, chiVP=0.25 et exclusion initiale, obtient zéro crossing mesuré sur le slab.','QUALIFICATION','MOBILE_SOLID','PASS pour la chaîne historique statique; mécanisme non retenu comme fermeture mobile finale.','A','2026-09-12',NULL,NULL,'Summary exact archivé; l’imperméabilité dépend fortement du bath orienté.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x15f','MILESTONE','x15f','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x15f','0493x15f','x15f','0493x15f','solides mobiles / FSI','Ablation sans outward_bath','Retire outward_bath à forte pénalisation et fait réapparaître un flux de crossings très important.','ABLATION','MOBILE_SOLID','PASS comme ablation discriminante; direction rejetée pour un solide matériel mobile.','A','2026-09-12',NULL,NULL,'Summary exact archivé; établit le rôle dominant du bath post-pénétration.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x16a','MILESTONE','x16a','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x16a','0493x16a','x16a','0493x16a','solides mobiles / FSI','Architecture SolidDynamics / SolidGeometry','Introduit une dynamique solide modulaire, le DOF rigid_slab_1d et les champs locaux chi/uSolidX/uSolidY avec bilan de quantité de mouvement.','CODE','MOBILE_SOLID','PASS sur le test rigid_slab_1d 2000 pas; fermeture proche du roundoff.','A','2026-09-12',NULL,NULL,'Package et summary exacts archivés.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x16b','MILESTONE','x16b','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x16b','0493x16b','x16b','0493x16b','solides mobiles / FSI','Charge solide spatiale exacte','Ajoute Delta p_s(c)=-Delta p_f(c) par cellule et la projection générique de cette charge vers les degrés de liberté du solide.','CODE','MOBILE_SOLID','Infrastructure de charge retenue; base du couplage mécanique ultérieur.','A','2026-09-12',NULL,NULL,'Package exact archivé.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x16c','MILESTONE','x16c','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x16c','0493x16c','x16c','0493x16c','solides mobiles / FSI','Inventaire du fluide fictif dans le solide','Ajoute un diagnostic de masse/moment/vitesse relative du fluide fictif afin d’attribuer les défauts du chi-solid mobile.','DIAGNOSTIC','MOBILE_SOLID','INFORMATIONAL; diagnostic de qualification, non physique nécessaire au chemin normal.','B','2026-09-12',NULL,NULL,'Devient opt-in/obsolète pour les géométries lagrangiennes avec x18d.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x16d','MILESTONE','x16d','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x16d','0493x16d','x16d','0493x16d','solides mobiles / FSI','Test galiléen du masque chi mobile','Montre que les sauts du masque binaire capturent brutalement des particules et corrèlent fortement masse fictive et pics d’impulsion.','QUALIFICATION','MOBILE_SOLID','REVIEW/FAIL comme invariance galiléenne du remapping binaire; résultat causal retenu.','A','2026-09-12',NULL,NULL,'Delta M_fict ~+639 aux shifts; RMS impulsion ~430.5 aux shifts contre ~35.7 hors shifts.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x16e','MILESTONE','x16e','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x16e','0493x16e','x16e','0493x16e','solides mobiles / FSI','Rasterisation subcellulaire CUDA résidente','Teste une représentation subcellulaire résidente pour adoucir les changements de support de la géométrie mobile.','CODE','MOBILE_SOLID','REVIEW; améliore la représentation mais ne résout pas le principe de capture/remapping.','B','2026-09-12',NULL,NULL,'Étape de la branche x16d--x16i finalement abandonnée comme mécanisme final.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x16f','MILESTONE','x16f','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x16f','0493x16f','x16f','0493x16f','solides mobiles / FSI','Synchronisation temporelle post-stream','Replace la mise à jour géométrique au niveau temporel post-stream correct pour tester l’hypothèse d’un décalage n/n+1.','EXPERIMENT','MOBILE_SOLID','Résultat négatif: effet faible; le défaut principal n’est pas la synchronisation temporelle.','A','2026-09-12',NULL,NULL,'Tentative infructueuse conservée comme enseignement.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x16g','MILESTONE','x16g','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x16g','0493x16g','x16g','0493x16g','solides mobiles / FSI','Neutralisation du bath lors de la capture','Neutralise l’impulsion collective de bath sur les particules nouvellement capturées par le masque.','EXPERIMENT','MOBILE_SOLID','Résultat négatif: le pic est déplacé au pas suivant; corriger la vitesse seule est insuffisant.','A','2026-09-12',NULL,NULL,'Tentative infructueuse conservée.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x16h','MILESTONE','x16h','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x16h','0493x16h','x16h','0493x16h','solides mobiles / FSI','Réinjection spatiale des particules capturées','Replace les particules capturées du côté fluide; réduit les pics mais provoque une déplétion artificielle du nouveau support solide.','EXPERIMENT','MOBILE_SOLID','REVIEW/REJECTED_DIRECTION: gain local mais remapping trop brutal.','A','2026-09-12',NULL,NULL,'Réduction ~70% du pic d’impulsion et ~95% du bath, au prix d’une forte déplétion.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x16i','MILESTONE','x16i','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x16i','0493x16i','x16i','0493x16i','solides mobiles / FSI','Comparaison binary_event / swept_geometry','Compare remapping binaire et volume balayé sur une géométrie déformable prescrite; aucun ne restaure une invariance galiléenne satisfaisante.','ABLATION','MOBILE_SOLID','REJECTED_DIRECTION pour le mécanisme final de solide matériel.','A','2026-09-12',NULL,NULL,'Erreur galiléenne ~0.2695 vs ~0.2859; swept_geometry plus coûteux (~+19%).','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x16j','MILESTONE','x16j','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x16j','0493x16j','x16j','0493x16j','solides mobiles / FSI','Première frontière chi cinétique spéculaire','Interprète chi=0.5 comme frontière matérielle et réutilise crossing x10/Q2 et réflexion spéculaire x14l au lieu de réparer les particules après pénétration.','CODE','MOBILE_SOLID','REVIEW: principe cinétique retenu; backend Eulerien encore en qualification.','A','2026-09-13',NULL,NULL,'Package exact archivé.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x16k','MILESTONE','x16k','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x16k','0493x16k','x16k','0493x16k','solides mobiles / FSI','Géométrie chi de niveau pour le test galiléen','Corrige/aligne l’évaluation géométrique de la frontière cinétique chi pour réduire les incohérences sous boost commun.','FIX','MOBILE_SOLID','REVIEW; étape intermédiaire vers la reconstruction Q2 cohérente.','B','2026-09-13',NULL,NULL,'Jalon intermédiaire attesté par le chantier x16j--x16q.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x16l','MILESTONE','x16l','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x16l','0493x16l','x16l','0493x16l','solides mobiles / FSI','Diagnostic direct post-stream de pénétration','Mesure la présence de particules du côté solide après streaming afin de distinguer fuite réelle et simple métrique cellulaire.','DIAGNOSTIC','MOBILE_SOLID','Qualification-only; read-only; non conservé dans le chemin normal x18d.','A','2026-09-13',NULL,NULL,'Diagnostic réutilisé plus tard pour auditer x18.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x16m','MILESTONE','x16m','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x16m','0493x16m','x16m','0493x16m','solides mobiles / FSI','Raffinement de racine Q2','Raffine la localisation de racine/intersection Q2 à l’échelle subcellulaire pour la frontière cinétique chi.','FIX','MOBILE_SOLID','REVIEW: cas rigides propres; résidu de fuite sur géométries déformables/courbes.','B','2026-09-13',NULL,NULL,'Étape intermédiaire de la reconstruction Eulerienne.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x16n','MILESTONE','x16n','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x16n','0493x16n','x16n','0493x16n','solides mobiles / FSI','Cohérence dual-square Q2','Impose une convention piecewise-Q2 cohérente sur les carrés duaux pour la topologie de frontière.','FIX','MOBILE_SOLID','REVIEW: rigidQualification=PASS, deformableQualification=REVIEW.','A','2026-09-13',NULL,NULL,'Summary exact archivé.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x16o','MILESTONE','x16o','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x16o','0493x16o','x16o','0493x16o','solides mobiles / FSI','Cohérence des extrémités d’arêtes Q2','Construit les extrémités de segments à partir des racines Q2 cohérentes avec le propriétaire local.','FIX','MOBILE_SOLID','REVIEW: rigidQualification=PASS; fuite spatiale subsiste sur cas courbe/déformable.','A','2026-09-13',NULL,NULL,'Summary exact archivé.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x16p','MILESTONE','x16p','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x16p','0493x16p','x16p','0493x16p','solides mobiles / FSI','Topologie complète de frontière Q2','Reconstruit la topologie locale depuis racines de bord Q2 et contour tracing, jusqu’à deux segments par propriétaire.','CODE','MOBILE_SOLID','REVIEW: rigide PASS/zero penetration, déformable REVIEW; zeroPenetrationAllCases=FAIL.','A','2026-09-13',NULL,NULL,'Summary exact archivé.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x16q','MILESTONE','x16q','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x16q','0493x16q','x16q','0493x16q','solides mobiles / FSI','Correction overlap/dead-zone de la frontière Q2','Traite la zone morte/overlap restante du chemin Q2 avant l’abandon de la reconstruction Eulerienne comme autorité mobile.','FIX','MOBILE_SOLID','REVIEW; dernier raffinement de la lignée x16j--x16q, supplantée par x17a.','B','2026-09-13',NULL,NULL,'Conservé pour l’historique et les briques Q2 réutilisables.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x17a','MILESTONE','x17a','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x17a','0493x17a','x17a','0493x17a','solides mobiles / FSI','Frontière chi lagrangienne persistante','Extrait une fois Gamma0={chi=0.5}, maintient un mesh lagrangien persistant et résout directement les collisions particule/segment mobile dans l’espace-temps.','CODE','MOBILE_SOLID','Backend matériel de référence; remplace la reconstruction chi->segments à chaque pas.','A','2026-09-13',NULL,NULL,'Package exact archivé; crossing quadratique exact en paramètre temporel.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x17b','MILESTONE','x17b','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x17b','0493x17b','x17b','0493x17b','solides mobiles / FSI','Initialisation et qualification des solides lagrangiens','Ajoute l’exclusion initiale unique du côté solide et qualifie la frontière persistante sans remapping en cours de run.','QUALIFICATION','MOBILE_SOLID','PASS: 6/6 cas, zéro pénétration stricte, persistance mesh, fermeture action-réaction/charge, contrôle galiléen.','A','2026-09-13',NULL,NULL,'État de référence d’imperméabilité à préserver.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x17c','MILESTONE','x17c','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x17c','0493x17c','x17c','0493x17c','solides mobiles / FSI','Première mécanique de membrane lagrangienne','Fait des noeuds x17a des DOF matériels avec ressorts d’arêtes, pénalité d’aire, amortissement interne et distribution nodale des impulsions.','CODE','FSI','Couplage FSI fonctionnel; mécanique structurelle minimale non revendiquée comme modèle de solide détaillé.','A','2026-09-14',NULL,NULL,'Package exact archivé.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x17d','MILESTONE','x17d','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x17d','0493x17d','x17d','0493x17d','solides mobiles / FSI','Membrane ancrée / plaque flexible de démonstration','Ajoute ancrages géométriques puis explore flexion et cohérence transverse pour obtenir une déformation visible sous charge fluide.','EXPERIMENT','FSI','HISTORICAL/REVIEW: transfert FSI démontré, mais tuning structural abandonné après rigidités excessives ou repliements.','A','2026-09-14',NULL,NULL,'Les fix mécaniques ultérieurs restent preuves sous x17d, sauf fix2 promu séparément.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x17d-fix2','MILESTONE','x17d-fix2','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x17d-fix2','0493x17d-fix2','x17d-fix2','0493x17d-fix2','solides mobiles / FSI','Couverture complète des particules par le collisionneur x17a','Supprime un plafond historique de lancement de 4096 blocs qui limitait le traitement à 1048576 particules sur les grands cas.','FIX','MOBILE_SOLID','Correctif de couverture nécessaire; conservé comme jalon de correction de calcul.','A','2026-09-14',NULL,NULL,'Package exact archivé.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x18a','MILESTONE','x18a','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x18a','0493x18a','x18a','0493x18a','solides mobiles / FSI','Volet rigide articulé 1-DOF','Ajoute hinged_plate_2d: contour rigide de faible épaisseur, charnière z fixe, dynamique I*theta_ddot=tau_hydro+tau_g-C*omega et couple issu des impacts x17a.','CODE','FSI','Démonstrateur courant; runs transverse-flow propres sur les audits de pénétration disponibles.','A','2026-09-14',NULL,NULL,'Sortie physique chi_hinged_plate_0493x18a.csv; package et CSV archivés.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x18a-fix2','MILESTONE','x18a-fix2','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x18a-fix2','0493x18a-fix2','x18a-fix2','0493x18a-fix2','solides mobiles / FSI','Initialisation du fluide cohérente avec l’angle du volet','Corrige le trou de fluide vertical laissé par la déactivation chi initiale lorsque le contour lagrangien est initialement tourné.','FIX','FSI','Correctif d’initialisation retenu; aucun changement C++/CUDA.','A','2026-09-14',NULL,NULL,'Désactive la déactivation Eulerienne initiale et exclut les particules dans le volet effectivement tourné.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x18b','MILESTONE','x18b','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x18b','0493x18b','x18b','0493x18b','solides mobiles / FSI','Chute du volet dans un fluide au repos','Variante x18a: volet initialement relevé, gravité, Ux=0 et sweep de densité fluide en scalant masse particulaire et kBT au même facteur.','RUNNER','FSI','Démonstrateur courant; audit cadence 1 propre sur 254 échantillons du cas gaz documenté.','A','2026-09-14',NULL,NULL,'Gas/liquid sont des labels de densité dans le même modèle MPCD, pas des EOS distinctes.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT OR IGNORE INTO objects(object_id,object_type,display_name,created_from) VALUES('milestone:0493x18d','MILESTONE','x18d','curation:0030_0493x15_x18_mobile_solids');
INSERT OR REPLACE INTO milestones(object_id,milestone_key,milestone_id,canonical_id,group_name,name,summary,nature,domain,status,confidence,introduced_date,introduced_commit,tag,notes,source_file,source_row) VALUES('milestone:0493x18d','0493x18d','x18d','0493x18d','solides mobiles / FSI','Nettoyage global du chemin normal des solides mobiles','Rend les diagnostics de qualification lourds opt-in via chiSolidQualificationDiagnosticsEnable=false par défaut et conserve seulement physique + résultats scientifiques dans le chemin normal.','OPTIMIZATION','MOBILE_SOLID','CURRENT/PENDING_LOCAL_CUDA_BUILD_AND_BENCHMARK; ne pas marquer PASS tant que la validation locale autoritaire n’est pas rapportée.','A','2026-09-14',NULL,NULL,'x18c spécialisé est explicitement rejeté/non canonique; x18d est global à tous les modèles de solides mobiles.','Info/inputs/historical/README_0493X15_X18_MOBILE_SOLIDS_20260915.md',NULL);

INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x15a','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x15a','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x15b','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x15b','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x15c','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x15c','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x15e','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x15e','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x15f','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x15f','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16a','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16a','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16b','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16b','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16c','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16c','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16d','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16d','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16e','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16e','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16f','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16f','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16g','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16g','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16h','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16h','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16i','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16i','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16j','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16j','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16k','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16k','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16l','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16l','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16m','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16m','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16n','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16n','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16o','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16o','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16p','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16p','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16q','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x16q','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x17a','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x17a','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x17b','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x17b','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x17c','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x17c','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x17d','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x17d','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x17d-fix2','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x17d-fix2','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x18a','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x18a','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x18a-fix2','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x18a-fix2','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x18b','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x18b','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x18d','HISTORICAL_SOURCE','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Archive primaire V4.31: packages, summaries, résultats x18 et rapport consolidé avec manifest SHA-256 interne.');
INSERT INTO evidence(object_id,evidence_type,path,confidence,notes) VALUES('milestone:0493x18d','PROJECT_REPORT','Info/inputs/historical/0493x15_x18_mobile_solids_20260912_15_original_sources.zip','A','Le rapport consolidé TeX/PDF archivé contient la section Solides mobiles et l’historique x15--x18d.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x15b','BUILDS_ON','milestone:0493x15a','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x15c','BUILDS_ON','milestone:0493x15b','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x15e','BUILDS_ON','milestone:0493x15c','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x15f','ABLATES','milestone:0493x15e','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x16a','BUILDS_ON','milestone:0493x15f','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x16b','BUILDS_ON','milestone:0493x16a','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x16c','DIAGNOSES','milestone:0493x16a','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x16d','DIAGNOSES','milestone:0493x16a','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x16e','BUILDS_ON','milestone:0493x16d','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x16f','BUILDS_ON','milestone:0493x16e','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x16g','BUILDS_ON','milestone:0493x16f','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x16h','BUILDS_ON','milestone:0493x16g','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x16i','BUILDS_ON','milestone:0493x16h','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x16j','SUPERSEDES','milestone:0493x16i','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x16k','BUILDS_ON','milestone:0493x16j','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x16l','DIAGNOSES','milestone:0493x16j','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x16m','BUILDS_ON','milestone:0493x16l','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x16n','BUILDS_ON','milestone:0493x16m','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x16o','BUILDS_ON','milestone:0493x16n','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x16p','BUILDS_ON','milestone:0493x16o','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x16q','BUILDS_ON','milestone:0493x16p','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x17a','SUPERSEDES','milestone:0493x16q','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x17b','QUALIFIES','milestone:0493x17a','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x17c','BUILDS_ON','milestone:0493x17b','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x17d','BUILDS_ON','milestone:0493x17c','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x17d-fix2','FIXES','milestone:0493x17d','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x18a','BUILDS_ON','milestone:0493x17b','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x18a-fix2','FIXES','milestone:0493x18a','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x18b','BUILDS_ON','milestone:0493x18a-fix2','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x18d','OPTIMIZES','milestone:0493x17b','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x18d','OPTIMIZES','milestone:0493x18a','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
INSERT OR IGNORE INTO relations(source_object_id,relation_type,target_object_id,confidence,evidence_text) VALUES('milestone:0493x18d','OPTIMIZES','milestone:0493x17c','A','Chaîne de décision documentée par la curation V4.31 et le rapport consolidé.');
UPDATE git_milestone_candidates SET status='LINKED', linked_milestone_object_id='milestone:0493' || label WHERE candidate_family='X' AND label IN ('x15a','x15b','x15c','x15e','x15f','x16a','x16b','x16c','x16d','x16e','x16f','x16g','x16h','x16i','x16j','x16k','x16l','x16m','x16n','x16o','x16p','x16q','x17a','x17b','x17c','x17d','x17d-fix2','x18a','x18a-fix2','x18b','x18d') AND EXISTS (SELECT 1 FROM milestones m WHERE m.object_id='milestone:0493' || git_milestone_candidates.label);
