function out = analyze_taylor_green_resampling_0126(runRoot, varargin)
%ANALYZE_TAYLOR_GREEN_RESAMPLING_0126 Post-process periodic TG resampling runs.
%
% out = analyze_taylor_green_resampling_0126('runs/taylor_green_resampling_0126')
%
% Expected subdirectories are generated by
% scripts/run_taylor_green_resampling_validation_0126.sh:
%   classic
%   q6
%   q6_resampling
%
% The analyzer reads V1/V2 .smpcd dumps, bins only role=Fluid particles by
% default, projects the velocity field onto the analytic Taylor--Green basis,
% and writes CSV tables plus visible figures in runRoot/analysis.

p = inputParser;
p.FunctionName = 'analyze_taylor_green_resampling_0126';
addOptional(p, 'runRoot', fullfile('runs','taylor_green_resampling_0126'), @(s) ischar(s) || isstring(s));
addParameter(p, 'kxMode', 1, @(x) isnumeric(x) && isscalar(x) && x >= 1);
addParameter(p, 'kyMode', 1, @(x) isnumeric(x) && isscalar(x) && x >= 1);
addParameter(p, 'makePlots', true, @(x) islogical(x) || isnumeric(x));
addParameter(p, 'labels', {'classic','q6','q6_resampling'}, @(x) iscell(x) || isstring(x));
parse(p, runRoot, varargin{:});
opts = p.Results;
runRoot = char(opts.runRoot);
labels = cellstr(opts.labels);

analysisDir = fullfile(runRoot, 'analysis');
if ~isfolder(analysisDir)
    mkdir(analysisDir);
end

runs = struct([]);
for i = 1:numel(labels)
    label = labels{i};
    runDir = fullfile(runRoot, label);
    if ~isfolder(runDir)
        fprintf('[TG 0126] skipping missing run directory: %s\n', runDir);
        continue;
    end
    r = local_analyze_run(runDir, label, opts.kxMode, opts.kyMode);
    runs = [runs; r]; %#ok<AGROW>
    writetable(r.metrics, fullfile(analysisDir, sprintf('tg_metrics_%s.csv', label)));
end

summary = local_make_summary(runs);
writetable(summary, fullfile(analysisDir, 'tg_summary.csv'));

out = struct();
out.runRoot = runRoot;
out.analysisDir = analysisDir;
out.runs = runs;
out.summary = summary;

disp('=== Taylor--Green resampling 0126 summary ===');
disp(summary);
fprintf('Analysis written to: %s\n', analysisDir);

if logical(opts.makePlots) && ~isempty(runs)
    local_plot_amplitude(runs, analysisDir);
    local_plot_diagnostics(runs, analysisDir);
    local_plot_resampling(runs, analysisDir);
    local_plot_final_fields(runs, analysisDir);
end
end

function run = local_analyze_run(runDir, label, kxMode, kyMode)
paramsFile = fullfile(runDir, 'params_used.kv');
if ~isfile(paramsFile)
    error('analyze_taylor_green_resampling_0126:missingParams', ...
        'Cannot find params_used.kv in %s', runDir);
end
params = parse_smpcd_kv(paramsFile);
for name = {'Lx','Ly','Nx','Ny'}
    if ~isfield(params, name{1})
        error('analyze_taylor_green_resampling_0126:missingParam', ...
            'Missing %s in %s', name{1}, paramsFile);
    end
end

Lx = double(params.Lx);
Ly = double(params.Ly);
Nx = double(params.Nx);
Ny = double(params.Ny);

frames = list_smpcd_dumps(runDir);
if height(frames) == 0
    error('analyze_taylor_green_resampling_0126:noFrames', ...
        'No state_step_*.smpcd dumps found in %s', runDir);
end

summaryFile = fullfile(runDir, 'summary_runtime.csv');
if isfile(summaryFile)
    runtime = readtable(summaryFile);
else
    runtime = table();
end

n = height(frames);
labelCol = repmat(string(label), n, 1);
step = frames.step;
time = frames.time;
amplitude = nan(n,1);
correlation = nan(n,1);
gridKinetic = nan(n,1);
divRms = nan(n,1);
divMaxAbs = nan(n,1);
omegaRms = nan(n,1);
fluidParticles = nan(n,1);
inactiveParticles = nan(n,1);
latentParticles = nan(n,1);
meanN = nan(n,1);
stdN = nan(n,1);
kBTEstimate = nan(n,1);
q6DivAfterProjectedFluxRms = nan(n,1);
q6ResidualRel = nan(n,1);
resampMRelRms = nan(n,1);
resampParticleMassRelStd = nan(n,1);
resampExtractionOps = nan(n,1);
resampInsertionOps = nan(n,1);
resampRemapCells = nan(n,1);
resampThermalCells = nan(n,1);
resampMassGuardParticles = nan(n,1);

lastFields = [];
for i = 1:n
    state = read_smpcd_state(char(frames.fullPath(i)));
    fields = bin_smpcd_state(state, 'Lx', Lx, 'Ly', Ly, 'Nx', Nx, 'Ny', Ny, ...
        'periodicX', true, 'periodicY', true, 'fluidOnly', true);
    m = local_tg_metrics(fields, kxMode, kyMode);
    amplitude(i) = m.amplitude;
    correlation(i) = m.correlation;
    gridKinetic(i) = m.gridKinetic;
    divRms(i) = m.divRms;
    divMaxAbs(i) = m.divMaxAbs;
    omegaRms(i) = m.omegaRms;
    lastFields = fields;

    if ~isempty(runtime) && ismember('step', runtime.Properties.VariableNames)
        j = find(runtime.step == step(i), 1, 'first');
        if ~isempty(j)
            kBTEstimate(i) = local_runtime(runtime, j, 'kBTEstimate');
            meanN(i) = local_runtime(runtime, j, 'meanN');
            stdN(i) = local_runtime(runtime, j, 'stdN');
            fluidParticles(i) = local_runtime(runtime, j, 'nFluidParticles');
            inactiveParticles(i) = local_runtime(runtime, j, 'nInactiveParticles');
            latentParticles(i) = local_runtime(runtime, j, 'nLatentParticles');
            q6DivAfterProjectedFluxRms(i) = local_runtime(runtime, j, 'q6DivAfterProjectedFluxRms');
            q6ResidualRel(i) = local_runtime(runtime, j, 'q6ResidualRel');
            resampMRelRms(i) = local_runtime(runtime, j, 'resampMRelRms');
            resampParticleMassRelStd(i) = local_runtime(runtime, j, 'resampParticleMassRelStd');
            resampExtractionOps(i) = local_runtime(runtime, j, 'resampExtractionApplyOpsApplied');
            resampInsertionOps(i) = local_runtime(runtime, j, 'resampInsertionApplyOpsApplied');
            resampRemapCells(i) = local_runtime(runtime, j, 'resampRemapCellsRemapped');
            resampThermalCells(i) = local_runtime(runtime, j, 'resampThermalRenormCellsRenormalized');
            resampMassGuardParticles(i) = local_runtime(runtime, j, 'resampMassGuardParticlesAdjusted');
        end
    end
end

metrics = table(labelCol, step, time, amplitude, correlation, gridKinetic, divRms, divMaxAbs, omegaRms, ...
    fluidParticles, inactiveParticles, latentParticles, meanN, stdN, kBTEstimate, ...
    q6DivAfterProjectedFluxRms, q6ResidualRel, resampMRelRms, resampParticleMassRelStd, ...
    resampExtractionOps, resampInsertionOps, resampRemapCells, resampThermalCells, resampMassGuardParticles, ...
    'VariableNames', {'case','step','time','amplitude','correlation','gridKinetic','divRms','divMaxAbs','omegaRms', ...
    'fluidParticles','inactiveParticles','latentParticles','meanN','stdN','kBTEstimate', ...
    'q6DivAfterProjectedFluxRms','q6ResidualRel','resampMRelRms','resampParticleMassRelStd', ...
    'resampExtractionOps','resampInsertionOps','resampRemapCells','resampThermalCells','resampMassGuardParticles'});

run = struct();
run.label = label;
run.runDir = runDir;
run.params = params;
run.frames = frames;
run.metrics = metrics;
run.finalFields = lastFields;
end

function v = local_runtime(runtime, row, col)
if ismember(col, runtime.Properties.VariableNames)
    v = runtime.(col)(row);
else
    v = nan;
end
end

function m = local_tg_metrics(fields, kxMode, kyMode)
[X, Y] = meshgrid(fields.xc, fields.yc);
Bx = sin(2*pi*kxMode*X/fields.Lx) .* cos(2*pi*kyMode*Y/fields.Ly);
By = -cos(2*pi*kxMode*X/fields.Lx) .* sin(2*pi*kyMode*Y/fields.Ly);
Ux = fields.Ux;
Uy = fields.Uy;
Ux(~isfinite(Ux)) = 0;
Uy(~isfinite(Uy)) = 0;

dotUB = sum(Ux(:).*Bx(:) + Uy(:).*By(:));
normB2 = sum(Bx(:).^2 + By(:).^2);
normU2 = sum(Ux(:).^2 + Uy(:).^2);
amplitude = dotUB / max(normB2, eps);
correlation = dotUB / max(sqrt(normU2 * normB2), eps);

dx = fields.dx;
dy = fields.dy;
dUx_dx = (circshift(Ux, [0 -1]) - circshift(Ux, [0 1])) ./ (2*dx);
dUy_dy = (circshift(Uy, [-1 0]) - circshift(Uy, [1 0])) ./ (2*dy);
div = dUx_dx + dUy_dy;
dUy_dx = (circshift(Uy, [0 -1]) - circshift(Uy, [0 1])) ./ (2*dx);
dUx_dy = (circshift(Ux, [-1 0]) - circshift(Ux, [1 0])) ./ (2*dy);
omega = dUy_dx - dUx_dy;

m = struct();
m.amplitude = amplitude;
m.correlation = correlation;
m.gridKinetic = 0.5 * mean(Ux(:).^2 + Uy(:).^2);
m.divRms = sqrt(mean(div(:).^2));
m.divMaxAbs = max(abs(div(:)));
m.omegaRms = sqrt(mean(omega(:).^2));
end

function summary = local_make_summary(runs)
if isempty(runs)
    summary = table();
    return;
end
n = numel(runs);
caseName = strings(n,1);
initialAmplitude = nan(n,1);
finalAmplitude = nan(n,1);
amplitudeRatio = nan(n,1);
finalCorrelation = nan(n,1);
finalDivRms = nan(n,1);
finalOmegaRms = nan(n,1);
finalKBT = nan(n,1);
finalStdN = nan(n,1);
finalResampMRelRms = nan(n,1);
maxResampMRelRms = nan(n,1);
totalExtracted = nan(n,1);
totalInserted = nan(n,1);
totalMassGuardAdjusted = nan(n,1);
for i = 1:n
    T = runs(i).metrics;
    caseName(i) = string(runs(i).label);
    initialAmplitude(i) = T.amplitude(1);
    finalAmplitude(i) = T.amplitude(end);
    amplitudeRatio(i) = finalAmplitude(i) / max(abs(initialAmplitude(i)), eps);
    finalCorrelation(i) = T.correlation(end);
    finalDivRms(i) = T.divRms(end);
    finalOmegaRms(i) = T.omegaRms(end);
    finalKBT(i) = T.kBTEstimate(end);
    finalStdN(i) = T.stdN(end);
    finalResampMRelRms(i) = T.resampMRelRms(end);
    maxResampMRelRms(i) = max(T.resampMRelRms, [], 'omitnan');
    totalExtracted(i) = sum(T.resampExtractionOps, 'omitnan');
    totalInserted(i) = sum(T.resampInsertionOps, 'omitnan');
    totalMassGuardAdjusted(i) = sum(T.resampMassGuardParticles, 'omitnan');
end
summary = table(caseName, initialAmplitude, finalAmplitude, amplitudeRatio, finalCorrelation, ...
    finalDivRms, finalOmegaRms, finalKBT, finalStdN, finalResampMRelRms, maxResampMRelRms, ...
    totalExtracted, totalInserted, totalMassGuardAdjusted);
end

function local_plot_amplitude(runs, analysisDir)
fig = figure('Name','TG 0126 amplitude and correlation','Visible','on');
tiledlayout(fig, 2, 1);
nexttile; hold on; grid on;
for i = 1:numel(runs)
    T = runs(i).metrics;
    plot(T.time, T.amplitude, 'DisplayName', runs(i).label);
end
xlabel('time'); ylabel('Taylor--Green amplitude'); legend('Location','best');
nexttile; hold on; grid on;
for i = 1:numel(runs)
    T = runs(i).metrics;
    plot(T.time, T.correlation, 'DisplayName', runs(i).label);
end
xlabel('time'); ylabel('pattern correlation'); legend('Location','best');
saveas(fig, fullfile(analysisDir, 'tg_0126_amplitude_correlation.png'));
end

function local_plot_diagnostics(runs, analysisDir)
fig = figure('Name','TG 0126 divergence and mass diagnostics','Visible','on');
tiledlayout(fig, 3, 1);
nexttile; hold on; grid on;
for i = 1:numel(runs)
    T = runs(i).metrics;
    semilogy(T.time, max(T.divRms, realmin), 'DisplayName', runs(i).label);
end
xlabel('time'); ylabel('grid div RMS'); legend('Location','best');
nexttile; hold on; grid on;
for i = 1:numel(runs)
    T = runs(i).metrics;
    semilogy(T.time, max(T.resampMRelRms, realmin), 'DisplayName', runs(i).label);
end
xlabel('time'); ylabel('resamp MRelRMS'); legend('Location','best');
nexttile; hold on; grid on;
for i = 1:numel(runs)
    T = runs(i).metrics;
    plot(T.time, T.stdN, 'DisplayName', runs(i).label);
end
xlabel('time'); ylabel('std(N)'); legend('Location','best');
saveas(fig, fullfile(analysisDir, 'tg_0126_div_mass_population.png'));
end

function local_plot_resampling(runs, analysisDir)
fig = figure('Name','TG 0126 resampling operations','Visible','on');
tiledlayout(fig, 3, 1);
nexttile; hold on; grid on;
for i = 1:numel(runs)
    T = runs(i).metrics;
    plot(T.time, T.resampExtractionOps, 'DisplayName', runs(i).label);
end
xlabel('time'); ylabel('extracted particles/summary'); legend('Location','best');
nexttile; hold on; grid on;
for i = 1:numel(runs)
    T = runs(i).metrics;
    plot(T.time, T.resampInsertionOps, 'DisplayName', runs(i).label);
end
xlabel('time'); ylabel('inserted particles/summary'); legend('Location','best');
nexttile; hold on; grid on;
for i = 1:numel(runs)
    T = runs(i).metrics;
    plot(T.time, T.resampMassGuardParticles, 'DisplayName', runs(i).label);
end
xlabel('time'); ylabel('mass-guard adjusted particles'); legend('Location','best');
saveas(fig, fullfile(analysisDir, 'tg_0126_resampling_operations.png'));
end

function local_plot_final_fields(runs, analysisDir)
for i = 1:numel(runs)
    f = runs(i).finalFields;
    if isempty(f)
        continue;
    end
    fig = figure('Name',sprintf('TG 0126 final fields: %s', runs(i).label),'Visible','on');
    tiledlayout(fig, 2, 2);
    nexttile; imagesc(f.xc, f.yc, f.speed); axis image xy; colorbar; title('speed'); xlabel('x'); ylabel('y');
    nexttile; imagesc(f.xc, f.yc, f.omega); axis image xy; colorbar; title('vorticity'); xlabel('x'); ylabel('y');
    nexttile; imagesc(f.xc, f.yc, f.mass); axis image xy; colorbar; title('cell mass'); xlabel('x'); ylabel('y');
    nexttile; imagesc(f.xc, f.yc, f.N); axis image xy; colorbar; title('cell population'); xlabel('x'); ylabel('y');
    saveas(fig, fullfile(analysisDir, sprintf('tg_0126_final_fields_%s.png', runs(i).label)));
end
end
