function T = analyze_immersed_circle_face_cell_smoke_0100(varargin)
%ANALYZE_IMMERSED_CIRCLE_FACE_CELL_SMOKE_0100 Compact report for the 0100 smoke suite.
%
% T = analyze_immersed_circle_face_cell_smoke_0100()
% T = analyze_immersed_circle_face_cell_smoke_0100('runDirs', {...}, 'writeCsv', true)
%
% This is a fast diagnostic helper, not a physical wake validator. It checks
% final runtime counters, immersed-circle particle leakage, and Q9 sidecar
% availability for the short face/cell-mask smoke suite.

p = inputParser;
p.FunctionName = 'analyze_immersed_circle_face_cell_smoke_0100';
addParameter(p, 'runDirs', { ...
    '../runs/immersed_circle_q6_mask_smoke_48x48_0100', ...
    '../runs/immersed_circle_q9_mask_smoke_48x48_0100', ...
    '../runs/immersed_circle_q9_virial_mask_smoke_48x48_0100'}, @(x) iscell(x) || isstring(x));
addParameter(p, 'circleCx', 0.5, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'circleCy', 0.5, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'circleR', 0.12, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'writeCsv', true, @(x) islogical(x) || isnumeric(x));
addParameter(p, 'outputCsv', '../runs/immersed_circle_face_cell_smoke_0100_summary.csv', @(s) ischar(s) || isstring(s));
parse(p, varargin{:});
opt = p.Results;

runDirs = cellstr(opt.runDirs);
rows = cell(numel(runDirs), 1);

for i = 1:numel(runDirs)
    runDir = char(runDirs{i});
    rows{i} = local_one_run(runDir, opt);
end

T = vertcat(rows{:});
disp(T);

if opt.writeCsv
    out = char(opt.outputCsv);
    outDir = fileparts(out);
    if ~isempty(outDir) && ~exist(outDir, 'dir')
        mkdir(outDir);
    end
    writetable(T, out);
    fprintf('[analyze_immersed_circle_face_cell_smoke_0100] wrote %s\n', out);
end
end

function row = local_one_run(runDir, opt)
summaryPath = fullfile(runDir, 'summary_runtime.csv');
if ~exist(summaryPath, 'file')
    error('analyze_immersed_circle_face_cell_smoke_0100:missingSummary', ...
        'Missing %s', summaryPath);
end
S = readtable(summaryPath);
if isempty(S)
    error('analyze_immersed_circle_face_cell_smoke_0100:emptySummary', ...
        'Empty %s', summaryPath);
end
last = S(end, :);

frameTable = table();
maxInside = NaN;
try
    frameTable = list_smpcd_dumps(runDir);
    maxInside = local_max_particles_inside_circle(frameTable, opt.circleCx, opt.circleCy, opt.circleR);
catch ME
    warning('analyze_immersed_circle_face_cell_smoke_0100:framesSkipped', ...
        'Could not inspect dumps in %s: %s', runDir, ME.message);
end

q9bins = dir(fullfile(runDir, '*.q9bin'));

row = table( ...
    string(runDir), ...
    local_last(last, 'step'), ...
    local_last(last, 'time'), ...
    height(S), ...
    height(frameTable), ...
    numel(q9bins), ...
    maxInside, ...
    local_last(last, 'totalMass'), ...
    local_last(last, 'kBTEstimate'), ...
    local_last(last, 'q6ImmersedSolidLeakProjectedFluxRms'), ...
    local_last(last, 'q9ImmersedHaloExcludedCells'), ...
    local_last(last, 'q9ImmersedSolidFluidCells'), ...
    local_last(last, 'q9ImmersedSolidSolidCells'), ...
    local_last(last, 'q9ImmersedSolidCutCells'), ...
    local_last(last, 'q9ImmersedSolidActiveCutCells'), ...
    local_last(last, 'q9ImmersedSolidActiveAdjacentCells'), ...
    local_last(last, 'q9ImmersedSolidClosedXFaces'), ...
    local_last(last, 'q9ImmersedSolidClosedYFaces'), ...
    local_last(last, 'q9ImmersedSolidLeakMassFluxRms'), ...
    local_last(last, 'q9ImmersedSolidLeakMassFluxMaxAbs'), ...
    local_last(last, 'q9SafetyActiveCells'), ...
    local_last(last, 'q9SafetyExcludedCells'), ...
    local_last(last, 'virialImmersedSolidActiveAdjacentCells'), ...
    local_last(last, 'virialImmersedSolidNormalKickClippedCells'), ...
    local_last(last, 'virialImmersedSolidNormalKickClippedComponents'), ...
    local_last(last, 'virialImmersedSolidNormalKickClippedRms'), ...
    local_last(last, 'virialImmersedSolidNormalKickClippedMaxAbs'), ...
    'VariableNames', { ...
    'runDir', 'finalStep', 'finalTime', 'nSummaryRows', 'nFrames', 'nQ9Sidecars', ...
    'maxParticlesInsideCircle', 'totalMassFinal', 'kBTFinal', ...
    'q6LeakFluxRms', 'q9HaloExcludedCells', 'q9FluidCells', 'q9SolidCells', ...
    'q9CutCells', 'q9ActiveCutCells', 'q9ActiveAdjacentCells', ...
    'q9ClosedXFaces', 'q9ClosedYFaces', 'q9LeakMassFluxRms', ...
    'q9LeakMassFluxMaxAbs', 'q9SafetyActiveCells', 'q9SafetyExcludedCells', ...
    'virialActiveAdjacentCells', 'virialNormalClipCells', ...
    'virialNormalClipComponents', 'virialNormalClipRms', 'virialNormalClipMaxAbs'});
end

function v = local_last(row, name)
if ismember(name, row.Properties.VariableNames)
    v = row.(name)(1);
else
    v = NaN;
end
end

function maxInside = local_max_particles_inside_circle(frameTable, cx, cy, R)
maxInside = NaN;
if isempty(frameTable)
    return;
end
maxInside = 0;
for k = 1:height(frameTable)
    state = read_smpcd_state(frameTable.fullPath{k});
    r2 = (double(state.x(:)) - cx).^2 + (double(state.y(:)) - cy).^2;
    inside = nnz(r2 < (R * (1 - 1e-10))^2);
    maxInside = max(maxInside, inside);
end
end
