function state = generate_piston_active_y095_state(varargin)
%GENERATE_PISTON_ACTIVE_Y095_STATE Generate the standard moving-piston initial state.
%
% Intended to be launched from the matlab/ directory. By default the state is
% written one level above matlab/, where the C++ executable is launched.

p = inputParser;
p.FunctionName = 'generate_piston_active_y095_state';
addParameter(p, 'output', '../initial_state_active_y095.smpcd', @(s) ischar(s) || isstring(s));
addParameter(p, 'Lx', 1.0, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'LyActive', 0.95, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'Nx', 32, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'Ny', 32, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'gamma', 80, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'kBT', 0.01, @(x) isnumeric(x) && isscalar(x) && x >= 0);
addParameter(p, 'mass', 1.0, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'seed', 12345, @(x) isnumeric(x) && isscalar(x));
parse(p, varargin{:});
opts = p.Results;

state = generate_smpcd_state_uniform( ...
    'output', char(opts.output), ...
    'Lx', opts.Lx, ...
    'Ly', opts.LyActive, ...
    'Nx', opts.Nx, ...
    'Ny', opts.Ny, ...
    'gamma', opts.gamma, ...
    'kBT', opts.kBT, ...
    'mass', opts.mass, ...
    'type', 0, ...
    'seed', opts.seed);
end
