function state = generate_poiseuille_q6_channel_short_state(varargin)
%GENERATE_POISEUILLE_Q6_CHANNEL_SHORT_STATE Generate the initial state for Q6 channel smoke tests.
%
% Run from the matlab/ directory:
%   state = generate_poiseuille_q6_channel_short_state();
%
% This writes ../initial_state_poiseuille_32x32_g40_kbt0p01.smpcd, which is the
% inputState used by the short classic/Q6 Poiseuille examples.

p = inputParser;
p.FunctionName = 'generate_poiseuille_q6_channel_short_state';
addParameter(p, 'output', '../initial_state_poiseuille_32x32_g40_kbt0p01.smpcd', @(s) ischar(s) || isstring(s));
addParameter(p, 'Lx', 1.0, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'Ly', 1.0, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'Nx', 32, @(x) isnumeric(x) && isscalar(x) && x >= 1);
addParameter(p, 'Ny', 32, @(x) isnumeric(x) && isscalar(x) && x >= 1);
addParameter(p, 'gamma', 40, @(x) isnumeric(x) && isscalar(x) && x >= 1);
addParameter(p, 'kBT', 0.01, @(x) isnumeric(x) && isscalar(x) && x >= 0);
addParameter(p, 'seed', 12345, @(x) isnumeric(x) && isscalar(x));
parse(p, varargin{:});
opt = p.Results;

state = generate_smpcd_state_uniform( ...
    'output', char(string(opt.output)), ...
    'Lx', opt.Lx, ...
    'Ly', opt.Ly, ...
    'Nx', opt.Nx, ...
    'Ny', opt.Ny, ...
    'gamma', opt.gamma, ...
    'kBT', opt.kBT, ...
    'mass', 1.0, ...
    'type', 0, ...
    'seed', opt.seed, ...
    'mode', 'uniform_per_cell', ...
    'velocityMode', 'maxwell', ...
    'removeMeanMomentum', true);

fprintf('Wrote Poiseuille Q6-channel initial state: %s\n', char(string(opt.output)));
end
