function state = generate_q9_beta_sweep_state(varargin)
%GENERATE_Q9_BETA_SWEEP_STATE Generate the initial state for the Q9 beta sweep.
%
% Run from the matlab/ directory:
%   addpath('.')
%   state = generate_q9_beta_sweep_state();
%
% The state is written one directory above matlab/, so the C++ executable can be
% launched from the repository root.

p = inputParser;
p.FunctionName = 'generate_q9_beta_sweep_state';
addParameter(p, 'output', '../initial_state_q9_sweep_32x32_g20.smpcd', @(s) ischar(s) || isstring(s));
addParameter(p, 'Lx', 1.0, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'Ly', 1.0, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'Nx', 32, @(x) isnumeric(x) && isscalar(x) && x >= 1);
addParameter(p, 'Ny', 32, @(x) isnumeric(x) && isscalar(x) && x >= 1);
addParameter(p, 'gamma', 20, @(x) isnumeric(x) && isscalar(x) && x >= 1);
addParameter(p, 'kBT', 0.01, @(x) isnumeric(x) && isscalar(x) && x >= 0);
addParameter(p, 'seed', 12345, @(x) isnumeric(x) && isscalar(x));
parse(p, varargin{:});
opt = p.Results;

state = generate_smpcd_state_uniform( ...
    'output', char(opt.output), ...
    'Lx', opt.Lx, ...
    'Ly', opt.Ly, ...
    'Nx', opt.Nx, ...
    'Ny', opt.Ny, ...
    'gamma', opt.gamma, ...
    'kBT', opt.kBT, ...
    'mass', 1.0, ...
    'type', 0, ...
    'seed', opt.seed, ...
    'mode', 'uniform_per_cell', ...
    'velocityMode', 'maxwell', ...
    'removeMeanMomentum', true);
end
