function T = plot_topo_naca_alpha_u0_sensitivity_0355(combinedCsv, varargin)
%PLOT_TOPO_NACA_ALPHA_U0_SENSITIVITY_0355 Plot NACA sensitivity to alphaMax and U0.
%
% T = plot_topo_naca_alpha_u0_sensitivity_0355(combinedCsv, 'OutputDir', outDir)
%
% Input: naca_alpha_u0_sweep_0355_combined.csv generated by
% scripts/run_topo_darcy_naca_alpha_u0_sweep_0355.sh.

p = inputParser;
addRequired(p, 'combinedCsv', @(s)ischar(s) || isstring(s));
addParameter(p, 'OutputDir', fullfile('runs','topo_matlab_plots_0355'), @(s)ischar(s) || isstring(s));
addParameter(p, 'ShowFigures', true, @(x)islogical(x) || isnumeric(x));
addParameter(p, 'Prefix', 'naca_alpha_u0_sensitivity_0355', @(s)ischar(s) || isstring(s));
parse(p, combinedCsv, varargin{:});

combinedCsv = char(p.Results.combinedCsv);
outDir = char(p.Results.OutputDir);
showFigures = logical(p.Results.ShowFigures);
prefix = char(p.Results.Prefix);
if ~exist(outDir, 'dir')
    mkdir(outDir);
end

T = readtable(combinedCsv, 'VariableNamingRule', 'preserve');
T = sortrows(T, {'U0_sweep','alphaMax','aoaDeg'});

% Normalise inside each (alphaMax,U0) group.
T.dragNorm = nan(height(T),1);
T.liftNorm = nan(height(T),1);
groups = unique([T.alphaMax, T.U0_sweep], 'rows');
for g = 1:size(groups,1)
    a = groups(g,1);
    u = groups(g,2);
    idx = T.alphaMax == a & T.U0_sweep == u;
    aoa = T.aoaDeg(idx);
    drag = T.dragProxy_mean(idx);
    lift = T.liftProxy_mean(idx);
    drag0 = interp1(aoa, drag, 0, 'linear', 'extrap');
    lift10 = interp1(aoa, lift, 10, 'linear', 'extrap');
    if ~isfinite(drag0) || abs(drag0) < eps, drag0 = max(abs(drag)); end
    if ~isfinite(lift10) || abs(lift10) < eps, lift10 = max(abs(lift)); end
    T.dragNorm(idx) = drag ./ abs(drag0);
    T.liftNorm(idx) = lift ./ abs(lift10);
end

normCsv = fullfile(outDir, [prefix '_normalized.csv']);
writetable(T, normCsv);

visibleState = ternary(showFigures, 'on', 'off');

plot_grouped(T, 'dragNorm', 'AoA [deg]', 'dragProxy / dragProxy(0)', ...
    'NACA drag shape sensitivity', fullfile(outDir, [prefix '_drag_norm']), visibleState);

plot_grouped(T, 'liftNorm', 'AoA [deg]', 'liftProxy / |liftProxy(10)|', ...
    'NACA lift shape sensitivity', fullfile(outDir, [prefix '_lift_norm']), visibleState);

plot_grouped(T, 'liftOverDragProxy', 'AoA [deg]', 'liftProxy / dragProxy', ...
    'NACA finesse proxy sensitivity', fullfile(outDir, [prefix '_finesse']), visibleState);

plot_grouped(T, 'darcyPower_mean', 'AoA [deg]', 'darcyPower mean', ...
    'NACA Darcy power sensitivity', fullfile(outDir, [prefix '_darcy_power']), visibleState);

% Drag-vs-lift polar proxy.
fig = figure('Visible', visibleState);
hold on;
labels = {};
for g = 1:size(groups,1)
    a = groups(g,1);
    u = groups(g,2);
    idx = T.alphaMax == a & T.U0_sweep == u;
    plot(T.dragProxy_mean(idx), T.liftProxy_mean(idx), '-o', 'LineWidth', 1.2);
    labels{end+1} = sprintf('\\alpha_{max}=%.4g, U0=%.4g', a, u); %#ok<AGROW>
end
grid on;
xlabel('dragProxy mean');
ylabel('liftProxy mean');
title('NACA lift-vs-drag sensitivity');
legend(labels, 'Location', 'best');
save_fig(fig, fullfile(outDir, [prefix '_lift_vs_drag']));
if ~showFigures, close(fig); end

fprintf('[0355-matlab] input=%s\n', combinedCsv);
fprintf('[0355-matlab] normalizedCsv=%s\n', normCsv);
end

function plot_grouped(T, yName, xl, yl, ttl, base, visibleState)
fig = figure('Visible', visibleState);
hold on;
groups = unique([T.alphaMax, T.U0_sweep], 'rows');
labels = {};
for g = 1:size(groups,1)
    a = groups(g,1);
    u = groups(g,2);
    idx = T.alphaMax == a & T.U0_sweep == u;
    plot(T.aoaDeg(idx), T.(yName)(idx), '-o', 'LineWidth', 1.2);
    labels{end+1} = sprintf('\\alpha_{max}=%.4g, U0=%.4g', a, u); %#ok<AGROW>
end
grid on;
xlabel(xl);
ylabel(yl);
title(ttl);
legend(labels, 'Location', 'best');
save_fig(fig, base);
if strcmp(get(fig, 'Visible'), 'off'), close(fig); end
end

function save_fig(fig, base)
png = [base '.png'];
pdf = [base '.pdf'];
saveas(fig, png);
saveas(fig, pdf);
fprintf('[0355-matlab] wrote %s\n', png);
fprintf('[0355-matlab] wrote %s\n', pdf);
end

function out = ternary(cond, a, b)
if cond, out = a; else, out = b; end
end
