function state = prepare_taylor_green_random_population_resampling_0128(varargin)
%PREPARE_TAYLOR_GREEN_RANDOM_POPULATION_RESAMPLING_0128 Generate a random-population TG state.
%
% This MATLAB generator prepares a periodic Taylor--Green .smpcd V2 state with
% a spatially random, bounded, non-homogeneous Fluid population per cell.  It
% is meant to trigger the OpenMP weighted-resampling path in a distributed way,
% closer to the random population tests used during the MATLAB development of
% the poor-cell correction.
%
% Usage from the repository matlab/ directory:
%
%   prepare_taylor_green_random_population_resampling_0128( ...
%       'output', '../init/taylor_green_random_population_resampling_0128/initial_state_tg_random_pop_0128.smpcd');
%
% Role convention written to the V2 .smpcd state:
%   0 = Inactive
%   1 = Fluid
%   2 = Latent
%
% Only Fluid particles are generated by default.  The total number of Fluid
% particles is exactly Nx*Ny*gamma, but the cell populations are random and
% bounded between populationMin and populationMax.

p = inputParser;
p.FunctionName = 'prepare_taylor_green_random_population_resampling_0128';
addParameter(p, 'output', fullfile('..','init','taylor_green_random_population_resampling_0128','initial_state_tg_random_pop_0128.smpcd'), @(s) ischar(s) || isstring(s));
addParameter(p, 'layoutCsv', '', @(s) ischar(s) || isstring(s));
addParameter(p, 'Lx', 1.0, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'Ly', 1.0, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'Nx', 32, @(x) isnumeric(x) && isscalar(x) && x >= 4 && abs(x-round(x)) < eps);
addParameter(p, 'Ny', 32, @(x) isnumeric(x) && isscalar(x) && x >= 4 && abs(x-round(x)) < eps);
addParameter(p, 'gamma', 20, @(x) isnumeric(x) && isscalar(x) && x >= 1 && abs(x-round(x)) < eps);
addParameter(p, 'populationStd', 6.0, @(x) isnumeric(x) && isscalar(x) && x >= 0);
addParameter(p, 'populationMin', [], @(x) isempty(x) || (isnumeric(x) && isscalar(x) && x >= 0));
addParameter(p, 'populationMax', [], @(x) isempty(x) || (isnumeric(x) && isscalar(x) && x >= 1));
addParameter(p, 'poorFractionForLayout', 0.90, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'richFractionForLayout', 1.10, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'flowAmplitude', 0.08, @(x) isnumeric(x) && isscalar(x) && x >= 0);
addParameter(p, 'kxMode', 1, @(x) isnumeric(x) && isscalar(x) && x >= 1 && abs(x-round(x)) < eps);
addParameter(p, 'kyMode', 1, @(x) isnumeric(x) && isscalar(x) && x >= 1 && abs(x-round(x)) < eps);
addParameter(p, 'kBT', 0.001, @(x) isnumeric(x) && isscalar(x) && x >= 0);
addParameter(p, 'mass', 1.0, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'type', uint32(0), @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'seed', 1280128, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'makePreview', false, @(x) islogical(x) && isscalar(x));
parse(p, varargin{:});
opt = p.Results;

Nx = double(opt.Nx);
Ny = double(opt.Ny);
gamma = double(opt.gamma);
Lx = double(opt.Lx);
Ly = double(opt.Ly);
dx = Lx / Nx;
dy = Ly / Ny;
Ncells = Nx * Ny;
NpTarget = round(Ncells * gamma);

if isempty(opt.populationMin)
    nMin = max(0, floor(gamma - 2.0 * double(opt.populationStd)));
else
    nMin = round(double(opt.populationMin));
end
if isempty(opt.populationMax)
    nMax = max(nMin + 1, ceil(gamma + 2.0 * double(opt.populationStd)));
else
    nMax = round(double(opt.populationMax));
end
if nMin > gamma || nMax < gamma
    error('prepare_taylor_green_random_population_resampling_0128:badBounds', ...
        'populationMin/populationMax must bracket gamma so total population can be balanced.');
end
if Ncells*nMin > NpTarget || Ncells*nMax < NpTarget
    error('prepare_taylor_green_random_population_resampling_0128:infeasibleBounds', ...
        'Population bounds are infeasible for exact total Nx*Ny*gamma.');
end

rng(double(opt.seed), 'twister');
counts = round(gamma + double(opt.populationStd) * randn(Ncells, 1));
counts = min(max(counts, nMin), nMax);
counts = balance_counts_to_total(counts, NpTarget, nMin, nMax, double(opt.seed) + 11);

Np = sum(counts);
x = zeros(Np, 1);
y = zeros(Np, 1);
cellIx = zeros(Np, 1);
cellIy = zeros(Np, 1);
q = 0;
rng(double(opt.seed) + 21, 'twister');
for iy = 1:Ny
    for ix = 1:Nx
        c = sub2ind([Ny, Nx], iy, ix);
        nc = counts(c);
        if nc <= 0
            continue;
        end
        ids = q + (1:nc);
        x(ids) = (ix - 1 + rand(nc, 1)) * dx;
        y(ids) = (iy - 1 + rand(nc, 1)) * dy;
        cellIx(ids) = ix;
        cellIy(ids) = iy;
        q = q + nc;
    end
end
if q ~= Np
    error('prepare_taylor_green_random_population_resampling_0128:internalCountMismatch', ...
        'Internal population mismatch.');
end

[vx, vy] = local_taylor_green_velocity(x, y, Lx, Ly, opt.flowAmplitude, opt.kxMode, opt.kyMode);
if opt.kBT > 0
    sigma = sqrt(double(opt.kBT) / double(opt.mass));
    rng(double(opt.seed) + 22, 'twister');
    vx = vx + sigma * randn(Np, 1);
    vy = vy + sigma * randn(Np, 1);
end

mass = repmat(double(opt.mass), Np, 1);
type = repmat(uint32(opt.type), Np, 1);
role = ones(Np, 1, 'uint8');

% Remove global mean momentum on Fluid particles.
M = sum(mass);
vx = vx - sum(mass .* vx) / M;
vy = vy - sum(mass .* vy) / M;

state = struct();
state.x = x;
state.y = y;
state.vx = vx;
state.vy = vy;
state.type = type;
state.mass = mass;
state.role = role;
state.metadata.generator = 'prepare_taylor_green_random_population_resampling_0128';
state.metadata.populationStd = opt.populationStd;
state.metadata.populationMin = nMin;
state.metadata.populationMax = nMax;
state.metadata.populationCounts = counts;

output = char(opt.output);
if ~isempty(output)
    outDir = fileparts(output);
    if ~isempty(outDir) && ~isfolder(outDir)
        mkdir(outDir);
    end
    write_smpcd_state(output, state);
end

layoutCsv = char(opt.layoutCsv);
if isempty(layoutCsv) && ~isempty(output)
    [outDir,~,~] = fileparts(output);
    layoutCsv = fullfile(outDir, 'initial_random_population_layout_0128.csv');
end
if ~isempty(layoutCsv)
    layoutDir = fileparts(layoutCsv);
    if ~isempty(layoutDir) && ~isfolder(layoutDir)
        mkdir(layoutDir);
    end
    write_layout_csv(layoutCsv, counts, Nx, Ny, gamma, opt.poorFractionForLayout, opt.richFractionForLayout);
end

if opt.makePreview
    make_preview_figure(counts, Nx, Ny, output);
end

fprintf('Prepared Taylor--Green random-population resampling state 0128:\n');
fprintf('  output          : %s\n', output);
fprintf('  grid            : %d x %d, gamma=%d\n', Nx, Ny, gamma);
fprintf('  particles       : total=%d fluid=%d latent=%d inactive=%d\n', ...
    numel(x), sum(role==1), sum(role==2), sum(role==0));
fprintf('  population      : min=%d max=%d mean=%.12g std=%.12g\n', ...
    min(counts), max(counts), mean(counts), std(double(counts), 1));
fprintf('  poor/rich cells : poor=%d rich=%d with layout thresholds %.3g/%.3g of gamma\n', ...
    sum(counts < opt.poorFractionForLayout*gamma), ...
    sum(counts > opt.richFractionForLayout*gamma), ...
    opt.poorFractionForLayout, opt.richFractionForLayout);
fprintf('  layout csv      : %s\n', layoutCsv);
end

function counts = balance_counts_to_total(counts, target, nMin, nMax, seed)
rng(seed, 'twister');
counts = round(double(counts(:)));
target = round(double(target));
nMin = round(double(nMin));
nMax = round(double(nMax));
iter = 0;
maxIter = 10 * numel(counts) * max(1, nMax - nMin + 1);
while sum(counts) < target
    avail = find(counts < nMax);
    if isempty(avail)
        error('balance_counts_to_total:noUpperCapacity', 'Cannot increase population to requested target.');
    end
    i = avail(randi(numel(avail)));
    counts(i) = counts(i) + 1;
    iter = iter + 1;
    if iter > maxIter
        error('balance_counts_to_total:maxIterIncrease', 'Balancing failed while increasing counts.');
    end
end
while sum(counts) > target
    avail = find(counts > nMin);
    if isempty(avail)
        error('balance_counts_to_total:noLowerCapacity', 'Cannot decrease population to requested target.');
    end
    i = avail(randi(numel(avail)));
    counts(i) = counts(i) - 1;
    iter = iter + 1;
    if iter > maxIter
        error('balance_counts_to_total:maxIterDecrease', 'Balancing failed while decreasing counts.');
    end
end
end

function [vx, vy] = local_taylor_green_velocity(x, y, Lx, Ly, U0, kxMode, kyMode)
phaseX = 2*pi*double(kxMode)*double(x(:))/double(Lx);
phaseY = 2*pi*double(kyMode)*double(y(:))/double(Ly);
vx = double(U0) .* sin(phaseX) .* cos(phaseY);
vy = -double(U0) .* cos(phaseX) .* sin(phaseY);
end

function write_layout_csv(filename, counts, Nx, Ny, gamma, poorFrac, richFrac)
[ix, iy] = meshgrid(1:Nx, 1:Ny);
N = counts(:);
T = table();
T.ix = ix(:);
T.iy = iy(:);
T.nFluid = N;
T.mass = N;
T.nOverGamma = double(N) ./ double(gamma);
T.isPoor = double(N) < double(poorFrac) * double(gamma);
T.isRich = double(N) > double(richFrac) * double(gamma);
T.isEmpty = N == 0;
writetable(T, filename);
end

function make_preview_figure(counts, Nx, Ny, output)
fig = figure('Name', 'TG random population 0128', 'Visible', 'on');
imagesc(reshape(counts, [Ny, Nx])); axis image; colorbar;
title('Initial random Fluid population per cell');
xlabel('ix'); ylabel('iy');
if ~isempty(output)
    [outDir,~,~] = fileparts(output);
    if ~isempty(outDir)
        saveas(fig, fullfile(outDir, 'initial_random_population_preview_0128.png'));
    end
end
end
