%RUN_PERIODIC_DARCY_STEP_ANALYSIS_0493X7W Launcher for existing x7w triplet.
%
% Run FROM repository matlab/ after copying analyze_periodic_darcy_step_0493x7w.m
% into matlab/. No simulation is launched or modified.
%
% Cross-mode comparison is aligned on monotone convective age tau_H.
% Coherent fields are averaged over tau_H windows [1,3], [4,6], [7,9].

clear x7wRunRoot x7wAnalysisOutput suite

x7wRunRoot = '../runs/0493x7w_periodic_darcy_step_512x128_g6_u0.9';
x7wAnalysisOutput = [x7wRunRoot '_analysis_0493x7w'];

suite = analyze_periodic_darcy_step_0493x7w( ...
    'RunRoot', x7wRunRoot, ...
    'OutputDir', x7wAnalysisOutput, ...
    'StrictTriplet', true, ...
    'DumpStride', 1, ...
    'AnalysisBinsPerH', 16, ...
    'SensitivityCheck', true, ...
    'SensitivityBinsPerH', 12, ...
    'MatchedTauLevels', 17, ...
    'SummaryTauRangeH', [1 Inf], ...
    'TauWindowsH', [1 3; 4 6; 7 9], ...
    'MakePlots', true, ...
    'ShowFigures', true, ...
    'WritePdf', true);

disp(suite.summary)
disp(suite.tauWindowFieldMetrics)
