function suite = validate_backward_step_parametric_suite(varargin)
%VALIDATE_BACKWARD_STEP_PARAMETRIC_SUITE Analyze the immersed-step Q6/Q9 parameter sweep.
%
% This wrapper expects the run directories generated by:
%   scripts/run_backward_step_parametric_suite.sh
%
% Example from repository root:
%   cd matlab
%   suite = validate_backward_step_parametric_suite();
%
% The sweep is still a periodic-x forced-channel test with an immersed
% rectangle. It is meant to tune masked Q6/Q9 strength before inlet/outlet
% boundary conditions are introduced.

    p = inputParser;
    addParameter(p, 'runDirs', local_default_run_dirs(), @(x) iscell(x) || isstring(x));
    addParameter(p, 'labels', {}, @(x) iscell(x) || isstring(x));
    addParameter(p, 'makePlots', true, @(x) islogical(x) || isnumeric(x));
    addParameter(p, 'field', 'omega', @(s) ischar(s) || isstring(s));
    addParameter(p, 'averageLastFraction', 0.50, @(x) isnumeric(x) && isscalar(x) && x > 0 && x <= 1);
    addParameter(p, 'outputDir', '../runs/backward_step_parametric_suite_analysis', @(s) ischar(s) || isstring(s));
    parse(p, varargin{:});
    opt = p.Results;

    runDirs = cellstr(opt.runDirs);
    existing = false(size(runDirs));
    for i = 1:numel(runDirs)
        existing(i) = exist(runDirs{i}, 'dir') == 7;
    end
    if ~any(existing)
        error('validate_backward_step_parametric_suite:missingRuns', ...
            'No default parametric run directories were found. Run scripts/run_backward_step_parametric_suite.sh first, or pass runDirs explicitly.');
    end
    if ~all(existing)
        missing = runDirs(~existing);
        fprintf('[parametric] skipping %d missing default run(s):\n', numel(missing));
        for i = 1:numel(missing)
            fprintf('  %s\n', missing{i});
        end
    end
    runDirs = runDirs(existing);

    labels = cellstr(opt.labels);
    if isempty(labels)
        labels = local_default_labels(runDirs);
    else
        labels = labels(existing);
    end

    suite = validate_backward_step_masked_structure_suite( ...
        'runDirs', runDirs, ...
        'labels', labels, ...
        'makePlots', opt.makePlots, ...
        'field', char(opt.field), ...
        'averageLastFraction', opt.averageLastFraction, ...
        'outputDir', char(opt.outputDir));

    writetable(suite.summary, fullfile(char(opt.outputDir), 'backward_step_parametric_suite_summary.csv'));

    if opt.makePlots
        local_plot_parametric_metrics(suite, char(opt.outputDir));
    end
end

function runDirs = local_default_run_dirs()
    runDirs = { ...
        '../runs/backward_step_parametric_classic_96x48', ...
        '../runs/backward_step_parametric_q6_s0p25_96x48', ...
        '../runs/backward_step_parametric_q6_s0p50_96x48', ...
        '../runs/backward_step_parametric_q6_s0p75_96x48', ...
        '../runs/backward_step_parametric_q6_s1p00_96x48', ...
        '../runs/backward_step_parametric_q9_s0p50_b0p00025_k2_96x48', ...
        '../runs/backward_step_parametric_q9_s0p50_b0p00100_k2_96x48', ...
        '../runs/backward_step_parametric_q9_s0p50_b0p00400_k2_96x48', ...
        '../runs/backward_step_parametric_q9_s0p50_b0p00100_k4_96x48'};
end

function labels = local_default_labels(runDirs)
    labels = cell(size(runDirs));
    for i = 1:numel(runDirs)
        rd = char(runDirs{i});
        if contains(rd, 'classic')
            labels{i} = 'classic';
        elseif contains(rd, 'q6_s0p25')
            labels{i} = 'Q6 s=0.25';
        elseif contains(rd, 'q6_s0p50')
            labels{i} = 'Q6 s=0.50';
        elseif contains(rd, 'q6_s0p75')
            labels{i} = 'Q6 s=0.75';
        elseif contains(rd, 'q6_s1p00')
            labels{i} = 'Q6 s=1.00';
        elseif contains(rd, 'q9_s0p50_b0p00025_k2')
            labels{i} = 'Q9 s=0.50 beta=2.5e-4 k=2';
        elseif contains(rd, 'q9_s0p50_b0p00100_k2')
            labels{i} = 'Q9 s=0.50 beta=1e-3 k=2';
        elseif contains(rd, 'q9_s0p50_b0p00400_k2')
            labels{i} = 'Q9 s=0.50 beta=4e-3 k=2';
        elseif contains(rd, 'q9_s0p50_b0p00100_k4')
            labels{i} = 'Q9 s=0.50 beta=1e-3 k=4';
        else
            [~, name] = fileparts(rd);
            labels{i} = name;
        end
    end
end

function local_plot_parametric_metrics(suite, outputDir)
    tbl = suite.summary;
    if isempty(tbl)
        return;
    end

    isQ6 = strcmp(tbl.method, 'q6');
    isQ9 = strcmp(tbl.method, 'q9');

    fig = figure('Name', 'Backward step parametric suite: scalar metrics');
    tiledlayout(2, 3, 'TileSpacing', 'compact', 'Padding', 'compact');

    nexttile;
    local_plot_by_strength(tbl, isQ6, isQ9, 'omegaRmsDownstream');
    ylabel('omega RMS downstream'); title('Vorticity RMS'); grid on;

    nexttile;
    local_plot_by_strength(tbl, isQ6, isQ9, 'reversedUxFraction');
    ylabel('reversed Ux fraction'); title('Recirculation fraction'); grid on;

    nexttile;
    local_plot_by_strength(tbl, isQ6, isQ9, 'meanUxDownstreamOverThermal');
    ylabel('<Ux> downstream / u_{th}'); title('Mean-flow signal'); grid on;

    nexttile;
    local_plot_by_strength(tbl, isQ6, isQ9, 'stdNLate');
    ylabel('std(N) late'); title('Density scatter'); grid on;

    nexttile;
    local_plot_by_strength(tbl, isQ6, isQ9, 'q6DivAfterProjectedFluxRmsLate');
    ylabel('Q6 div after projected flux'); title('Projection residual after under-relaxation'); grid on;

    nexttile;
    local_plot_by_strength(tbl, isQ6, isQ9, 'q6CorrectionVelocityRmsLate');
    ylabel('Q6 correction velocity RMS'); title('Q6 kick amplitude'); grid on;

    saveas(fig, fullfile(outputDir, 'backward_step_parametric_suite_scalar_metrics.png'));

    figC = figure('Name', 'Backward step parametric suite: coherence metrics');
    tiledlayout(2, 3, 'TileSpacing', 'compact', 'Padding', 'compact');

    nexttile;
    local_plot_by_strength(tbl, isQ6, isQ9, 'omegaCoherenceRatioDownstream');
    ylabel('omega coherent / total RMS'); title('Temporal coherence'); grid on;

    nexttile;
    local_plot_by_strength(tbl, isQ6, isQ9, 'omegaFluctToCoherentRatioDownstream');
    ylabel('omega fluct / coherent RMS'); title('Fluctuation loading'); grid on;

    nexttile;
    local_plot_by_strength(tbl, isQ6, isQ9, 'omegaMeanLowKFractionDownstream');
    ylabel('mean omega low-k fraction'); title('Large-scale content'); grid on;

    nexttile;
    local_plot_by_strength(tbl, isQ6, isQ9, 'uxReversePersistenceMeanDownstream');
    ylabel('mean P(Ux<0)'); title('Reverse persistence'); grid on;

    nexttile;
    local_plot_by_strength(tbl, isQ6, isQ9, 'reversedLargestComponentFraction');
    ylabel('largest reversed component fraction'); title('Recirculation compactness'); grid on;

    nexttile;
    local_plot_by_strength(tbl, isQ6, isQ9, 'reversedComponentCount');
    ylabel('component count'); title('Recirculation fragmentation'); grid on;

    saveas(figC, fullfile(outputDir, 'backward_step_parametric_suite_coherence_metrics.png'));

    figP = figure('Name', 'Backward step parametric suite: population reliability metrics');
    tiledlayout(2, 3, 'TileSpacing', 'compact', 'Padding', 'compact');

    nexttile;
    local_plot_by_strength(tbl, isQ6, isQ9, 'populationP05DownstreamOverReference');
    ylabel('P05(N) downstream / ref'); title('Downstream low-tail population'); grid on;

    nexttile;
    local_plot_by_strength(tbl, isQ6, isQ9, 'populationLowHalfRefFractionDownstream');
    ylabel('fraction N < 0.5 ref'); title('Downstream under-populated cells'); grid on;

    nexttile;
    local_plot_by_strength(tbl, isQ6, isQ9, 'populationTemporalCvMeanDownstream');
    ylabel('mean temporal CV(N)'); title('Downstream population intermittency'); grid on;

    nexttile;
    local_plot_by_strength(tbl, isQ6, isQ9, 'populationP05ReversedOverReference');
    ylabel('P05(N) reversed / ref'); title('Recirculation low-tail population'); grid on;

    nexttile;
    local_plot_by_strength(tbl, isQ6, isQ9, 'populationLowHalfRefFractionReversed');
    ylabel('fraction N < 0.5 ref'); title('Recirculation under-populated cells'); grid on;

    nexttile;
    local_plot_by_strength(tbl, isQ6, isQ9, 'populationBelow5FractionReversed');
    ylabel('fraction N < 5'); title('Recirculation cells below N=5'); grid on;

    saveas(figP, fullfile(outputDir, 'backward_step_parametric_suite_population_metrics.png'));

    if any(isQ9)
        fig2 = figure('Name', 'Backward step parametric suite: Q9 tuning');
        tiledlayout(2, 2, 'TileSpacing', 'compact', 'Padding', 'compact');

        nexttile;
        scatter(tbl.q9DensityRelaxationBetaParam(isQ9), tbl.q9DensityStdRatioEstimateLate(isQ9), 60, 'filled');
        set(gca, 'XScale', 'log'); grid on; xlabel('q9DensityRelaxationBeta'); ylabel('density std ratio estimate');
        title('Q9 density relaxation');

        nexttile;
        scatter(tbl.q9DensityRelaxationBetaParam(isQ9), tbl.q9CorrectionVelocityRmsLate(isQ9), 60, 'filled');
        set(gca, 'XScale', 'log'); grid on; xlabel('q9DensityRelaxationBeta'); ylabel('Q9 correction RMS');
        title('Q9 kick amplitude');

        nexttile;
        scatter(tbl.q9LowKMaxIndexParam(isQ9), tbl.q9TargetDivergenceFilterRatioLate(isQ9), 60, 'filled');
        grid on; xlabel('q9LowKMaxIndex'); ylabel('target-div filter ratio');
        title('Low-k filter response');

        nexttile;
        scatter(tbl.q9DensityRelaxationBetaParam(isQ9), tbl.omegaRmsDownstream(isQ9), 60, 'filled');
        set(gca, 'XScale', 'log'); grid on; xlabel('q9DensityRelaxationBeta'); ylabel('omega RMS downstream');
        title('Structure impact');

        saveas(fig2, fullfile(outputDir, 'backward_step_parametric_suite_q9_metrics.png'));
    end
end

function local_plot_by_strength(tbl, isQ6, isQ9, metricName)
    hold on;
    if any(isQ6)
        plot(tbl.q6ProjectionStrengthParam(isQ6), tbl.(metricName)(isQ6), '-o', 'DisplayName', 'Q6');
    end
    if any(isQ9)
        plot(tbl.q6ProjectionStrengthParam(isQ9), tbl.(metricName)(isQ9), 's', 'DisplayName', 'Q9');
    end
    if any(strcmp(tbl.method, 'classic'))
        classic = strcmp(tbl.method, 'classic');
        y = mean(tbl.(metricName)(classic), 'omitnan');
        yline(y, 'k--', 'DisplayName', 'classic');
    end
    xlabel('q6ProjectionStrength');
    legend('Location', 'best', 'Interpreter', 'none');
    hold off;
end
