function suite = validate_backward_step_final_liquid_config(varargin)
%VALIDATE_BACKWARD_STEP_FINAL_LIQUID_CONFIG Analyze the final immersed-step Q9/virial candidate.
%
% The default comparison uses the no-virial lowK=4 hard-wall calibration run
% and the final lowK=4 virial run generated by:
%   scripts/run_backward_step_final_liquid_config_test.sh
%
% Example from repository root:
%   cd matlab
%   suite = validate_backward_step_final_liquid_config();

    p = inputParser;
    addParameter(p, 'runDirs', local_default_run_dirs(), @(x) iscell(x) || isstring(x));
    addParameter(p, 'labels', {}, @(x) iscell(x) || isstring(x));
    addParameter(p, 'makePlots', true, @(x) islogical(x) || isnumeric(x));
    addParameter(p, 'field', 'omega', @(s) ischar(s) || isstring(s));
    addParameter(p, 'averageLastFraction', 0.50, @(x) isnumeric(x) && isscalar(x) && x > 0 && x <= 1);
    addParameter(p, 'outputDir', '../runs/backward_step_final_liquid_config_analysis', @(s) ischar(s) || isstring(s));
    parse(p, varargin{:});
    opt = p.Results;

    runDirs = cellstr(string(opt.runDirs));
    labels = cellstr(string(opt.labels));
    if isempty(labels)
        labels = local_default_labels(runDirs);
    end
    if numel(labels) ~= numel(runDirs)
        error('validate_backward_step_final_liquid_config:labels', 'labels and runDirs must have the same length.');
    end

    existing = false(size(runDirs));
    for i = 1:numel(runDirs)
        existing(i) = exist(runDirs{i}, 'dir') == 7;
    end
    if ~all(existing)
        missing = runDirs(~existing);
        fprintf('[final-liquid-config] missing run directories:\n');
        for i = 1:numel(missing)
            fprintf('  %s\n', missing{i});
        end
        error('validate_backward_step_final_liquid_config:missingRuns', ...
            'Run scripts/run_backward_step_final_liquid_config_test.sh, or pass runDirs explicitly.');
    end

    outputDir = char(opt.outputDir);
    if ~exist(outputDir, 'dir')
        mkdir(outputDir);
    end

    suite = validate_backward_step_masked_structure_suite( ...
        'runDirs', runDirs, ...
        'labels', labels, ...
        'makePlots', logical(opt.makePlots), ...
        'field', char(opt.field), ...
        'averageLastFraction', opt.averageLastFraction, ...
        'outputDir', outputDir);

    writetable(suite.summary, fullfile(outputDir, 'backward_step_final_liquid_config_summary.csv'));

    if opt.makePlots
        local_plot_final_metrics(suite, outputDir);
    end
end

function runDirs = local_default_run_dirs()
    % Prefer the already-computed hard-wall calibration baseline. If the user
    % deliberately reruns the baseline with the final script, they can pass
    % runDirs explicitly.
    runDirs = { ...
        '../runs/backward_step_hardwall_q9_s0p50_b0p00100_k4_96x48', ...
        '../runs/backward_step_final_q9_k4_virial_96x48'};
end

function labels = local_default_labels(runDirs)
    labels = cell(size(runDirs));
    for i = 1:numel(runDirs)
        rd = char(runDirs{i});
        if contains(rd, 'virial')
            labels{i} = 'Q9 k=4 + virial';
        elseif contains(rd, 'q9') && contains(rd, 'k4')
            labels{i} = 'Q9 k=4';
        else
            [~, name] = fileparts(rd);
            labels{i} = name;
        end
    end
end

function local_plot_final_metrics(suite, outputDir)
    tbl = suite.summary;
    if isempty(tbl)
        return;
    end

    labels = suite.labels(:);
    x = 1:height(tbl);

    fig = figure('Name', 'Backward step final liquid config: reliability and structure');
    tiledlayout(2, 4, 'TileSpacing', 'compact', 'Padding', 'compact');

    local_bar_tile(x, tbl, labels, 'populationP05ReversedOverReference', 'P05(N) rev/ref', 'Recirc. low-tail');
    local_bar_tile(x, tbl, labels, 'populationBelow5FractionReversed', 'fraction', 'N<5 in recirc.');
    local_bar_tile(x, tbl, labels, 'populationTemporalCvMeanReversed', 'CV', 'Recirc. temporal CV(N)');
    local_bar_tile(x, tbl, labels, 'stdNLate', 'std(N)', 'Global population std');
    local_bar_tile(x, tbl, labels, 'omegaMeanLowKFractionDownstream', 'fraction', 'Mean omega low-k');
    local_bar_tile(x, tbl, labels, 'reversedLargestComponentFraction', 'fraction', 'Largest reversed comp.');
    local_bar_tile(x, tbl, labels, 'reversedComponentCount', 'count', 'Reversed components');
    local_bar_tile(x, tbl, labels, 'omegaTotalRmsDownstream', 'RMS', 'Total omega RMS');

    saveas(fig, fullfile(outputDir, 'backward_step_final_liquid_config_reliability_structure.png'));

    fig2 = figure('Name', 'Backward step final liquid config: projection and virial safety');
    tiledlayout(2, 4, 'TileSpacing', 'compact', 'Padding', 'compact');

    local_bar_tile(x, tbl, labels, 'q6ImmersedSolidLeakProjectedFluxRmsLate', 'RMS', 'Q6 solid leak');
    local_bar_tile(x, tbl, labels, 'q9ImmersedSolidLeakMassFluxRmsLate', 'RMS', 'Q9 solid leak');
    local_bar_tile(x, tbl, labels, 'q6DivAfterProjectedFluxRmsLate', 'RMS', 'Q6 div after');
    local_bar_tile(x, tbl, labels, 'q9DensityStdRatioEstimateLate', 'ratio', 'Q9 density std ratio');
    local_bar_tile(x, tbl, labels, 'virialRhoDefectRelRmsLate', 'RMS', 'Virial rho defect');
    local_bar_tile(x, tbl, labels, 'virialDuOverThermalRmsLate', 'ratio', 'Virial du/u_th');
    local_bar_tile(x, tbl, labels, 'virialDuAppliedMaxAbsLate', 'velocity', 'Virial du max');
    local_bar_tile(x, tbl, labels, 'gradPdriveRmsLate', 'RMS', 'grad Pdrive');

    saveas(fig2, fullfile(outputDir, 'backward_step_final_liquid_config_projection_virial.png'));
end

function local_bar_tile(x, tbl, labels, metricName, ylab, ttl)
    nexttile;
    if ismember(metricName, tbl.Properties.VariableNames)
        bar(x, tbl.(metricName));
    else
        bar(x, nan(size(x)));
        text(mean(x), 0.5, sprintf('missing: %s', metricName), ...
            'HorizontalAlignment', 'center', 'Interpreter', 'none');
    end
    title(ttl, 'Interpreter', 'none');
    ylabel(ylab, 'Interpreter', 'none');
    set(gca, 'XTick', x, 'XTickLabel', labels, 'XTickLabelRotation', 25);
    grid on;
end
