function suite = validate_backward_step_hardwall_calibration_suite(varargin)
%VALIDATE_BACKWARD_STEP_HARDWALL_CALIBRATION_SUITE Analyze the hard-wall calibration subset.
%
% This wrapper expects the run directories generated by:
%   scripts/run_backward_step_hardwall_calibration_suite.sh
%
% It reuses the backward-step masked-structure analyzer, including the
% coherence and population-reliability diagnostics. The purpose is to
% re-evaluate the best Q6/Q9 candidates after the immersed-solid hard-wall
% projection fix: q6ProjectionStrength may under-relax interior projection,
% but the immersed solid must remain impermeable.
%
% Example from repository root:
%   cd matlab
%   suite = validate_backward_step_hardwall_calibration_suite();

    p = inputParser;
    addParameter(p, 'runDirs', local_default_run_dirs(), @(x) iscell(x) || isstring(x));
    addParameter(p, 'labels', {}, @(x) iscell(x) || isstring(x));
    addParameter(p, 'makePlots', true, @(x) islogical(x) || isnumeric(x));
    addParameter(p, 'field', 'omega', @(s) ischar(s) || isstring(s));
    addParameter(p, 'averageLastFraction', 0.50, @(x) isnumeric(x) && isscalar(x) && x > 0 && x <= 1);
    addParameter(p, 'outputDir', '../runs/backward_step_hardwall_calibration_analysis', @(s) ischar(s) || isstring(s));
    parse(p, varargin{:});
    opt = p.Results;

    runDirs = cellstr(opt.runDirs);
    existing = false(size(runDirs));
    for i = 1:numel(runDirs)
        existing(i) = exist(runDirs{i}, 'dir') == 7;
    end
    if ~any(existing)
        error('validate_backward_step_hardwall_calibration_suite:missingRuns', ...
            'No default hard-wall calibration run directories were found. Run scripts/run_backward_step_hardwall_calibration_suite.sh first, or pass runDirs explicitly.');
    end
    if ~all(existing)
        missing = runDirs(~existing);
        fprintf('[hardwall-calibration] skipping %d missing default run(s):\n', numel(missing));
        for i = 1:numel(missing)
            fprintf('  %s\n', missing{i});
        end
    end
    runDirs = runDirs(existing);

    labels = cellstr(opt.labels);
    if isempty(labels)
        labels = local_default_labels(runDirs);
    else
        labels = labels(existing);
    end

    suite = validate_backward_step_masked_structure_suite( ...
        'runDirs', runDirs, ...
        'labels', labels, ...
        'makePlots', opt.makePlots, ...
        'field', char(opt.field), ...
        'averageLastFraction', opt.averageLastFraction, ...
        'outputDir', char(opt.outputDir));

    if ~exist(char(opt.outputDir), 'dir')
        mkdir(char(opt.outputDir));
    end
    writetable(suite.summary, fullfile(char(opt.outputDir), 'backward_step_hardwall_calibration_summary.csv'));

    if opt.makePlots
        local_plot_hardwall_metrics(suite, char(opt.outputDir));
    end
end

function runDirs = local_default_run_dirs()
    runDirs = { ...
        '../runs/backward_step_hardwall_q6_s0p50_96x48', ...
        '../runs/backward_step_hardwall_q6_s1p00_96x48', ...
        '../runs/backward_step_hardwall_q9_s0p50_b0p00100_k2_96x48', ...
        '../runs/backward_step_hardwall_q9_s0p50_b0p00100_k4_96x48'};
end

function labels = local_default_labels(runDirs)
    labels = cell(size(runDirs));
    for i = 1:numel(runDirs)
        rd = char(runDirs{i});
        if contains(rd, 'q6_s0p50')
            labels{i} = 'Q6 hard-wall s=0.50';
        elseif contains(rd, 'q6_s1p00')
            labels{i} = 'Q6 hard-wall s=1.00';
        elseif contains(rd, 'q9_s0p50_b0p00100_k2')
            labels{i} = 'Q9 hard-wall s=0.50 beta=1e-3 k=2';
        elseif contains(rd, 'q9_s0p50_b0p00100_k4')
            labels{i} = 'Q9 hard-wall s=0.50 beta=1e-3 k=4';
        else
            [~, name] = fileparts(rd);
            labels{i} = name;
        end
    end
end

function local_plot_hardwall_metrics(suite, outputDir)
    tbl = suite.summary;
    if isempty(tbl)
        return;
    end

    labels = suite.labels(:);
    x = 1:height(tbl);

    fig = figure('Name', 'Backward step hard-wall calibration: key metrics');
    tiledlayout(2, 3, 'TileSpacing', 'compact', 'Padding', 'compact');

    nexttile;
    local_bar_metric(x, tbl, 'q6ImmersedSolidLeakProjectedFluxRmsLate');
    title('Q6 solid leak RMS'); ylabel('leak');

    nexttile;
    local_bar_metric(x, tbl, 'q9ImmersedSolidLeakMassFluxRmsLate');
    title('Q9 solid leak RMS'); ylabel('leak');

    nexttile;
    local_bar_metric(x, tbl, 'populationP05ReversedOverReference');
    title('Recirculation P05(N)/ref'); ylabel('ratio');

    nexttile;
    local_bar_metric(x, tbl, 'populationTemporalCvMeanReversed');
    title('Recirculation temporal CV(N)'); ylabel('CV');

    nexttile;
    local_bar_metric(x, tbl, 'omegaMeanLowKFractionDownstream');
    title('Mean-vorticity low-k fraction'); ylabel('fraction');

    nexttile;
    local_bar_metric(x, tbl, 'reversedLargestComponentFraction');
    title('Largest reversed component'); ylabel('fraction');

    for ax = findall(fig, 'Type', 'axes')'
        ax.XTick = x;
        ax.XTickLabel = labels;
        ax.XTickLabelRotation = 30;
        grid(ax, 'on');
    end

    saveas(fig, fullfile(outputDir, 'backward_step_hardwall_calibration_key_metrics.png'));

    fig2 = figure('Name', 'Backward step hard-wall calibration: correction amplitudes');
    tiledlayout(2, 2, 'TileSpacing', 'compact', 'Padding', 'compact');

    nexttile;
    local_bar_metric(x, tbl, 'q6DivAfterProjectedFluxRmsLate');
    title('Q6 residual after applied correction'); ylabel('RMS');

    nexttile;
    local_bar_metric(x, tbl, 'q6CorrectionVelocityRmsLate');
    title('Q6 correction velocity RMS'); ylabel('velocity');

    nexttile;
    local_bar_metric(x, tbl, 'q9DensityStdRatioEstimateLate');
    title('Q9 density std ratio estimate'); ylabel('ratio');

    nexttile;
    local_bar_metric(x, tbl, 'q9CorrectionVelocityRmsLate');
    title('Q9 correction velocity RMS'); ylabel('velocity');

    for ax = findall(fig2, 'Type', 'axes')'
        ax.XTick = x;
        ax.XTickLabel = labels;
        ax.XTickLabelRotation = 30;
        grid(ax, 'on');
    end

    saveas(fig2, fullfile(outputDir, 'backward_step_hardwall_calibration_projection_metrics.png'));
end

function local_bar_metric(x, tbl, metricName)
    if ismember(metricName, tbl.Properties.VariableNames)
        bar(x, tbl.(metricName));
    else
        bar(x, nan(size(x)));
        text(mean(x), 0.5, sprintf('missing: %s', metricName), 'HorizontalAlignment', 'center', 'Interpreter', 'none');
    end
end
