#!/usr/bin/env bash
set -euo pipefail

ROOT="${ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
cd "$ROOT"

# 0493x13zf -- shared run_ok profile for the qualitative dripping demo.
#
# Geometry/inlet/forcing are kept from the retained x10o dripping runner.
# The microscopic free-surface closure is promoted to the qualified tagged
# production chain:
#   x10o + CIC + Q2 + x10p/x10q + x10u + x10v full-vector swap + x12a.
#
# This remains a qualitative capability/demonstration case.  It is intended
# to show pendant-drop growth, necking, pinch-off, falling drop, wall impact,
# puddle formation and subsequent liquid-liquid impact; it is NOT a calibrated
# dripping-faucet benchmark or a critical-Weber measurement.

BASE_RUNNER="$ROOT/scripts/run_0493x10o_q6_thermal_interface_dripping.sh"
[[ -f "$BASE_RUNNER" ]] || {
  echo "[0493x13zf-run-ok] ERROR missing $BASE_RUNNER" >&2
  exit 2
}

CASE_NAME="${RUN_OK_SURFACE_CASE:-dripping}"
[[ "$CASE_NAME" == dripping ]] || {
  echo "[0493x13zf-run-ok] ERROR RUN_OK_SURFACE_CASE=$CASE_NAME" >&2
  exit 2
}

RUN_MODE="${RUN_MODE:-src-q6-g-f}"
[[ "$RUN_MODE" == "src-q6-g-f" ]] || {
  echo "[0493x13zf-run-ok] ERROR RUN_MODE=$RUN_MODE; dripping is locked to src-q6-g-f" >&2
  exit 2
}
export RUN_MODE

# ---------------------------------------------------------------------------
# USER EDIT ZONE -- same front-door conventions as the run_ok collection.
# Defaults preserve the historical x10o dripping geometry/forcing point.
# ---------------------------------------------------------------------------
Lx="${Lx:-1.0}"; Ly="${Ly:-1.5}"
NX="${NX:-200}"; NY="${NY:-300}"
GAMMA="${GAMMA:-20}"
DT="${DT:-0.002}"
KBT="${KBT:-0.125}"
LIQUID_MASS="${LIQUID_MASS:-1.0}"
GAS_MASS="${GAS_MASS:-1.0}"
LIQUID_TYPE="${LIQUID_TYPE:-1}"
GAS_TYPE="${GAS_TYPE:-2}"

SIGMA_ACTIVE="${SIGMA_ACTIVE:-2500.0}"
SURFACE_TENSION_MIN_RADIUS_CELLS="${SURFACE_TENSION_MIN_RADIUS_CELLS:-4}"
GRAVITY_Y="${GRAVITY_Y:--0.1}"
UIN="${UIN:-0.1}"
INLET_WIDTH_CELLS="${INLET_WIDTH_CELLS:-6}"
INLET_CENTER_X="${INLET_CENTER_X:-0.5}"
INLET_RESERVOIR_CELLS="${INLET_RESERVOIR_CELLS:-2}"
CONTACT_ANGLE_DEG="${CONTACT_ANGLE_DEG:-90.0}"
KINETIC_REFLECTION_FRACTION="${KINETIC_REFLECTION_FRACTION:-1.0}"
EVAPORATION_TARGET_TYPE="${EVAPORATION_TARGET_TYPE:--1}"
VACUUM_BACKGROUND="${VACUUM_BACKGROUND:-1}"
CASES="${CASES:-capillary}"
SEED="${SEED:-493940}"

STEPS="${STEPS:-50000}"
SUMMARY_EVERY="${SUMMARY_EVERY:-100}"
DUMP_STATE_EVERY="${DUMP_STATE_EVERY:-1000}"
CLEAN_RUN_ROOT="${CLEAN_RUN_ROOT:-1}"
THREADS="${THREADS:-8}"

BIN="${BIN:-${SRC_MPCD_DEFAULT_BIN_0434:-build/src_mpcd_base_cuda_q6_resident_livevis_0486}}"
LIVE_PROGRESS="${LIVE_PROGRESS:-1}"
PREFLIGHT_ONLY="${PREFLIGHT_ONLY:-0}"
PARTICLE_TYPE_FILTER="${PARTICLE_TYPE_FILTER:-$LIQUID_TYPE}"

BASE_RUN_ROOT="${BASE_RUN_ROOT:-runs/0434_dripping_${NX}x${NY}_g${GAMMA}_s${SIGMA_ACTIVE}_u${UIN}}"
RUN_ROOT="${RUN_ROOT:-$BASE_RUN_ROOT/$RUN_MODE}"

# LiveVis / recording conventions shared with the demonstration collection.
LIVE_VIS_ENABLE="${LIVE_VIS_ENABLE:-1}"
LIVE_VIS_HOLD_ON_EXIT="${LIVE_VIS_HOLD_ON_EXIT:-1}"
LIVE_VIS_FIELD="${LIVE_VIS_FIELD:-mass}"
LIVE_VIS_EVERY="${LIVE_VIS_EVERY:-1}"
LIVE_VIS_COLORMAP="${LIVE_VIS_COLORMAP:-blue_red}"
LIVE_VIS_CLIP="${LIVE_VIS_CLIP:--1}"
OVERWRITE_LIVEVIS_CONTROL="${OVERWRITE_LIVEVIS_CONTROL:-1}"

FILTERED_RECORDING_ENABLE="${FILTERED_RECORDING_ENABLE:-1}"
LIVE_VIS_RECORD_ENABLE="${LIVE_VIS_RECORD_ENABLE:-1}"
LIVE_VIS_RECORD_EVERY="${LIVE_VIS_RECORD_EVERY:-100}"
LIVE_VIS_RECORD_FIELDS="${LIVE_VIS_RECORD_FIELDS:-mass}"
FILTER_SAMPLE_EVERY="${FILTER_SAMPLE_EVERY:-100}"
RECORD_ENABLE="${RECORD_ENABLE:-true}"
RECORD_EVERY="${RECORD_EVERY:-$LIVE_VIS_RECORD_EVERY}"
RECORD_FIELDS="${RECORD_FIELDS:-$LIVE_VIS_RECORD_FIELDS}"

# Historical x10o dripping fluid: keep its thermodynamic/collision definition.
ROTATION_ANGLE="${ROTATION_ANGLE:-1.5707963267948966}"
RANDOM_ROTATION_SIGN="${RANDOM_ROTATION_SIGN:-true}"
GRID_SHIFT_ENABLE="${GRID_SHIFT_ENABLE:-true}"
THERMOSTAT_ENABLE="${THERMOSTAT_ENABLE:-true}"
THERMOSTAT_MODE="${THERMOSTAT_MODE:-cell_relative_rescale}"
THERMOSTAT_EVERY="${THERMOSTAT_EVERY:-1}"
THERMOSTAT_TARGET_KBT="${THERMOSTAT_TARGET_KBT:-$KBT}"
THERMOSTAT_MIN_PARTICLES="${THERMOSTAT_MIN_PARTICLES:-3}"

# Q6 profile: protect the demonstration from unrelated shell overrides while
# leaving the original dripping generator/segmented-boundary implementation
# untouched.
RUN_OK_DRIPPING_PROJECTION_BACKEND="${RUN_OK_DRIPPING_PROJECTION_BACKEND:-cuda}"
RUN_OK_DRIPPING_PROJECTION_MAX_ITERATIONS="${RUN_OK_DRIPPING_PROJECTION_MAX_ITERATIONS:-2000}"
RUN_OK_DRIPPING_PROJECTION_TOLERANCE="${RUN_OK_DRIPPING_PROJECTION_TOLERANCE:-1e-5}"
RUN_OK_DRIPPING_Q6_STRICT="${RUN_OK_DRIPPING_Q6_STRICT:-1}"
RUN_OK_DRIPPING_Q6_GF_DENSITY_RELAXATION_TIME="${RUN_OK_DRIPPING_Q6_GF_DENSITY_RELAXATION_TIME:-0.25}"
RUN_OK_DRIPPING_Q6_GF_MIN_FILL_FRACTION="${RUN_OK_DRIPPING_Q6_GF_MIN_FILL_FRACTION:-0.10}"

PROJECTION_BACKEND="$RUN_OK_DRIPPING_PROJECTION_BACKEND"
PROJECTION_MAX_ITERATIONS="$RUN_OK_DRIPPING_PROJECTION_MAX_ITERATIONS"
PROJECTION_TOLERANCE="$RUN_OK_DRIPPING_PROJECTION_TOLERANCE"
Q6_STRICT="$RUN_OK_DRIPPING_Q6_STRICT"
Q6_GF_DENSITY_RELAXATION_TIME="$RUN_OK_DRIPPING_Q6_GF_DENSITY_RELAXATION_TIME"
SPECIES_Q6_MIN_FILL_FRACTION="$RUN_OK_DRIPPING_Q6_GF_MIN_FILL_FRACTION"

# Qualified free-surface closure at surf-tension-qualified-x13h-20260831.
# x10q is the structural 7x7 fallback of x10p and has no independent flag.
export MPCD_X10J_SIMPLE_SPECULAR_ABLATION=0
export MPCD_X10K_LOCAL_FRAME_SPECULAR_ABLATION=0
export MPCD_X10M_MOVING_INTERFACE_WALL=0
export MPCD_X10N_Q6_CONTINUOUS_INTERFACE_WALL=0
export MPCD_X10O_Q6_THERMAL_INTERFACE_WALL=1
export MPCD_X10O_THERMAL_PARTICLE_MASS="$LIQUID_MASS"
export MPCD_X10O_THERMAL_SIGMAS="${RUN_OK_DRIPPING_X10O_THERMAL_SIGMAS:-3.0}"
export MPCD_X10O_THERMAL_MAX_CELLS="${RUN_OK_DRIPPING_X10O_THERMAL_MAX_CELLS:-0.75}"
export MPCD_X10_KINETIC_INTERFACE_CIC=1
export MPCD_X10_KINETIC_INTERFACE_QUADRATIC=1
export MPCD_X10P_INITIAL_OVERLAP_RESOLUTION=1
export MPCD_X10_KINETIC_INTERFACE_ONE_FOR_ONE=1
export MPCD_X10_KINETIC_INTERFACE_ONE_FOR_ONE_SWAP=1
export MPCD_X10_KINETIC_INTERFACE_ONE_FOR_ONE_NORMAL_ONLY=0
export MPCD_X10R_Q6_THERMAL_FULL_VECTOR_ENDPOINT_VELOCITY=0
export MPCD_X10S_Q6_THERMAL_SEGMENT_NORMAL_KINEMATICS=0
export MPCD_X10T_Q6_THERMAL_RIGID_TANGENTIAL_KINEMATICS=0
export MPCD_X10_KINETIC_INTERFACE_THERMAL_PHASE_LIMITER=0
export MPCD_X12A_LOCAL_THERMAL_COOLING=1
export MPCD_X12A_LOCAL_THERMAL_RADIUS_CELLS="${RUN_OK_DRIPPING_X12A_RADIUS_CELLS:-25.298221281347036}"

# No resampling/refill/virial correction in this demonstration.
SPECIES_RESAMPLING_ENABLE=false
LIQUID_RESAMPLING_ENABLE=false
GAS_RESAMPLING_ENABLE=false
VIRIAL_DENSITY_KICK_ENABLE=false
WEIGHTED_RESAMPLING_ENABLE_OVERRIDE=false
CUDA_EMPTY_REFILL_ENABLE_OVERRIDE=false

export Lx Ly NX NY GAMMA DT KBT LIQUID_MASS GAS_MASS LIQUID_TYPE GAS_TYPE
export SIGMA_ACTIVE SURFACE_TENSION_MIN_RADIUS_CELLS GRAVITY_Y UIN INLET_WIDTH_CELLS INLET_CENTER_X INLET_RESERVOIR_CELLS
export CONTACT_ANGLE_DEG KINETIC_REFLECTION_FRACTION EVAPORATION_TARGET_TYPE VACUUM_BACKGROUND CASES SEED
export STEPS SUMMARY_EVERY DUMP_STATE_EVERY CLEAN_RUN_ROOT THREADS BIN LIVE_PROGRESS PREFLIGHT_ONLY PARTICLE_TYPE_FILTER
export BASE_RUN_ROOT RUN_ROOT
export LIVE_VIS_ENABLE LIVE_VIS_HOLD_ON_EXIT LIVE_VIS_FIELD LIVE_VIS_EVERY LIVE_VIS_COLORMAP LIVE_VIS_CLIP OVERWRITE_LIVEVIS_CONTROL
export FILTERED_RECORDING_ENABLE LIVE_VIS_RECORD_ENABLE LIVE_VIS_RECORD_EVERY LIVE_VIS_RECORD_FIELDS FILTER_SAMPLE_EVERY
export RECORD_ENABLE RECORD_EVERY RECORD_FIELDS
export ROTATION_ANGLE RANDOM_ROTATION_SIGN GRID_SHIFT_ENABLE THERMOSTAT_ENABLE THERMOSTAT_MODE THERMOSTAT_EVERY THERMOSTAT_TARGET_KBT THERMOSTAT_MIN_PARTICLES
export PROJECTION_BACKEND PROJECTION_MAX_ITERATIONS PROJECTION_TOLERANCE Q6_STRICT Q6_GF_DENSITY_RELAXATION_TIME SPECIES_Q6_MIN_FILL_FRACTION
export SPECIES_RESAMPLING_ENABLE LIQUID_RESAMPLING_ENABLE GAS_RESAMPLING_ENABLE VIRIAL_DENSITY_KICK_ENABLE WEIGHTED_RESAMPLING_ENABLE_OVERRIDE CUDA_EMPTY_REFILL_ENABLE_OVERRIDE

printf '%s\n' \
  "===== RUN_OK DRIPPING / QUALIFIED FREE-SURFACE CHAIN =====" \
  "[0493x13zf-run-ok] path=$RUN_MODE root=$RUN_ROOT" \
  "[0493x13zf-run-ok] base=$(basename "$BASE_RUNNER") profile=surf-tension-qualified-x13h-20260831" \
  "[0493x13zf-run-ok] chain=x10o+CIC+Q2+x10p/q+x10u+x10v-full-vector+x12a" \
  "[0493x13zf-run-ok] grid=${NX}x${NY} gamma=$GAMMA dt=$DT kBT=$KBT sigma=$SIGMA_ACTIVE rmin/h=$SURFACE_TENSION_MIN_RADIUS_CELLS" \
  "[0493x13zf-run-ok] inlet width/h=$INLET_WIDTH_CELLS Uin=$UIN gravityY=$GRAVITY_Y steps=$STEPS" \
  "[0493x13zf-run-ok] outputs dumpEvery=$DUMP_STATE_EVERY recordEvery=$LIVE_VIS_RECORD_EVERY recordFields=$LIVE_VIS_RECORD_FIELDS liveEvery=$LIVE_VIS_EVERY" \
  "[0493x13zf-run-ok] scope=qualitative pendant-drop/necking/pinch-off/fall/impact/puddle demonstration; not a calibrated dripping benchmark"

bash "$BASE_RUNNER"

# The x10o runner writes its environment snapshot inside the capillary case.
ENV_FILE="$RUN_ROOT/capillary/logs/environment_0493x9q.env"
if [[ -f "$ENV_FILE" ]]; then
  cat >> "$ENV_FILE" <<META_0493X13ZF
RUN_OK_DRIPPING_PROFILE=0493x13zf_7655b81_x10o_x10uv_x12a
RUN_OK_SURFACE_CASE=dripping
RUN_OK_DRIPPING_CHAIN=x10o+CIC+Q2+x10p/q+x10u+x10v-full-vector+x12a
RUN_OK_DRIPPING_SIGMA=${SIGMA_ACTIVE}
RUN_OK_DRIPPING_MIN_RADIUS_CELLS=${SURFACE_TENSION_MIN_RADIUS_CELLS}
RUN_OK_DRIPPING_X12A_RADIUS_CELLS=${MPCD_X12A_LOCAL_THERMAL_RADIUS_CELLS}
RUN_OK_DRIPPING_NORMAL_ONLY=${MPCD_X10_KINETIC_INTERFACE_ONE_FOR_ONE_NORMAL_ONLY}
RUN_OK_DRIPPING_REFERENCE_TAG=surf-tension-qualified-x13h-20260831
META_0493X13ZF
fi

echo "[0493x13zf-run-ok] COMPLETE run=$RUN_ROOT"
