#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
0493x24ak — Li-style framewise cavity-shape analysis for oscillating cavities.

Purpose
-------
The previous article figure reconstructed the Li et al. coordinates from time-
averaged cavity depth and width:

    X(old) = sqrt[(4/pi) Fr' / (mean(h/D))^3]
    Y(old) = mean(d/D) / mean(h/D)

For oscillating cavities this is not strictly equivalent to averaging the
instantaneous Li coordinates because X depends nonlinearly on h and Y is a ratio.

This analyzer therefore computes, for every retained frame:

    X_k = sqrt[(4/pi) Fr' / (h_k/D)^3]
    Y_k = (d_k/D) / (h_k/D)

then reports:

    Xbar = mean(X_k)
    Ybar = mean(Y_k)

The article figure plots only (Xbar,Ybar) without uncertainty whiskers, while
the temporal standard deviations are retained in the CSV/report.

Theoretical reference lines:
    parabola : d/h = sqrt(16/pi) X
    ellipse  : d/h = sqrt(12/pi) X

Expected input
--------------
frame_interface_history.csv generated by
analyze_0493x24ae_article_interface_validation.py

Required columns:
    targetFr
    time
    includeForArticle
    hOverD_initialRef
    mouthWidthOverD

Optional:
    runRoot

Usage
-----
From the repository root:

python3 scripts/analyze_0493x24ak_li_framewise_shape.py \
  --history analysis/0493x24ae_article_interface_extended/frame_interface_history.csv \
  --out analysis/0493x24ak_li_framewise_shape

Article scope
-------------
By default only Fr' <= 1.17 is included. Fr'=3 can be examined separately with
--max-fr 3.0 but should not be mixed into the quantitative Sato/Li comparison.

No pandas.
"""

from __future__ import annotations

import argparse
import csv
import math
from collections import defaultdict
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt


A_PARABOLA = math.sqrt(16.0 / math.pi)
A_ELLIPSE = math.sqrt(12.0 / math.pi)


def ffloat(x, default=math.nan):
    try:
        y = float(x)
        return y if math.isfinite(y) else default
    except Exception:
        return default


def fint(x, default=0):
    try:
        return int(float(x))
    except Exception:
        return default


def read_csv(path: Path):
    if not path.exists():
        raise SystemExit(f"[x24ak] ERROR missing input: {path}")
    if path.stat().st_size == 0:
        raise SystemExit(f"[x24ak] ERROR empty input: {path}")
    with path.open("r", newline="") as h:
        rows = list(csv.DictReader(h))
    if not rows:
        raise SystemExit(f"[x24ak] ERROR no data rows in: {path}")
    return rows


def require_columns(rows, cols, path):
    got = set(rows[0].keys())
    missing = [c for c in cols if c not in got]
    if missing:
        raise SystemExit(
            f"[x24ak] ERROR {path} missing columns: {', '.join(missing)}"
        )


def mean_std(vals):
    a = np.asarray([v for v in vals if math.isfinite(v)], float)
    if len(a) == 0:
        return math.nan, math.nan, 0
    return (
        float(np.mean(a)),
        float(np.std(a, ddof=1)) if len(a) > 1 else 0.0,
        int(len(a)),
    )


def fit_origin(x, y):
    x = np.asarray(x, float)
    y = np.asarray(y, float)
    mask = np.isfinite(x) & np.isfinite(y)
    x = x[mask]
    y = y[mask]
    if len(x) < 2 or np.dot(x, x) <= 0.0:
        return math.nan, math.nan
    slope = float(np.dot(x, y) / np.dot(x, x))
    pred = slope * x
    ssr = float(np.sum((y - pred) ** 2))
    sst = float(np.sum((y - np.mean(y)) ** 2))
    r2 = 1.0 - ssr / sst if sst > 0 else math.nan
    return slope, r2


def publication_style():
    plt.rcParams.update({
        "font.family": "DejaVu Sans",
        "font.size": 10,
        "axes.labelsize": 11,
        "legend.fontsize": 9,
        "xtick.labelsize": 10,
        "ytick.labelsize": 10,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "lines.linewidth": 1.7,
        "lines.markersize": 6.0,
    })


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--history",
        default="analysis/0493x24ae_article_interface_extended/frame_interface_history.csv",
        help="x24ae frame_interface_history.csv",
    )
    ap.add_argument(
        "--out",
        default="analysis/0493x24ak_li_framewise_shape",
        help="output directory",
    )
    ap.add_argument(
        "--max-fr",
        type=float,
        default=1.17,
        help="maximum Fr' included in the quantitative plot",
    )
    ap.add_argument(
        "--min-h-over-D",
        type=float,
        default=0.05,
        help="reject pathological frames with h/D below this value",
    )
    ap.add_argument(
        "--min-mouth-width-over-D",
        type=float,
        default=0.05,
        help="reject frames with undefined/negligible mouth width",
    )
    ap.add_argument(
        "--annotate-fr",
        action="store_true",
        default=True,
        help="annotate points with Fr' values (default: on)",
    )
    ap.add_argument(
        "--no-annotate-fr",
        action="store_false",
        dest="annotate_fr",
        help="disable Fr' point labels",
    )
    args = ap.parse_args()

    history_path = Path(args.history)
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    rows = read_csv(history_path)
    require_columns(
        rows,
        [
            "targetFr",
            "time",
            "includeForArticle",
            "hOverD_initialRef",
            "mouthWidthOverD",
        ],
        history_path,
    )

    # Framewise calculation.
    frame_rows = []
    rejected = defaultdict(int)

    for r in rows:
        fr = ffloat(r.get("targetFr"))
        t = ffloat(r.get("time"))
        include = fint(r.get("includeForArticle"))
        hD = ffloat(r.get("hOverD_initialRef"))
        dD = ffloat(r.get("mouthWidthOverD"))

        if not math.isfinite(fr) or fr > args.max_fr + 1e-12:
            continue
        if include != 1:
            rejected[(fr, "transient")] += 1
            continue
        if not math.isfinite(hD) or hD < args.min_h_over_D:
            rejected[(fr, "bad_h")] += 1
            continue
        if not math.isfinite(dD) or dD < args.min_mouth_width_over_D:
            rejected[(fr, "bad_d")] += 1
            continue

        X = math.sqrt((4.0 / math.pi) * fr / (hD ** 3))
        Y = dD / hD

        if not (math.isfinite(X) and math.isfinite(Y)):
            rejected[(fr, "nonfinite_XY")] += 1
            continue

        frame_rows.append({
            "targetFr": fr,
            "time": t,
            "hOverD": hD,
            "mouthWidthOverD": dD,
            "X": X,
            "Y_dOverh": Y,
            "runRoot": r.get("runRoot", ""),
        })

    if not frame_rows:
        raise SystemExit("[x24ak] ERROR no valid article frames after filtering")

    frame_rows.sort(key=lambda r: (r["targetFr"], r["time"]))

    frame_csv = out / "li_framewise_history.csv"
    with frame_csv.open("w", newline="") as h:
        fields = list(frame_rows[0].keys())
        w = csv.DictWriter(h, fieldnames=fields)
        w.writeheader()
        w.writerows(frame_rows)

    groups = defaultdict(list)
    for r in frame_rows:
        groups[round(r["targetFr"], 9)].append(r)

    summary = []

    for frkey in sorted(groups):
        rr = groups[frkey]
        fr = float(np.mean([r["targetFr"] for r in rr]))

        Xmean, Xstd, n = mean_std([r["X"] for r in rr])
        Ymean, Ystd, _ = mean_std([r["Y_dOverh"] for r in rr])

        hmean, hstd, _ = mean_std([r["hOverD"] for r in rr])
        dmean, dstd, _ = mean_std([r["mouthWidthOverD"] for r in rr])

        # Old aggregate-of-means formulation for comparison/audit.
        X_old = (
            math.sqrt((4.0 / math.pi) * fr / (hmean ** 3))
            if math.isfinite(hmean) and hmean > 0
            else math.nan
        )
        Y_old = dmean / hmean if math.isfinite(hmean) and hmean > 0 else math.nan

        para = A_PARABOLA * Xmean
        ell = A_ELLIPSE * Xmean

        summary.append({
            "targetFr": fr,
            "frames": n,
            "timeStart": min(r["time"] for r in rr),
            "timeEnd": max(r["time"] for r in rr),

            "meanHOverD": hmean,
            "stdHOverD": hstd,
            "meanMouthWidthOverD": dmean,
            "stdMouthWidthOverD": dstd,

            "meanFramewiseX": Xmean,
            "stdFramewiseX": Xstd,
            "meanFramewiseY_dOverh": Ymean,
            "stdFramewiseY_dOverh": Ystd,

            "aggregateMeansX_old": X_old,
            "aggregateMeansY_old": Y_old,

            "deltaX_framewise_minus_old": Xmean - X_old,
            "relativeDeltaX": (
                (Xmean - X_old) / X_old
                if math.isfinite(X_old) and X_old != 0
                else math.nan
            ),
            "deltaY_framewise_minus_old": Ymean - Y_old,
            "relativeDeltaY": (
                (Ymean - Y_old) / Y_old
                if math.isfinite(Y_old) and Y_old != 0
                else math.nan
            ),

            "parabolaPredictionAtMeanX": para,
            "ellipsePredictionAtMeanX": ell,
            "YoverParabola": Ymean / para if para > 0 else math.nan,
            "YoverEllipse": Ymean / ell if ell > 0 else math.nan,
        })

    summary_csv = out / "li_framewise_summary.csv"
    with summary_csv.open("w", newline="") as h:
        fields = list(summary[0].keys())
        w = csv.DictWriter(h, fieldnames=fields)
        w.writeheader()
        w.writerows(summary)

    xs = np.array([r["meanFramewiseX"] for r in summary])
    ys = np.array([r["meanFramewiseY_dOverh"] for r in summary])
    frs = np.array([r["targetFr"] for r in summary])

    slope, r2 = fit_origin(xs, ys)

    publication_style()

    xmax = 1.12 * float(np.nanmax(xs))
    xx = np.linspace(0.0, xmax, 300)

    # Article figure: intentionally no whiskers.
    fig, ax = plt.subplots(figsize=(6.5, 5.0))
    ax.plot(
        xx, A_PARABOLA * xx, "--",
        label=rf"Parabola: $d/h=\sqrt{{16/\pi}}\,X$"
    )
    ax.plot(
        xx, A_ELLIPSE * xx, "-.",
        label=rf"Ellipse: $d/h=\sqrt{{12/\pi}}\,X$"
    )
    ax.plot(
        xx, slope * xx, ":",
        label=f"SRC fit: d/h = {slope:.3f} X"
    )
    ax.plot(xs, ys, "o", label="SRC/MPCD points")

    if args.annotate_fr:
        for x, y, fr in zip(xs, ys, frs):
            ax.annotate(
                f"{fr:g}",
                (x, y),
                xytext=(4, 4),
                textcoords="offset points",
                fontsize=8,
            )

    ax.set_xlabel(r"$X=\left(M/(\rho_l g h^3)\right)^{1/2}$")
    ax.set_ylabel(r"Cavity aspect ratio $d/h$")
    ax.set_xlim(left=0.0)
    ax.set_ylim(bottom=0.0)
    ax.grid(True, alpha=0.25)
    ax.legend(loc="best")
    fig.tight_layout()
    fig.savefig(out / "fig_li_framewise_shape_map.pdf", format="pdf", bbox_inches="tight")
    plt.close(fig)

    # Diagnostic comparison: framewise means vs old aggregate-of-means points.
    fig, ax = plt.subplots(figsize=(6.5, 5.0))
    ax.plot(xx, A_PARABOLA * xx, "--", label="Parabola")
    ax.plot(xx, A_ELLIPSE * xx, "-.", label="Ellipse")

    oldx = np.array([r["aggregateMeansX_old"] for r in summary])
    oldy = np.array([r["aggregateMeansY_old"] for r in summary])

    ax.plot(oldx, oldy, "s", label="Old: functions of temporal means")
    ax.plot(xs, ys, "o", label="New: temporal means of framewise X,Y")

    for xo, yo, xn, yn, fr in zip(oldx, oldy, xs, ys, frs):
        ax.plot([xo, xn], [yo, yn], linewidth=0.8, alpha=0.7)
        ax.annotate(
            f"{fr:g}", (xn, yn),
            xytext=(4, 4), textcoords="offset points", fontsize=8
        )

    ax.set_xlabel(r"$X=\left(M/(\rho_l g h^3)\right)^{1/2}$")
    ax.set_ylabel(r"Cavity aspect ratio $d/h$")
    ax.set_xlim(left=0.0)
    ax.set_ylim(bottom=0.0)
    ax.grid(True, alpha=0.25)
    ax.legend(loc="best")
    fig.tight_layout()
    fig.savefig(out / "fig_li_framewise_vs_aggregate_diagnostic.pdf",
                format="pdf", bbox_inches="tight")
    plt.close(fig)

    report = out / "report.txt"
    with report.open("w") as h:
        h.write("0493x24ak — Li framewise shape analysis\n")
        h.write("========================================\n\n")
        h.write(
            "Per retained frame:\n"
            "  X_k = sqrt((4/pi) * Fr' / (h_k/D)^3)\n"
            "  Y_k = (d_k/D)/(h_k/D)\n\n"
            "Article point:\n"
            "  X = mean(X_k)\n"
            "  Y = mean(Y_k)\n\n"
        )
        h.write(
            f"Parabola slope sqrt(16/pi) = {A_PARABOLA:.8f}\n"
            f"Ellipse slope  sqrt(12/pi) = {A_ELLIPSE:.8f}\n"
            f"SRC framewise fit through origin = {slope:.8f}, R2={r2:.8f}\n\n"
        )

        h.write("Case summary\n")
        h.write("------------\n")
        for r in summary:
            h.write(
                f"Fr'={r['targetFr']:.9g}  N={r['frames']}  "
                f"Xbar={r['meanFramewiseX']:.6g} +/- {r['stdFramewiseX']:.4g}  "
                f"Ybar={r['meanFramewiseY_dOverh']:.6g} +/- {r['stdFramewiseY_dOverh']:.4g}  "
                f"oldX={r['aggregateMeansX_old']:.6g}  "
                f"oldY={r['aggregateMeansY_old']:.6g}  "
                f"dX={100*r['relativeDeltaX']:+.2f}%  "
                f"dY={100*r['relativeDeltaY']:+.2f}%  "
                f"Y/parabola={r['YoverParabola']:.4f}\n"
            )

        h.write("\nRejected frames\n")
        h.write("---------------\n")
        if rejected:
            for (fr, reason), count in sorted(rejected.items()):
                h.write(f"Fr'={fr:g} {reason}: {count}\n")
        else:
            h.write("none\n")

    print("[x24ak] input :", history_path)
    print("[x24ak] valid frames:", len(frame_rows))
    print("[x24ak] cases:", len(summary))
    print(f"[x24ak] SRC framewise fit: d/h = {slope:.6f} X, R2={r2:.6f}")
    print("[x24ak] wrote:")
    print(" ", frame_csv)
    print(" ", summary_csv)
    print(" ", out / "fig_li_framewise_shape_map.pdf")
    print(" ", out / "fig_li_framewise_vs_aggregate_diagnostic.pdf")
    print(" ", report)


if __name__ == "__main__":
    main()
