#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

if [[ ! -x build/src_mpcd_base ]]; then
  ./scripts/build_src_mpcd_base.sh
fi

STATE="initial_state_backward_step_96x48_g20.smpcd"
if [[ ! -f "$STATE" ]]; then
  if command -v matlab >/dev/null 2>&1; then
    matlab -batch "cd('matlab'); generate_backward_step_state('output','../${STATE}');"
  else
    echo "Missing ${STATE}. Generate it from MATLAB:" >&2
    echo "  cd matlab" >&2
    echo "  generate_backward_step_state('output','../${STATE}');" >&2
    echo "  cd .." >&2
    exit 1
  fi
fi

RUN_Q6_S050="${RUN_Q6_S050:-1}"
RUN_Q6_S100="${RUN_Q6_S100:-1}"
RUN_Q9_K2="${RUN_Q9_K2:-1}"
RUN_Q9_K4="${RUN_Q9_K4:-1}"
RUN_ANALYSIS="${RUN_ANALYSIS:-0}"

N_STEPS="${N_STEPS:-30000}"
SUMMARY_EVERY="${SUMMARY_EVERY:-100}"
DUMP_STATE_EVERY="${DUMP_STATE_EVERY:-500}"
NUM_THREADS="${NUM_THREADS:-4}"

Q9_BETA="${Q9_BETA:-0.00100}"

CONFIG_DIR="runs/backward_step_hardwall_calibration_configs"
mkdir -p "$CONFIG_DIR"

write_case() {
  local method="$1"
  local out_dir="$2"
  local file="$3"
  local q6_strength="$4"
  local q9_enable="$5"
  local q9_lowk="$6"

  cat > "$file" <<EOF_INNER
# Auto-generated by scripts/run_backward_step_hardwall_calibration_suite.sh.
# Second-stage masked immersed-step calibration after hard-wall projection semantics.
# Periodic-x forced immersed-rectangle step. Not an inlet/outlet benchmark.

inputState = ${STATE}
outputDir = ${out_dir}

Lx = 2.0
Ly = 1.0
Nx = 96
Ny = 48

fluidXMin0 = 0.0
fluidXMax0 = -1.0
fluidYMin0 = 0.0
fluidYMax0 = -1.0

dt = 0.001
nSteps = ${N_STEPS}

rotationAngle = 2.0943951023931953
randomRotationSign = true
gridShiftEnable = true
rngSeed = 12345

bcLeft = periodic
bcRight = periodic
bcBottom = solid
bcTop = solid

bodyAccelerationX = 0.015
bodyAccelerationY = 0.0

projectionEnable = true
projectionOperator = channel_fv_cg
projectionMaxIterations = 700
projectionTolerance = 1.0e-9
projectionMomentumCorrectionEnable = true
q6ProjectionStrength = ${q6_strength}
projectionImmersedSolidMaskEnable = true
projectionImmersedSolidFluidFractionThreshold = 0.5
projectionAllowUnmaskedImmersedSolid = false

q9MassFluxProjectionEnable = ${q9_enable}
q9MassFluxProjectionStrength = 1.0
q9DensityRelaxationBeta = ${Q9_BETA}
q9TargetFilter = elliptic_lowpass
q9LowKMaxIndex = ${q9_lowk}
q9EllipticLowPassPasses = 1
q9MomentumCorrectionEnable = true

virialDiagnosticsEnable = false
virialKickEnable = false

immersedSolidEnable = true
immersedSolidShape = rectangle
immersedSolidXMin = 0.25
immersedSolidXMax = 0.65
immersedSolidYMin = 0.0
immersedSolidYMax = 0.50
immersedSolidFractionSamples = 4
immersedSolidVx = 0.0
immersedSolidVy = 0.0
immersedSolidWallUx = 0.0
immersedSolidWallUy = 0.0
immersedSolidOmega = 0.0

wallAccommodation = 1.0
wallVpGamma = 0.0
wallVpMass = 1.0
wallKBT = -1.0
wallThermalNoise = 1.0

thermostatEnable = true
thermostatMode = cell_relative_rescale
thermostatEvery = 1
thermostatTargetKBT = -1.0
thermostatMinParticles = 3
kBT = 0.0025

summaryEvery = ${SUMMARY_EVERY}
dumpStateEvery = ${DUMP_STATE_EVERY}
numThreads = ${NUM_THREADS}
EOF_INNER
}

run_case() {
  local desc="$1"
  local cfg="$2"
  echo "[backward-step-hardwall-calibration] running ${desc}: ${cfg}"
  ./build/src_mpcd_base "$cfg"
}

if [[ "$RUN_Q6_S050" != "0" ]]; then
  cfg="$CONFIG_DIR/params_backward_step_hardwall_q6_s0p50_96x48.kv"
  out="runs/backward_step_hardwall_q6_s0p50_96x48"
  write_case "q6" "$out" "$cfg" "0.50" "false" "2"
  run_case "Q6 hard-wall s=0.50" "$cfg"
fi

if [[ "$RUN_Q6_S100" != "0" ]]; then
  cfg="$CONFIG_DIR/params_backward_step_hardwall_q6_s1p00_96x48.kv"
  out="runs/backward_step_hardwall_q6_s1p00_96x48"
  write_case "q6" "$out" "$cfg" "1.00" "false" "2"
  run_case "Q6 hard-wall s=1.00" "$cfg"
fi

if [[ "$RUN_Q9_K2" != "0" ]]; then
  cfg="$CONFIG_DIR/params_backward_step_hardwall_q9_s0p50_b0p00100_k2_96x48.kv"
  out="runs/backward_step_hardwall_q9_s0p50_b0p00100_k2_96x48"
  write_case "q9" "$out" "$cfg" "0.50" "true" "2"
  run_case "Q9 hard-wall s=0.50 beta=${Q9_BETA} lowK=2" "$cfg"
fi

if [[ "$RUN_Q9_K4" != "0" ]]; then
  cfg="$CONFIG_DIR/params_backward_step_hardwall_q9_s0p50_b0p00100_k4_96x48.kv"
  out="runs/backward_step_hardwall_q9_s0p50_b0p00100_k4_96x48"
  write_case "q9" "$out" "$cfg" "0.50" "true" "4"
  run_case "Q9 hard-wall s=0.50 beta=${Q9_BETA} lowK=4" "$cfg"
fi

if [[ "$RUN_ANALYSIS" != "0" ]]; then
  if command -v matlab >/dev/null 2>&1; then
    echo "[backward-step-hardwall-calibration] running MATLAB analysis"
    matlab -batch "cd('matlab'); suite = validate_backward_step_hardwall_calibration_suite('makePlots',false);"
  else
    echo "[backward-step-hardwall-calibration] MATLAB not found; analyze later with:" >&2
    echo "  cd matlab" >&2
    echo "  suite = validate_backward_step_hardwall_calibration_suite();" >&2
  fi
fi

echo "[backward-step-hardwall-calibration] done"
