#!/usr/bin/env bash
set -euo pipefail

# 0066 open-boundary backward-facing-step validation.
# Run from repository root.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

EXE="${EXE:-./build/src_mpcd_base}"
STATE="${STATE:-initial_state_backward_step_96x48_g20.smpcd}"
RUN_ROOT="${RUN_ROOT:-runs/backward_step_open_channel_validation_0066}"
CASE_STEPS="${CASE_STEPS:-3000}"
SUMMARY_EVERY="${SUMMARY_EVERY:-100}"
DUMP_STATE_EVERY="${DUMP_STATE_EVERY:-300}"
NUM_THREADS="${NUM_THREADS:-4}"
AUTO_BUILD="${AUTO_BUILD:-1}"
RUN_CLASSIC="${RUN_CLASSIC:-0}"
RUN_Q6="${RUN_Q6:-1}"
RUN_Q9="${RUN_Q9:-1}"
RUN_Q9_VIRIAL="${RUN_Q9_VIRIAL:-1}"
RUN_NO_KEEPMEAN="${RUN_NO_KEEPMEAN:-0}"
RUN_ANALYSIS="${RUN_ANALYSIS:-0}"

INLET_UX="${INLET_UX:-0.05}"
KBT="${KBT:-0.0025}"
Q6_STRENGTH="${Q6_STRENGTH:-0.50}"
Q9_BETA="${Q9_BETA:-0.001}"
Q9_LOWK="${Q9_LOWK:-4}"
VIRIAL_K="${VIRIAL_K:-0.50}"
VIRIAL_BETA="${VIRIAL_BETA:-0.05}"
VIRIAL_OPEN_EXCLUSION_CELLS="${VIRIAL_OPEN_EXCLUSION_CELLS:-3}"

if [[ "$AUTO_BUILD" == "1" ]]; then
  ./scripts/build_src_mpcd_base.sh
fi

if [[ ! -x "$EXE" ]]; then
  echo "ERROR: executable not found or not executable: $EXE" >&2
  echo "Build first, e.g.: ./scripts/build_src_mpcd_base.sh" >&2
  exit 1
fi

if [[ ! -f "$STATE" ]]; then
  if command -v matlab >/dev/null 2>&1; then
    matlab -batch "cd('matlab'); generate_backward_step_state('output','../${STATE}');"
  else
    cat >&2 <<MSG
ERROR: missing ${STATE}
Generate it from MATLAB with:
  cd matlab
  generate_backward_step_state('output','../${STATE}');
  cd ..
MSG
    exit 2
  fi
fi

mkdir -p "$RUN_ROOT/params" "$RUN_ROOT/logs"

write_case() {
  local case_label="$1"
  local method="$2"
  local q9_enable="$3"
  local virial_enable="$4"
  local keep_mean="$5"
  local params="$RUN_ROOT/params/${case_label}.kv"
  local out_dir="$RUN_ROOT/${case_label}"

  cat > "$params" <<EOF_INNER
# Auto-generated by scripts/run_backward_step_open_channel_validation_0066.sh.
# 0066 open-boundary backward-facing-step validation with a static immersed rectangle.

inputState = ${STATE}
outputDir = ${out_dir}

Lx = 2.0
Ly = 1.0
Nx = 96
Ny = 48

fluidXMin0 = 0.0
fluidXMax0 = -1.0
fluidYMin0 = 0.0
fluidYMax0 = -1.0

dt = 0.001
nSteps = ${CASE_STEPS}

rotationAngle = 2.0943951023931953
randomRotationSign = true
gridShiftEnable = true
rngSeed = 12345

bcLeft = inlet
bcRight = outlet
bcBottom = solid
bcTop = solid

bodyAccelerationX = 0.0
bodyAccelerationY = 0.0
keepMeanFlowEnable = ${keep_mean}
targetMeanUx = ${INLET_UX}
targetMeanUy = 0.0

inletUxLeft = ${INLET_UX}
inletUyLeft = 0.0
inletKBT = -1.0
inletThermalNoise = 0.0
inletInjectionMode = cuda_recycle
inletSlabCells = 1.0
inletRandomizeTangential = true
inletReinjectBackflow = true

projectionEnable = true
projectionOperator = elliptic_fv_cg
projectionMaxIterations = 900
projectionTolerance = 1.0e-10
projectionMomentumCorrectionEnable = true
q6ProjectionStrength = ${Q6_STRENGTH}
projectionImmersedSolidMaskEnable = true
projectionImmersedSolidFluidFractionThreshold = 0.5
projectionAllowUnmaskedImmersedSolid = false

q9MassFluxProjectionEnable = ${q9_enable}
q9MassFluxProjectionStrength = 1.00
q9DensityRelaxationBeta = ${Q9_BETA}
q9TargetFilter = elliptic_lowpass
q9LowKMaxIndex = ${Q9_LOWK}
q9EllipticLowPassPasses = 1
q9MomentumCorrectionEnable = true

virialDiagnosticsEnable = ${virial_enable}
virialKickEnable = ${virial_enable}
virialK = ${VIRIAL_K}
virialBeta = ${VIRIAL_BETA}
virialRhoEOSRefMode = current_uniform
virialRhoUniformMode = particle_mean
virialDriveTargetMode = current_uniform
virialRhoKickMode = uniform_now
virialRhoKickMinFraction = 0.10
virialMomentumCorrectionEnable = true
virialOpenBoundaryExclusionCells = ${VIRIAL_OPEN_EXCLUSION_CELLS}

immersedSolidEnable = true
immersedSolidShape = rectangle
immersedSolidXMin = 0.25
immersedSolidXMax = 0.65
immersedSolidYMin = 0.0
immersedSolidYMax = 0.50
immersedSolidFractionSamples = 4
immersedSolidVx = 0.0
immersedSolidVy = 0.0
immersedSolidWallUx = 0.0
immersedSolidWallUy = 0.0
immersedSolidOmega = 0.0

wallAccommodation = 1.0
wallVpGamma = 0.0
wallVpMass = 1.0
wallKBT = -1.0
wallThermalNoise = 1.0
wallUxBottom = 0.0
wallUyBottom = 0.0
wallUxTop = 0.0
wallUyTop = 0.0

thermostatEnable = true
thermostatMode = cell_relative_rescale
thermostatEvery = 1
thermostatTargetKBT = -1.0
thermostatMinParticles = 3
kBT = ${KBT}

summaryEvery = ${SUMMARY_EVERY}
dumpStateEvery = ${DUMP_STATE_EVERY}
numThreads = ${NUM_THREADS}
EOF_INNER

  echo "$params"
}

run_case() {
  local params="$1"
  local case_label
  case_label="$(basename "$params" .kv)"
  local log="$RUN_ROOT/logs/${case_label}.log"
  echo "=== 0066 running ${case_label} ==="
  echo "params: $params"
  "$EXE" "$params" | tee "$log"
}

cases=()
if [[ "$RUN_CLASSIC" != "0" ]]; then
  cases+=("$(write_case backstep_classic_keepmean classic false false true)")
fi
if [[ "$RUN_Q6" != "0" ]]; then
  cases+=("$(write_case backstep_q6_keepmean_s050 q6 false false true)")
fi
if [[ "$RUN_Q9" != "0" ]]; then
  cases+=("$(write_case backstep_q9_keepmean_b0001 q9 true false true)")
fi
if [[ "$RUN_Q9_VIRIAL" != "0" ]]; then
  cases+=("$(write_case backstep_q9_virial_keepmean_K0p50_b0p05_ex3 q9_virial true true true)")
fi
if [[ "$RUN_NO_KEEPMEAN" == "1" ]]; then
  cases+=("$(write_case backstep_q9_virial_nokeep_K0p50_b0p05_ex3 q9_virial true true false)")
fi

for params in "${cases[@]}"; do
  run_case "$params"
done

if [[ "$RUN_ANALYSIS" != "0" ]]; then
  if command -v matlab >/dev/null 2>&1; then
    matlab -batch "cd('matlab'); suite = analyze_backward_step_open_channel_validation_0066('root','..');"
  else
    echo "MATLAB not found; analyze later with:" >&2
    echo "  cd matlab" >&2
    echo "  suite = analyze_backward_step_open_channel_validation_0066('root','..');" >&2
  fi
fi

cat <<MSG

0066 open-boundary backward-step validation completed.
Output root:
  $RUN_ROOT

MATLAB analysis:
  cd matlab
  suite = analyze_backward_step_open_channel_validation_0066('root','..');
  cd ..
MSG
