#!/usr/bin/env bash
set -euo pipefail

# 0423 -- final VK comparison launcher.
# Runs the solid reference and Darcy/Brinkman chi variants sequentially with
# common VK parameters and a shared initial particle state generated by the
# solid script.  Default livevis hold is off so the batch can proceed; set
# LIVE_VIS_HOLD_ON_EXIT=1 to inspect each final frame and close the window to continue.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

truthy_0423() { case "${1:-0}" in 1|true|TRUE|yes|YES|on|ON|enable|enabled) return 0 ;; *) return 1 ;; esac; }

SOLID_SCRIPT=${SOLID_SCRIPT:-scripts/run_portable_von_karman_resampling_0337_livevis_classic.sh}
DARCY_SCRIPT=${DARCY_SCRIPT:-scripts/run_src_classic_cuda_darcy_chi_vonkarman_periodic_0416.sh}

SUITE_TAG=${SUITE_TAG:-vk_final_compare_0423}
SUITE_ROOT=${SUITE_ROOT:-runs/${SUITE_TAG}}
CLEAN_SUITE=${CLEAN_SUITE:-1}
PREBUILD=${PREBUILD:-1}

# Common physics/numerics for all modes.
Lx=${Lx:-1.5}
Ly=${Ly:-0.4}
NX=${NX:-1200}
NY=${NY:-640}
GAMMA=${GAMMA:-6}
STEPS=${STEPS:-3000}
DT=${DT:-0.0005}
KBT=${KBT:-5.0}
SEED=${SEED:-1628505}
THREADS=${THREADS:-12}
SUMMARY_EVERY=${SUMMARY_EVERY:-300}
DUMP_STATE_EVERY=${DUMP_STATE_EVERY:-1000}
U0=${U0:-0.9}
AX=${AX:-0.000005}
AY=${AY:-0.0}
ROTATION_ANGLE=${ROTATION_ANGLE:-1.5}
THERMOSTAT_ENABLE=${THERMOSTAT_ENABLE:-true}

# Geometry.
CIRCLE_XC=${CIRCLE_XC:-0.2}
CIRCLE_YC=${CIRCLE_YC:-0.205}
CIRCLE_RC=${CIRCLE_RC:-0.04}

# Darcy chi and forcing defaults.
CHI_FILE=${CHI_FILE:-${DARCY_CHI_FILE:-./chi/chi_vonkarman_circle_xc0p2_yc0p205_rc0p04_1200x640_f32.f32}}
CHI_FILE_FORMAT=${CHI_FILE_FORMAT:-float32}
ALPHA=${ALPHA:-800000.0}
ALPHA_MIN=${ALPHA_MIN:-0.0}
DARCY_Q=${DARCY_Q:-0.1}
DARCY_INITIAL_DEACTIVATE_BELOW_CHI=${DARCY_INITIAL_DEACTIVATE_BELOW_CHI:-0.05}
WALL_KBT=${WALL_KBT:--1.0}
DARCY_CHI_COLLISION_VP_GAMMA=${DARCY_CHI_COLLISION_VP_GAMMA:--1}
DARCY_CHI_COLLISION_VP_LAYERS=${DARCY_CHI_COLLISION_VP_LAYERS:-1}
DARCY_CHI_COLLISION_VP_STRENGTH=${DARCY_CHI_COLLISION_VP_STRENGTH:-1.0}
DARCY_CHI_COLLISION_VP_THRESHOLD=${DARCY_CHI_COLLISION_VP_THRESHOLD:-0.5}

# Live visualization.  Batch default: no final hold.  Set LIVE_VIS_HOLD_ON_EXIT=1
# to inspect each final frame; close the window/Q/Esc to let the next run start.
LIVE_VIS_ENABLE=${LIVE_VIS_ENABLE:-1}
LIVE_VIS_FIELD=${LIVE_VIS_FIELD:-vorticity}
LIVE_VIS_EVERY=${LIVE_VIS_EVERY:-10}
LIVE_VIS_NX=${LIVE_VIS_NX:-1200}
LIVE_VIS_NY=${LIVE_VIS_NY:-320}
LIVE_VIS_CLIP=${LIVE_VIS_CLIP:--20}
LIVE_VIS_GAIN=${LIVE_VIS_GAIN:-0.5}
LIVE_VIS_SMOOTH_PASSES=${LIVE_VIS_SMOOTH_PASSES:-10}
LIVE_VIS_COLORMAP=${LIVE_VIS_COLORMAP:-blue_red}
LIVE_VIS_WINDOW_SCALE=${LIVE_VIS_WINDOW_SCALE:-1}
LIVE_VIS_VSYNC=${LIVE_VIS_VSYNC:-0}
LIVE_VIS_CUDA_FIELD=${LIVE_VIS_CUDA_FIELD:-1}
LIVE_VIS_CUDA_SNAPSHOT=${LIVE_VIS_CUDA_SNAPSHOT:-0}
LIVE_VIS_LOG_SOURCE=${LIVE_VIS_LOG_SOURCE:-0}
LIVE_VIS_CONTROL_FILE=${LIVE_VIS_CONTROL_FILE:-./livevis_control.kv}
LIVE_VIS_HOLD_ON_EXIT=${LIVE_VIS_HOLD_ON_EXIT:-0}

# Output filters.
DUMP_ROLE_FILTER=${DUMP_ROLE_FILTER:-fluid}
SUMMARY_ROLE_FILTER=${SUMMARY_ROLE_FILTER:-fluid}

# Which modes to run.  Disable a mode by setting the corresponding RUN_* to 0.
RUN_SOLID=${RUN_SOLID:-1}
RUN_DARCY_MEAN=${RUN_DARCY_MEAN:-1}
RUN_DARCY_THERMAL=${RUN_DARCY_THERMAL:-1}
RUN_DARCY_OUTWARD=${RUN_DARCY_OUTWARD:-1}
RUN_DARCY_MEAN_OUTWARD=${RUN_DARCY_MEAN_OUTWARD:-1}
RUN_DARCY_MEAN_CHIVP=${RUN_DARCY_MEAN_CHIVP:-1}
RUN_DARCY_MEAN_OUTWARD_CHIVP=${RUN_DARCY_MEAN_OUTWARD_CHIVP:-1}

if [[ ! -f "$SOLID_SCRIPT" ]]; then echo "[0423] ERROR missing SOLID_SCRIPT=$SOLID_SCRIPT" >&2; exit 2; fi
if [[ ! -f "$DARCY_SCRIPT" ]]; then echo "[0423] ERROR missing DARCY_SCRIPT=$DARCY_SCRIPT" >&2; exit 2; fi
if [[ ! -f "$CHI_FILE" ]]; then echo "[0423] ERROR missing CHI_FILE=$CHI_FILE" >&2; exit 2; fi

if (truthy_0423 "$RUN_DARCY_MEAN_CHIVP" || truthy_0423 "$RUN_DARCY_MEAN_OUTWARD_CHIVP") && ! grep -q 'darcyChiCollisionVpEnable' "$DARCY_SCRIPT"; then
  echo "[0423] ERROR: $DARCY_SCRIPT does not appear to write darcyChiCollisionVpEnable into the generated .kv." >&2
  echo "[0423] Add the 0422 chiVP keys to the Darcy VK script before running chiVP modes." >&2
  exit 3
fi

if truthy_0423 "$CLEAN_SUITE"; then
  rm -rf "$SUITE_ROOT"
fi
mkdir -p "$SUITE_ROOT"
MANIFEST="$SUITE_ROOT/vk_final_compare_manifest_0423.csv"
echo 'mode,runRoot,outputDir,params,summary,dump3000,timeFile' > "$MANIFEST"

if truthy_0423 "$PREBUILD"; then
  echo "[0423] prebuilding livevis binary with current source tree"
  MPCD_ENABLE_LIVE_VIS=1 OUT=build/src_mpcd_base_cuda_q6_resident_0400_livevis bash scripts/build_src_mpcd_cuda_q6_resident_0400.sh
fi

common_live_env=(
  LIVE_VIS_ENABLE="$LIVE_VIS_ENABLE"
  LIVE_VIS_FIELD="$LIVE_VIS_FIELD"
  LIVE_VIS_EVERY="$LIVE_VIS_EVERY"
  LIVE_VIS_NX="$LIVE_VIS_NX"
  LIVE_VIS_NY="$LIVE_VIS_NY"
  LIVE_VIS_CLIP="$LIVE_VIS_CLIP"
  LIVE_VIS_GAIN="$LIVE_VIS_GAIN"
  LIVE_VIS_SMOOTH_PASSES="$LIVE_VIS_SMOOTH_PASSES"
  LIVE_VIS_COLORMAP="$LIVE_VIS_COLORMAP"
  LIVE_VIS_WINDOW_SCALE="$LIVE_VIS_WINDOW_SCALE"
  LIVE_VIS_VSYNC="$LIVE_VIS_VSYNC"
  LIVE_VIS_CUDA_FIELD="$LIVE_VIS_CUDA_FIELD"
  LIVE_VIS_CUDA_SNAPSHOT="$LIVE_VIS_CUDA_SNAPSHOT"
  LIVE_VIS_LOG_SOURCE="$LIVE_VIS_LOG_SOURCE"
  LIVE_VIS_CONTROL_FILE="$LIVE_VIS_CONTROL_FILE"
  LIVE_VIS_HOLD_ON_EXIT="$LIVE_VIS_HOLD_ON_EXIT"
)

run_solid_0423() {
  local baseRoot="$SUITE_ROOT/solid"
  echo "[0423] === solid reference ==="
  env \
    BASE_RUN_ROOT="$baseRoot" \
    RUN_MODES=classic \
    VK_MODE=periodic \
    CLEAN_RUN_ROOT=1 \
    FORCE_REBUILD=0 \
    AUTO_BUILD=1 \
    THREADS="$THREADS" \
    Lx="$Lx" Ly="$Ly" NX="$NX" NY="$NY" GAMMA="$GAMMA" \
    STEPS="$STEPS" DT="$DT" KBT="$KBT" SEED="$SEED" \
    SUMMARY_EVERY="$SUMMARY_EVERY" DUMP_STATE_EVERY="$DUMP_STATE_EVERY" \
    UIN="$U0" UINIT="$U0" \
    THERMOSTAT_ENABLE="$THERMOSTAT_ENABLE" \
    CYLINDER_CX="$CIRCLE_XC" CYLINDER_CY="$CIRCLE_YC" CYLINDER_R="$CIRCLE_RC" \
    DUMP_ROLE_FILTER="$DUMP_ROLE_FILTER" SUMMARY_ROLE_FILTER="$SUMMARY_ROLE_FILTER" \
    "${common_live_env[@]}" \
    bash "$SOLID_SCRIPT"

  local runRoot="$baseRoot/periodic/classic"
  local out="$runRoot/output"
  echo "solid,$runRoot,$out,$runRoot/params/von_karman_cylinder_0315_periodic.kv,$out/summary_runtime.csv,$out/state_step_00003000.smpcd,$runRoot/logs/von_karman_cylinder_0315_periodic.time" >> "$MANIFEST"
}

run_darcy_0423() {
  local modeName=$1
  local forcingMode=$2
  local chiVpEnable=$3
  local runRoot="$SUITE_ROOT/$modeName"
  echo "[0423] === $modeName forcing=$forcingMode chiVP=$chiVpEnable ==="
  env \
    TAG="$modeName" RUN_ROOT="$runRoot" \
    STATE_SOURCE="$SHARED_STATE" \
    CHI_FILE="$CHI_FILE" CHI_FILE_FORMAT="$CHI_FILE_FORMAT" \
    Lx="$Lx" Ly="$Ly" LX="$Lx" LY="$Ly" NX="$NX" NY="$NY" GAMMA="$GAMMA" \
    STEPS="$STEPS" DT="$DT" KBT="$KBT" SEED="$SEED" \
    THREADS="$THREADS" \
    SUMMARY_EVERY="$SUMMARY_EVERY" DUMP_STATE_EVERY="$DUMP_STATE_EVERY" \
    U0="$U0" UINIT="$U0" AX="$AX" AY="$AY" \
    ROTATION_ANGLE="$ROTATION_ANGLE" \
    THERMOSTAT_ENABLE="$THERMOSTAT_ENABLE" \
    CIRCLE_XC="$CIRCLE_XC" CIRCLE_YC="$CIRCLE_YC" CIRCLE_RC="$CIRCLE_RC" \
    ALPHA="$ALPHA" ALPHA_MIN="$ALPHA_MIN" DARCY_Q="$DARCY_Q" \
    DARCY_INITIAL_DEACTIVATE_BELOW_CHI="$DARCY_INITIAL_DEACTIVATE_BELOW_CHI" \
    DARCY_BRINKMAN_FORCING_MODE="$forcingMode" \
    WALL_KBT="$WALL_KBT" \
    DARCY_CHI_COLLISION_VP_ENABLE="$chiVpEnable" \
    DARCY_CHI_COLLISION_VP_GAMMA="$DARCY_CHI_COLLISION_VP_GAMMA" \
    DARCY_CHI_COLLISION_VP_LAYERS="$DARCY_CHI_COLLISION_VP_LAYERS" \
    DARCY_CHI_COLLISION_VP_STRENGTH="$DARCY_CHI_COLLISION_VP_STRENGTH" \
    DARCY_CHI_COLLISION_VP_THRESHOLD="$DARCY_CHI_COLLISION_VP_THRESHOLD" \
    TOPO_BENCHMARK_ENABLE=true \
    TOPO_BENCHMARK_EVERY="$SUMMARY_EVERY" \
    DARCY_COST_EVERY="$SUMMARY_EVERY" \
    DUMP_ROLE_FILTER="$DUMP_ROLE_FILTER" SUMMARY_ROLE_FILTER="$SUMMARY_ROLE_FILTER" \
    FORCE_BUILD=0 BUILD_IF_STALE=1 \
    "${common_live_env[@]}" \
    bash "$DARCY_SCRIPT"

  local out="$runRoot/output"
  echo "$modeName,$runRoot,$out,$runRoot/params/src_classic_darcy_chi.kv,$out/summary_runtime.csv,$out/state_step_00003000.smpcd,$runRoot/logs/src_classic_darcy_chi.time" >> "$MANIFEST"
}

if truthy_0423 "$RUN_SOLID"; then
  run_solid_0423
fi

SHARED_STATE=${SHARED_STATE:-$SUITE_ROOT/solid/periodic/classic/init/von_karman_cylinder_0315_periodic_${NX}x${NY}_g${GAMMA}.smpcd}
if [[ ! -f "$SHARED_STATE" ]]; then
  echo "[0423] ERROR shared initial state not found: $SHARED_STATE" >&2
  echo "[0423] Either run the solid mode first or provide SHARED_STATE=/path/to/state.smpcd" >&2
  exit 4
fi

echo "[0423] shared initial state for Darcy modes: $SHARED_STATE"

if truthy_0423 "$RUN_DARCY_MEAN"; then run_darcy_0423 darcy_mean mean 0; fi
if truthy_0423 "$RUN_DARCY_THERMAL"; then run_darcy_0423 darcy_thermal_bath thermal_bath 0; fi
if truthy_0423 "$RUN_DARCY_OUTWARD"; then run_darcy_0423 darcy_outward_bath outward_bath 0; fi
if truthy_0423 "$RUN_DARCY_MEAN_OUTWARD"; then run_darcy_0423 darcy_mean_outward mean_outward_bath 0; fi
if truthy_0423 "$RUN_DARCY_MEAN_CHIVP"; then run_darcy_0423 darcy_mean_chiVP mean 1; fi
if truthy_0423 "$RUN_DARCY_MEAN_OUTWARD_CHIVP"; then run_darcy_0423 darcy_mean_outward_chiVP mean_outward_bath 1; fi

echo "[0423] done"
echo "[0423] suite root: $SUITE_ROOT"
echo "[0423] manifest: $MANIFEST"
cat "$MANIFEST"
