#!/usr/bin/env bash
set -euo pipefail
ROOT="${ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
cd "$ROOT"

[[ -x scripts/run_0493x7n_path_fluid_calibrator.sh ]] || {
  echo "[0493x8e-cal] ERROR missing x7n path calibrator" >&2; exit 2; }
[[ -f scripts/analyze_0493x7n_tg_only.py ]] || {
  echo "[0493x8e-cal] ERROR missing canonical x7n TG analyzer" >&2; exit 2; }

RUN_ROOT_BASE="${RUN_ROOT_BASE:-runs/0493x8e_q6gf_tg_viscosity}"
SEEDS="${SEEDS:-493201 593201 693201 793201}"
LIVE_PROGRESS="${LIVE_PROGRESS:-1}"
PREFLIGHT_ONLY="${PREFLIGHT_ONLY:-0}"

# Exact microscopic state of x8d Poiseuille: a256_dt002_k125.
Lx=0.5; Ly=0.5; NX=128; NY=128; GAMMA=20
DT=0.002; KBT=0.125; PARTICLE_MASS=1.0
ROTATION_ANGLE=1.5707963267948966
RANDOM_ROTATION_SIGN=true
GRID_SHIFT_ENABLE=true
THERMOSTAT_ENABLE=true
THERMOSTAT_MODE=cell_relative_rescale
THERMOSTAT_EVERY=1
THERMOSTAT_TARGET_KBT=0.125
THERMOSTAT_MIN_PARTICLES=3

# Same physical TG wavelength as the final 0493w1 128^2 calibration:
# mode (2,2) in a .5 box -> wavelength .25 = 64 cells.
TG_MODE_X=2; TG_MODE_Y=2
TG_AMPLITUDE=0.05
TG_STEPS="${TG_STEPS:-2000}"
TG_DUMP_COUNT="${TG_DUMP_COUNT:-50}"

for seed in $SEEDS; do
  run="$RUN_ROOT_BASE/seed_$seed"
  echo "[0493x8e-cal] seed=$seed"
  CALIBRATION_PATH=src-q6-g-f \
  CALIBRATION_EXPERIMENTS=tg \
  RUN_ROOT="$run" \
  Lx="$Lx" Ly="$Ly" NX="$NX" NY="$NY" GAMMA="$GAMMA" \
  DT="$DT" KBT="$KBT" PARTICLE_MASS="$PARTICLE_MASS" SEED="$seed" \
  ROTATION_ANGLE="$ROTATION_ANGLE" \
  RANDOM_ROTATION_SIGN="$RANDOM_ROTATION_SIGN" \
  GRID_SHIFT_ENABLE="$GRID_SHIFT_ENABLE" \
  THERMOSTAT_ENABLE="$THERMOSTAT_ENABLE" \
  THERMOSTAT_MODE="$THERMOSTAT_MODE" THERMOSTAT_EVERY="$THERMOSTAT_EVERY" \
  THERMOSTAT_TARGET_KBT="$THERMOSTAT_TARGET_KBT" \
  THERMOSTAT_MIN_PARTICLES="$THERMOSTAT_MIN_PARTICLES" \
  TG_MODE_X="$TG_MODE_X" TG_MODE_Y="$TG_MODE_Y" \
  TG_AMPLITUDE="$TG_AMPLITUDE" TG_STEPS="$TG_STEPS" TG_DUMP_COUNT="$TG_DUMP_COUNT" \
  CHARACTERISTIC_U=0.1064 CHARACTERISTIC_L=0.24 \
  PROJECTION_TOLERANCE=1e-5 PROJECTION_MAX_ITERATIONS=800 Q6_STRICT=1 \
  Q6_GF_DENSITY_RELAXATION_TIME=0.25 \
  Q6_GF_DENSITY_COMPRESSION_GATE_ENABLE=1 \
  Q6_GF_DENSITY_COMPRESSION_THRESHOLD_PARTICLES=3 \
  Q6_GF_DENSITY_TRACTION_THRESHOLD_PARTICLES=6 \
  Q6_GF_DENSITY_TRACTION_GAIN=1 \
  Q6_GF_MIN_FILL_FRACTION=0.10 \
  MPCD_Q6_G_F_RESIDENT_CG_0493X7J=1 \
  MPCD_CUDA_Q6_RESIDENT_SINGLE_BLOCK_CG_0407=0 \
  SPECIES_RESAMPLING_ENABLE=false WEIGHTED_RESAMPLING_ENABLE_OVERRIDE=false \
  CUDA_EMPTY_REFILL_ENABLE_OVERRIDE=false \
  LIVE_PROGRESS="$LIVE_PROGRESS" LIVE_VIS_ENABLE=0 FILTERED_RECORDING_ENABLE=0 \
  PREFLIGHT_ONLY="$PREFLIGHT_ONLY" CLEAN_RUN_ROOT=1 \
  bash scripts/run_0493x7n_path_fluid_calibrator.sh
done

if [[ "$PREFLIGHT_ONLY" == 1 ]]; then
  echo "[0493x8e-cal] PREFLIGHT COMPLETE"
  exit 0
fi

python3 scripts/analyze_0493x8e_q6gf_tg_ensemble.py \
  --root "$RUN_ROOT_BASE" --seeds $SEEDS \
  --poiseuille-solid-nu 0.00070604 \
  --poiseuille-chi-nu 0.00071221 \
  --old-src-reference-nu 0.00059751
