#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

if [[ ! -x build/src_mpcd_base ]]; then
  ./scripts/build_src_mpcd_base.sh
fi

STATE="initial_state_backward_step_96x48_g20.smpcd"
if [[ ! -f "$STATE" ]]; then
  if command -v matlab >/dev/null 2>&1; then
    matlab -batch "cd('matlab'); generate_backward_step_state('output','../${STATE}');"
  else
    echo "Missing ${STATE}. Generate it from MATLAB:" >&2
    echo "  cd matlab" >&2
    echo "  generate_backward_step_state('output','../${STATE}');" >&2
    echo "  cd .." >&2
    exit 1
  fi
fi

RUN_CLASSIC="${RUN_CLASSIC:-1}"
RUN_Q6_SWEEP="${RUN_Q6_SWEEP:-1}"
RUN_Q9_SWEEP="${RUN_Q9_SWEEP:-1}"
RUN_ANALYSIS="${RUN_ANALYSIS:-0}"

N_STEPS="${N_STEPS:-30000}"
SUMMARY_EVERY="${SUMMARY_EVERY:-100}"
DUMP_STATE_EVERY="${DUMP_STATE_EVERY:-500}"
NUM_THREADS="${NUM_THREADS:-4}"

Q6_STRENGTHS="${Q6_STRENGTHS:-0.25 0.50 0.75 1.00}"
# Q9 cases are triples: q6Strength beta lowKMaxIndex.
Q9_CASES="${Q9_CASES:-0.50:0.00025:2 0.50:0.00100:2 0.50:0.00400:2 0.50:0.00100:4}"

CONFIG_DIR="runs/backward_step_parametric_suite_configs"
mkdir -p "$CONFIG_DIR"

float_tag() {
  local v="$1"
  v="${v/./p}"
  v="${v#0}"
  if [[ "$v" == p* ]]; then v="0${v}"; fi
  echo "$v"
}

write_case() {
  local method="$1"
  local out_dir="$2"
  local file="$3"
  local q6_strength="$4"
  local q9_enable="$5"
  local q9_beta="$6"
  local q9_lowk="$7"

  cat > "$file" <<EOF_INNER
# Auto-generated by scripts/run_backward_step_parametric_suite.sh.
# Periodic-x forced immersed-rectangle step. Not an inlet/outlet benchmark.

inputState = ${STATE}
outputDir = ${out_dir}

Lx = 2.0
Ly = 1.0
Nx = 96
Ny = 48

fluidXMin0 = 0.0
fluidXMax0 = -1.0
fluidYMin0 = 0.0
fluidYMax0 = -1.0

dt = 0.001
nSteps = ${N_STEPS}

rotationAngle = 2.0943951023931953
randomRotationSign = true
gridShiftEnable = true
rngSeed = 12345

bcLeft = periodic
bcRight = periodic
bcBottom = solid
bcTop = solid

bodyAccelerationX = 0.015
bodyAccelerationY = 0.0

projectionEnable = $( [[ "$method" == "classic" ]] && echo false || echo true )
projectionOperator = channel_fv_cg
projectionMaxIterations = 700
projectionTolerance = 1.0e-9
projectionMomentumCorrectionEnable = true
q6ProjectionStrength = ${q6_strength}
projectionImmersedSolidMaskEnable = $( [[ "$method" == "classic" ]] && echo false || echo true )
projectionImmersedSolidFluidFractionThreshold = 0.5
q9MassFluxProjectionEnable = ${q9_enable}
q9MassFluxProjectionStrength = 1.0
q9DensityRelaxationBeta = ${q9_beta}
q9TargetFilter = elliptic_lowpass
q9LowKMaxIndex = ${q9_lowk}
q9EllipticLowPassPasses = 1
q9MomentumCorrectionEnable = true
virialDiagnosticsEnable = false
virialKickEnable = false

immersedSolidEnable = true
immersedSolidShape = rectangle
immersedSolidXMin = 0.25
immersedSolidXMax = 0.65
immersedSolidYMin = 0.0
immersedSolidYMax = 0.50
immersedSolidFractionSamples = 4
immersedSolidVx = 0.0
immersedSolidVy = 0.0
immersedSolidWallUx = 0.0
immersedSolidWallUy = 0.0
immersedSolidOmega = 0.0

wallAccommodation = 1.0
wallVpGamma = 0.0
wallVpMass = 1.0
wallKBT = -1.0
wallThermalNoise = 1.0

thermostatEnable = true
thermostatMode = cell_relative_rescale
thermostatEvery = 1
thermostatTargetKBT = -1.0
thermostatMinParticles = 3
kBT = 0.0025

summaryEvery = ${SUMMARY_EVERY}
dumpStateEvery = ${DUMP_STATE_EVERY}
numThreads = ${NUM_THREADS}
EOF_INNER
}

run_param_file() {
  local desc="$1"
  local file="$2"
  echo "[backward-step-parametric] running ${desc}: ${file}"
  ./build/src_mpcd_base "$file"
}

if [[ "$RUN_CLASSIC" != "0" ]]; then
  cfg="$CONFIG_DIR/params_backward_step_parametric_classic_96x48.kv"
  out="runs/backward_step_parametric_classic_96x48"
  write_case "classic" "$out" "$cfg" "1.0" "false" "0.00025" "2"
  run_param_file "classic" "$cfg"
fi

if [[ "$RUN_Q6_SWEEP" != "0" ]]; then
  for strength in $Q6_STRENGTHS; do
    tag="$(float_tag "$strength")"
    cfg="$CONFIG_DIR/params_backward_step_parametric_q6_s${tag}_96x48.kv"
    out="runs/backward_step_parametric_q6_s${tag}_96x48"
    write_case "q6" "$out" "$cfg" "$strength" "false" "0.00025" "2"
    run_param_file "Q6 strength=${strength}" "$cfg"
  done
fi

if [[ "$RUN_Q9_SWEEP" != "0" ]]; then
  for spec in $Q9_CASES; do
    IFS=':' read -r strength beta lowk <<< "$spec"
    stag="$(float_tag "$strength")"
    btag="$(float_tag "$beta")"
    cfg="$CONFIG_DIR/params_backward_step_parametric_q9_s${stag}_b${btag}_k${lowk}_96x48.kv"
    out="runs/backward_step_parametric_q9_s${stag}_b${btag}_k${lowk}_96x48"
    write_case "q9" "$out" "$cfg" "$strength" "true" "$beta" "$lowk"
    run_param_file "Q9 q6Strength=${strength} beta=${beta} lowK=${lowk}" "$cfg"
  done
fi

if [[ "$RUN_ANALYSIS" != "0" ]]; then
  if command -v matlab >/dev/null 2>&1; then
    echo "[backward-step-parametric] running MATLAB parametric analysis"
    matlab -batch "cd('matlab'); validate_backward_step_parametric_suite('makePlots',false);"
  else
    echo "[backward-step-parametric] MATLAB not found; skipping analysis" >&2
  fi
fi

echo "[backward-step-parametric] done"
