#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

if [[ ! -x build/src_mpcd_base ]]; then
  ./scripts/build_src_mpcd_base.sh
fi

STATE="initial_state_backward_step_96x48_g20.smpcd"
if [[ ! -f "$STATE" ]]; then
  if command -v matlab >/dev/null 2>&1; then
    matlab -batch "cd('matlab'); generate_backward_step_state('output','../${STATE}');"
  else
    echo "Missing ${STATE}. Generate it from MATLAB:" >&2
    echo "  cd matlab" >&2
    echo "  generate_backward_step_state('output','../${STATE}');" >&2
    echo "  cd .." >&2
    exit 1
  fi
fi

RUN_Q9="${RUN_Q9:-1}"
RUN_Q9_VIRIAL="${RUN_Q9_VIRIAL:-1}"
RUN_ANALYSIS="${RUN_ANALYSIS:-0}"

N_STEPS="${N_STEPS:-30000}"
SUMMARY_EVERY="${SUMMARY_EVERY:-100}"
DUMP_STATE_EVERY="${DUMP_STATE_EVERY:-500}"
NUM_THREADS="${NUM_THREADS:-4}"

Q6_STRENGTH="${Q6_STRENGTH:-0.50}"
Q9_BETA="${Q9_BETA:-0.00100}"
Q9_LOWK="${Q9_LOWK:-2}"
VIRIAL_K="${VIRIAL_K:-0.50}"
VIRIAL_BETA="${VIRIAL_BETA:-0.05}"

CONFIG_DIR="runs/backward_step_liquid_closure_comparison_configs"
mkdir -p "$CONFIG_DIR"

write_case() {
  local method="$1"
  local out_dir="$2"
  local file="$3"
  local virial_enable="$4"

  cat > "$file" <<EOF_INNER
# Auto-generated by scripts/run_backward_step_liquid_closure_comparison.sh.
# Periodic-x forced immersed-rectangle step. This compares the selected
# masked Q6/Q9 setting against the complete Q6/Q9/virial liquid closure.

inputState = ${STATE}
outputDir = ${out_dir}

Lx = 2.0
Ly = 1.0
Nx = 96
Ny = 48

fluidXMin0 = 0.0
fluidXMax0 = -1.0
fluidYMin0 = 0.0
fluidYMax0 = -1.0

dt = 0.001
nSteps = ${N_STEPS}

rotationAngle = 2.0943951023931953
randomRotationSign = true
gridShiftEnable = true
rngSeed = 12345

bcLeft = periodic
bcRight = periodic
bcBottom = solid
bcTop = solid

bodyAccelerationX = 0.015
bodyAccelerationY = 0.0

projectionEnable = true
projectionOperator = channel_fv_cg
projectionMaxIterations = 700
projectionTolerance = 1.0e-9
projectionMomentumCorrectionEnable = true
q6ProjectionStrength = ${Q6_STRENGTH}
projectionImmersedSolidMaskEnable = true
projectionImmersedSolidFluidFractionThreshold = 0.5
projectionAllowUnmaskedImmersedSolid = false

q9MassFluxProjectionEnable = true
q9MassFluxProjectionStrength = 1.0
q9DensityRelaxationBeta = ${Q9_BETA}
q9TargetFilter = elliptic_lowpass
q9LowKMaxIndex = ${Q9_LOWK}
q9EllipticLowPassPasses = 1
q9MomentumCorrectionEnable = true

virialDiagnosticsEnable = ${virial_enable}
virialKickEnable = ${virial_enable}
Kvirial = ${VIRIAL_K}
virialBeta = ${VIRIAL_BETA}
virialRhoEOSRefMode = current_uniform
virialRhoUniformMode = particle_mean
virialDriveTargetMode = current_uniform
virialRhoKickMode = uniform_now
virialRhoKickMinFraction = 0.1
virialMomentumCorrectionEnable = true

immersedSolidEnable = true
immersedSolidShape = rectangle
immersedSolidXMin = 0.25
immersedSolidXMax = 0.65
immersedSolidYMin = 0.0
immersedSolidYMax = 0.50
immersedSolidFractionSamples = 4
immersedSolidVx = 0.0
immersedSolidVy = 0.0
immersedSolidWallUx = 0.0
immersedSolidWallUy = 0.0
immersedSolidOmega = 0.0

wallAccommodation = 1.0
wallVpGamma = 0.0
wallVpMass = 1.0
wallKBT = -1.0
wallThermalNoise = 1.0

thermostatEnable = true
thermostatMode = cell_relative_rescale
thermostatEvery = 1
thermostatTargetKBT = -1.0
thermostatMinParticles = 3
kBT = 0.0025

summaryEvery = ${SUMMARY_EVERY}
dumpStateEvery = ${DUMP_STATE_EVERY}
numThreads = ${NUM_THREADS}
EOF_INNER
}

run_case() {
  local desc="$1"
  local cfg="$2"
  echo "[backward-step-liquid] running ${desc}: ${cfg}"
  ./build/src_mpcd_base "$cfg"
}

if [[ "$RUN_Q9" != "0" ]]; then
  cfg="$CONFIG_DIR/params_backward_step_liquid_q9_selected_96x48.kv"
  out="runs/backward_step_liquid_q9_selected_96x48"
  write_case "q9" "$out" "$cfg" "false"
  run_case "Q9 selected, no virial" "$cfg"
fi

if [[ "$RUN_Q9_VIRIAL" != "0" ]]; then
  cfg="$CONFIG_DIR/params_backward_step_liquid_q9_virial_selected_96x48.kv"
  out="runs/backward_step_liquid_q9_virial_selected_96x48"
  write_case "q9_virial" "$out" "$cfg" "true"
  run_case "Q9 selected + virial" "$cfg"
fi

if [[ "$RUN_ANALYSIS" != "0" ]]; then
  if command -v matlab >/dev/null 2>&1; then
    matlab -batch "cd('matlab'); suite = validate_backward_step_liquid_closure_comparison();"
  else
    echo "MATLAB not found; analyze later with:" >&2
    echo "  cd matlab" >&2
    echo "  suite = validate_backward_step_liquid_closure_comparison();" >&2
  fi
fi
