#!/usr/bin/env bash
set -u

# 0493x18b — hinged rigid plate released under gravity in a quiescent fluid.
# Runner-only variant of x18a: no C++/CUDA change.
#
# Sign convention of x18a:
#   theta = 0      : plate hanging vertically downward
#   theta > 0      : lower end displaced toward +x
#   theta < 0      : lower end displaced toward -x
# Therefore INITIAL_ANGLE_DEG=-45 starts the plate raised to the left and
# gravity drives it counter-clockwise (theta increasing toward zero).
#
# Density sweep strategy:
#   gamma is kept fixed.
#   particle mass and kBT are scaled by the SAME factor, so kBT/m is constant.
# This keeps the initial thermal velocity scale sqrt(kBT/m) unchanged while
# changing the areal mass density rho_2D = gamma*m/h^2.

ROOT="${ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
BASE_RUNNER="$ROOT/scripts/run_0493x18a_hinged_plate.sh"
if [[ ! -f "$BASE_RUNNER" ]]; then
    echo "[0493x18b] ERROR missing base x18a runner: $BASE_RUNNER" >&2
    exit 2
fi

# ------------------------------ fluid ---------------------------------
# FLUID_REGIME only provides a convenient default density factor.
# It does NOT switch to a different equation of state / multiphase model.
FLUID_REGIME="${FLUID_REGIME:-liquid}"
case "$FLUID_REGIME" in
    gas)    DEFAULT_DENSITY_FACTOR="0.010" ;;
    liquid) DEFAULT_DENSITY_FACTOR="1.00" ;;
    custom) DEFAULT_DENSITY_FACTOR="1.00" ;;
    *)
        echo "[0493x18b] ERROR FLUID_REGIME must be gas, liquid or custom" >&2
        exit 2
        ;;
esac

FLUID_DENSITY_FACTOR="${FLUID_DENSITY_FACTOR:-$DEFAULT_DENSITY_FACTOR}"

# x18a reference state.  kBT/m = 0.125 exactly.
REF_PARTICLE_MASS="${REF_PARTICLE_MASS:-0.4444444444444444}"
REF_KBT="${REF_KBT:-0.05555555555555556}"

# Geometry/grid are exposed here so an absolute rho_2D can optionally be used.
Lx="${Lx:-0.75}"
Ly="${Ly:-0.5}"
NX="${NX:-288}"
NY="${NY:-192}"
GAMMA="${GAMMA:-20}"

read -r H PARTICLE_MASS KBT RHO2D DENSITY_FACTOR_EFFECTIVE < <(
python3 - "$Lx" "$Ly" "$NX" "$NY" "$GAMMA" \
    "$REF_PARTICLE_MASS" "$REF_KBT" "$FLUID_DENSITY_FACTOR" "${FLUID_RHO2D:-}" <<'PY'
import math,sys
Lx,Ly=float(sys.argv[1]),float(sys.argv[2])
nx,ny=int(sys.argv[3]),int(sys.argv[4])
gamma=int(sys.argv[5])
mref,kref=float(sys.argv[6]),float(sys.argv[7])
factor=float(sys.argv[8])
rho_arg=sys.argv[9].strip()
hx=Lx/nx; hy=Ly/ny
if abs(hx-hy)>1e-12*max(hx,hy):
    raise SystemExit(f"0493x18b requires square cells: hx={hx} hy={hy}")
if gamma <= 0 or mref <= 0 or kref <= 0:
    raise SystemExit("0493x18b requires positive gamma/reference mass/reference kBT")
q=kref/mref
if rho_arg:
    rho=float(rho_arg)
    if not math.isfinite(rho) or rho<=0:
        raise SystemExit("FLUID_RHO2D must be positive and finite")
    m=rho*hx*hx/gamma
    factor_eff=m/mref
else:
    if not math.isfinite(factor) or factor<=0:
        raise SystemExit("FLUID_DENSITY_FACTOR must be positive and finite")
    m=mref*factor
    factor_eff=factor
    rho=gamma*m/(hx*hx)
k=q*m
print(f"{hx:.17g} {m:.17g} {k:.17g} {rho:.17g} {factor_eff:.17g}")
PY
) || exit $?

# ------------------------------ solid ---------------------------------
# x18a theta=0 is vertical down.  -45 deg gives a raised plate whose gravity
# torque is positive, hence counter-clockwise in the x18a convention.
INITIAL_ANGLE_DEG="${INITIAL_ANGLE_DEG:--45.0}"
HINGED_INITIAL_ANGLE="$(python3 - "$INITIAL_ANGLE_DEG" <<'PY'
import math,sys
print(f"{math.radians(float(sys.argv[1])):.17g}")
PY
)"
HINGED_INITIAL_OMEGA="${HINGED_INITIAL_OMEGA:-0.0}"

SOLID_MASS="${SOLID_MASS:-4000.0}"
HINGED_GRAVITY_Y="${HINGED_GRAVITY_Y:--10.0}"
# Keep mechanical hinge damping zero by default: the contrast between gas and
# liquid should primarily come from the fluid loading/damping.
HINGED_ANGULAR_DAMPING="${HINGED_ANGULAR_DAMPING:-0.0}"

# ------------------------------ run -----------------------------------
FLOW_UX="0.0"
# x18f: no imposed through-flow.  Two passive Neumann faces let the
# pressure/velocity disturbance generated by the falling flap leave either side
# without periodic recycling and without imposing a directional inlet.
HINGED_X_BOUNDARY_MODE="${HINGED_X_BOUNDARY_MODE:-double_neumann}"
STEPS="${STEPS:-400}"
DT="${DT:-0.006}"
SEED="${SEED:-4931802}"
SUMMARY_EVERY="${SUMMARY_EVERY:-1}"
HINGED_OUTPUT_EVERY="${HINGED_OUTPUT_EVERY:-5}"
DUMP_STATE_EVERY="${DUMP_STATE_EVERY:-0}"

LIVE_PROGRESS="${LIVE_PROGRESS:-1}"
LIVE_VIS_ENABLE="${LIVE_VIS_ENABLE:-1}"
LIVE_VIS_EVERY="${LIVE_VIS_EVERY:-1}"
LIVE_VIS_FIELD="${LIVE_VIS_FIELD:-ux}"
RECORD_ENABLE="${RECORD_ENABLE:-true}"
RECORD_EVERY="${RECORD_EVERY:-20}"
RECORD_FIELDS="${RECORD_FIELDS:-rho,ux,uy,n}"

FACTOR_TAG="$(python3 - "$DENSITY_FACTOR_EFFECTIVE" <<'PY'
import sys
s=f"{float(sys.argv[1]):.6g}"
print(s.replace('-','m').replace('+','').replace('.','p'))
PY
)"
CASE_LABEL="${CASE_LABEL:-0493x18b_hinged_fall_${FLUID_REGIME}_rho${FACTOR_TAG}}"
BASE_RUN_ROOT="${BASE_RUN_ROOT:-runs/${CASE_LABEL}}"

cat <<INFO

===== 0493x18b HINGED FALL IN QUIESCENT FLUID =====
regime=$FLUID_REGIME
flowUx=$FLOW_UX
initialAngleDeg=$INITIAL_ANGLE_DEG  (negative => raised left; gravity-driven motion is CCW toward theta=0)
steps=$STEPS dt=$DT
solidMass=$SOLID_MASS gravityY=$HINGED_GRAVITY_Y hingeDamping=$HINGED_ANGULAR_DAMPING
fluidDensityFactor=$DENSITY_FACTOR_EFFECTIVE
rho2D=$RHO2D
gamma=$GAMMA particleMass=$PARTICLE_MASS kBT=$KBT kBT_over_m=$(python3 - "$KBT" "$PARTICLE_MASS" <<'PY'
import sys
print(f"{float(sys.argv[1])/float(sys.argv[2]):.17g}")
PY
)
run=$BASE_RUN_ROOT/fresh
INFO

# Explicitly override the user's x18a defaults (which may have been edited for
# the transverse-flow demonstration).
Lx="$Lx" Ly="$Ly" NX="$NX" NY="$NY" GAMMA="$GAMMA" \
PARTICLE_MASS="$PARTICLE_MASS" KBT="$KBT" \
FLOW_UX="$FLOW_UX" STEPS="$STEPS" DT="$DT" SEED="$SEED" \
SOLID_MASS="$SOLID_MASS" \
HINGED_GRAVITY_Y="$HINGED_GRAVITY_Y" \
HINGED_ANGULAR_DAMPING="$HINGED_ANGULAR_DAMPING" \
HINGED_INITIAL_ANGLE="$HINGED_INITIAL_ANGLE" \
HINGED_INITIAL_OMEGA="$HINGED_INITIAL_OMEGA" \
HINGED_OUTPUT_EVERY="$HINGED_OUTPUT_EVERY" \
SUMMARY_EVERY="$SUMMARY_EVERY" DUMP_STATE_EVERY="$DUMP_STATE_EVERY" \
LIVE_PROGRESS="$LIVE_PROGRESS" LIVE_VIS_ENABLE="$LIVE_VIS_ENABLE" \
LIVE_VIS_EVERY="$LIVE_VIS_EVERY" LIVE_VIS_FIELD="$LIVE_VIS_FIELD" \
RECORD_ENABLE="$RECORD_ENABLE" RECORD_EVERY="$RECORD_EVERY" \
RECORD_FIELDS="$RECORD_FIELDS" \
HINGED_X_BOUNDARY_MODE="$HINGED_X_BOUNDARY_MODE" \
CASE_LABEL="$CASE_LABEL" BASE_RUN_ROOT="$BASE_RUN_ROOT" \
bash "$BASE_RUNNER"
rc=$?
if [[ $rc -ne 0 ]]; then exit $rc; fi

META="$BASE_RUN_ROOT/fresh/run_meta_0493x18b_hinged_fall.txt"
cat > "$META" <<META
case=0493x18b_hinged_fall_quiescent
baseModel=0493x18a_hinged_plate_2d
fluidRegimeLabel=$FLUID_REGIME
fluidInitiallyQuiescent=true
flowUx=0.0
xBoundaryMode=$HINGED_X_BOUNDARY_MODE
fluidDensityFactor=$DENSITY_FACTOR_EFFECTIVE
rho2D=$RHO2D
gamma=$GAMMA
particleMass=$PARTICLE_MASS
kBT=$KBT
kBTOverMass=$(python3 - "$KBT" "$PARTICLE_MASS" <<'PY'
import sys
print(f"{float(sys.argv[1])/float(sys.argv[2]):.17g}")
PY
)
initialAngleDeg=$INITIAL_ANGLE_DEG
initialAngleRad=$HINGED_INITIAL_ANGLE
initialOmega=$HINGED_INITIAL_OMEGA
solidMass=$SOLID_MASS
gravityY=$HINGED_GRAVITY_Y
angularDamping=$HINGED_ANGULAR_DAMPING
steps=$STEPS
dt=$DT
seed=$SEED
META

echo "[0493x18b] COMPLETE run=$BASE_RUN_ROOT/fresh"
echo "[0493x18b] dynamics=$BASE_RUN_ROOT/fresh/output/chi_hinged_plate_0493x18a.csv"
