#!/usr/bin/env bash
set -euo pipefail

# 0493x8d-a — Q6-g-f-only physical-wall Poiseuille qualification.
#
# No C++/CUDA changes and no new diagnostics.  This runner deliberately reuses
# the calibrated 0493w1 a256_dt002_k125 fluid rather than the historical
# high-force/pathological Poiseuille states.
#
# Reference microscopic/effective state:
#   a=1/256, gamma=20, dt=.002, kBT=.125, m=1, rotation=90 deg
#   nu_ref=5.9751e-4, cs_ref=.35459, Dself=1.6588e-4
#   Uchar=.1064, Lref=.24 -> Re_ref=42.737360, Ma_ref=0.300065
#
# Geometry:
#   H=.25 = 64 cells, Lx=.5 = 128 cells, periodic x, physical walls y.
# Body acceleration is selected from no-slip Poiseuille using nu_ref so the
# reference centerline speed is Uchar=.1064.

ROOT="${ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
cd "$ROOT"

RUN_MODES="src-q6-g-f"
Lx="${Lx:-0.5}"
Ly="${Ly:-0.25}"
NX="${NX:-128}"
NY="${NY:-64}"
GAMMA="${GAMMA:-20}"
DT="${DT:-0.002}"
KBT="${KBT:-0.125}"
PARTICLE_MASS="${PARTICLE_MASS:-1.0}"
SEED="${SEED:-493202}"
ROTATION_ANGLE="${ROTATION_ANGLE:-1.5707963267948966}"
RANDOM_ROTATION_SIGN="${RANDOM_ROTATION_SIGN:-true}"
GRID_SHIFT_ENABLE="${GRID_SHIFT_ENABLE:-true}"
THERMOSTAT_ENABLE="${THERMOSTAT_ENABLE:-true}"
THERMOSTAT_MODE="${THERMOSTAT_MODE:-cell_relative_rescale}"
THERMOSTAT_EVERY="${THERMOSTAT_EVERY:-1}"
THERMOSTAT_TARGET_KBT="${THERMOSTAT_TARGET_KBT:-$KBT}"
THERMOSTAT_MIN_PARTICLES="${THERMOSTAT_MIN_PARTICLES:-3}"

REFERENCE_NU="${REFERENCE_NU:-0.00059751}"
REFERENCE_CS="${REFERENCE_CS:-0.35459}"
REFERENCE_DSELF="${REFERENCE_DSELF:-0.00016588}"
REFERENCE_UCHAR="${REFERENCE_UCHAR:-0.1064}"
REFERENCE_L="${REFERENCE_L:-0.24}"

BODY_AX="${BODY_AX:-0.0081376081920000003}"
U0=0.0
VELOCITY_MODE=zero
STEPS="${STEPS:-30000}"
SUMMARY_EVERY="${SUMMARY_EVERY:-100}"
DUMP_STATE_EVERY="${DUMP_STATE_EVERY:-1000}"
BASE_RUN_ROOT="${BASE_RUN_ROOT:-runs/0493x8d_q6gf_poiseuille_qualification/solid}"
LIVE_PROGRESS="${LIVE_PROGRESS:-1}"
LIVE_VIS_ENABLE="${LIVE_VIS_ENABLE:-0}"
LIVE_VIS_HOLD_ON_EXIT=0
FILTERED_RECORDING_ENABLE=0
PREFLIGHT_ONLY="${PREFLIGHT_ONLY:-0}"
CLEAN_RUN_ROOT="${CLEAN_RUN_ROOT:-1}"

PROJECTION_TOLERANCE="${PROJECTION_TOLERANCE:-1.0e-5}"
PROJECTION_MAX_ITERATIONS="${PROJECTION_MAX_ITERATIONS:-800}"
Q6_STRICT="${Q6_STRICT:-1}"
Q6_GF_DENSITY_RELAXATION_TIME="${Q6_GF_DENSITY_RELAXATION_TIME:-0.25}"
Q6_GF_DENSITY_COMPRESSION_GATE_ENABLE="${Q6_GF_DENSITY_COMPRESSION_GATE_ENABLE:-1}"
Q6_GF_DENSITY_COMPRESSION_THRESHOLD_PARTICLES="${Q6_GF_DENSITY_COMPRESSION_THRESHOLD_PARTICLES:-3}"
Q6_GF_DENSITY_TRACTION_THRESHOLD_PARTICLES="${Q6_GF_DENSITY_TRACTION_THRESHOLD_PARTICLES:-6}"
Q6_GF_DENSITY_TRACTION_GAIN="${Q6_GF_DENSITY_TRACTION_GAIN:-1.0}"
Q6_GF_MIN_FILL_FRACTION="${Q6_GF_MIN_FILL_FRACTION:-0.10}"
Q6_GF_HAS_GAS_PHASE=0
Q6_GF_EXTERNAL_SPECIES=0
MPCD_Q6_G_F_RESIDENT_CG_0493X7J="${MPCD_Q6_G_F_RESIDENT_CG_0493X7J:-1}"
MPCD_CUDA_Q6_RESIDENT_SINGLE_BLOCK_CG_0407="${MPCD_CUDA_Q6_RESIDENT_SINGLE_BLOCK_CG_0407:-0}"

SPECIES_RESAMPLING_ENABLE=false
WEIGHTED_RESAMPLING_ENABLE_OVERRIDE=false
CUDA_EMPTY_REFILL_ENABLE_OVERRIDE=false


python3 - "$Lx" "$Ly" "$NX" "$NY" "$DT" "$KBT" "$GAMMA" \
  "$REFERENCE_NU" "$REFERENCE_CS" "$REFERENCE_UCHAR" "$REFERENCE_L" \
  "$BODY_AX" "$STEPS" <<'PY_X8D_SOLID'
import math, sys
lx,ly,nx,ny,dt,kbt,gamma,nu,cs,U,L,ax,steps=sys.argv[1:]
lx=float(lx); ly=float(ly); nx=int(nx); ny=int(ny)
dt=float(dt); kbt=float(kbt); gamma=int(gamma)
nu=float(nu); cs=float(cs); U=float(U); L=float(L)
ax=float(ax); steps=int(steps)
dx=lx/nx; dy=ly/ny
if abs(dx-dy) > 1e-12*max(dx,dy):
    raise SystemExit(f"[0493x8d-solid] ERROR non-square cells dx={dx} dy={dy}")
if abs(dx-1/256) > 1e-12:
    raise SystemExit(f"[0493x8d-solid] ERROR a={dx:.12g}; calibrated fluid requires 1/256")
ax_ref=8*nu*U/(ly*ly)
if abs(ax-ax_ref) > 1e-10*max(1.0,abs(ax_ref)):
    print(f"[0493x8d-solid] NOTE BODY_AX override={ax:.12g} reference={ax_ref:.12g}")
tau=ly*ly/(math.pi**2*nu)
print(f"[0493x8d-solid] fluid=a256_dt002_k125 gamma={gamma} kBT={kbt} dt={dt}")
print(f"[0493x8d-solid] a={dx:.9g} H/a={ly/dy:.0f} Re_ref={U*L/nu:.5f} Ma_ref={U/cs:.5f}")
print(f"[0493x8d-solid] ax={ax:.12g} Uc_ref={U:.8g} tau_diff={tau:.6g} tEnd/tau={steps*dt/tau:.3f}")
PY_X8D_SOLID

PROJECTION_TOLERANCE="$PROJECTION_TOLERANCE" \
PROJECTION_MAX_ITERATIONS="$PROJECTION_MAX_ITERATIONS" \
Q6_STRICT="$Q6_STRICT" \
Q6_GF_DENSITY_RELAXATION_TIME="$Q6_GF_DENSITY_RELAXATION_TIME" \
Q6_GF_DENSITY_COMPRESSION_GATE_ENABLE="$Q6_GF_DENSITY_COMPRESSION_GATE_ENABLE" \
Q6_GF_DENSITY_COMPRESSION_THRESHOLD_PARTICLES="$Q6_GF_DENSITY_COMPRESSION_THRESHOLD_PARTICLES" \
Q6_GF_DENSITY_TRACTION_THRESHOLD_PARTICLES="$Q6_GF_DENSITY_TRACTION_THRESHOLD_PARTICLES" \
Q6_GF_DENSITY_TRACTION_GAIN="$Q6_GF_DENSITY_TRACTION_GAIN" \
Q6_GF_MIN_FILL_FRACTION="$Q6_GF_MIN_FILL_FRACTION" \
Q6_GF_HAS_GAS_PHASE=0 Q6_GF_EXTERNAL_SPECIES=0 \
MPCD_Q6_G_F_RESIDENT_CG_0493X7J="$MPCD_Q6_G_F_RESIDENT_CG_0493X7J" \
MPCD_CUDA_Q6_RESIDENT_SINGLE_BLOCK_CG_0407="$MPCD_CUDA_Q6_RESIDENT_SINGLE_BLOCK_CG_0407" \
SPECIES_RESAMPLING_ENABLE=false WEIGHTED_RESAMPLING_ENABLE_OVERRIDE=false \
CUDA_EMPTY_REFILL_ENABLE_OVERRIDE=false \
RUN_MODES="$RUN_MODES" Lx="$Lx" Ly="$Ly" NX="$NX" NY="$NY" GAMMA="$GAMMA" \
DT="$DT" KBT="$KBT" PARTICLE_MASS="$PARTICLE_MASS" SEED="$SEED" \
ROTATION_ANGLE="$ROTATION_ANGLE" RANDOM_ROTATION_SIGN="$RANDOM_ROTATION_SIGN" \
GRID_SHIFT_ENABLE="$GRID_SHIFT_ENABLE" THERMOSTAT_ENABLE="$THERMOSTAT_ENABLE" \
THERMOSTAT_MODE="$THERMOSTAT_MODE" THERMOSTAT_EVERY="$THERMOSTAT_EVERY" \
THERMOSTAT_TARGET_KBT="$THERMOSTAT_TARGET_KBT" THERMOSTAT_MIN_PARTICLES="$THERMOSTAT_MIN_PARTICLES" \
BODY_AX="$BODY_AX" U0=0 VELOCITY_MODE=zero STEPS="$STEPS" \
SUMMARY_EVERY="$SUMMARY_EVERY" DUMP_STATE_EVERY="$DUMP_STATE_EVERY" \
BASE_RUN_ROOT="$BASE_RUN_ROOT" LIVE_PROGRESS="$LIVE_PROGRESS" \
LIVE_VIS_ENABLE="$LIVE_VIS_ENABLE" LIVE_VIS_HOLD_ON_EXIT=0 FILTERED_RECORDING_ENABLE=0 \
PREFLIGHT_ONLY="$PREFLIGHT_ONLY" CLEAN_RUN_ROOT="$CLEAN_RUN_ROOT" \
bash scripts/run_ok_poiseuille.sh
