#!/usr/bin/env bash
set -euo pipefail

# 0229 — shadow validation of CUDA resampling classification/compaction/plan
# on the real WeightedRealFluidDepositWorkspace generated by the simulation.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

BIN=${BIN:-build/src_mpcd_base_cuda_0229}
ART_DIR=${ART_DIR:-dev_history/artifacts/gpu_cuda_resampling_0229}
GRID_CASES=${GRID_CASES:-"64:200 128:100"}
GAMMA=${GAMMA:-20}
THREADS=${THREADS:-8}
SUMMARY_EVERY_DEFAULT=${SUMMARY_EVERY:-50}
SEED_BASE=${SEED_BASE:-1620229}
CASE_LIST=${CASE_LIST:-tg_periodic_full}
PROJECTION_BACKEND=${PROJECTION_BACKEND:-cpu}
PROJECTION_ENABLE=${PROJECTION_ENABLE:-false}
STOP_ON_FAIL=${STOP_ON_FAIL:-1}

mkdir -p "$ART_DIR"

if [[ ! -x "$BIN" ]]; then
  OUT="$BIN" CUDA_ARCH_FLAGS=${CUDA_ARCH_FLAGS:-} bash scripts/build_src_mpcd_cuda_0229.sh
fi
if [[ ! -x "$BIN" ]]; then
  echo "[0229-resampling-shadow] ERROR: missing binary $BIN" >&2
  exit 127
fi

OUT_CSV=${OUT_CSV:-$ART_DIR/cuda_resampling_shadow_0229.csv}
printf 'grid,NX,NY,steps,mode,baselineWallTime,modeWallTime,wallDelta_s,wallSpeedup,failed_metrics,compared_metrics,verdict,shadowRows,shadowPassRows,shadowPoorMismatch,shadowRichMismatch,shadowDeficitAbsDiffMax,shadowExcessAbsDiffMax,shadowPlannedAbsDiffMax,shadowCsv,compareCsv,compareSummary\n' > "$OUT_CSV"

run_validation() {
  local nx=$1 ny=$2 steps=$3 root=$4 tag=$5 shadow=$6 shadow_csv=$7
  local summary_every=${SUMMARY_EVERY_OVERRIDE:-$SUMMARY_EVERY_DEFAULT}
  local seed=$((SEED_BASE + nx + steps))
  env BIN="$BIN" BUILD_IF_MISSING=0 CASE_LIST="$CASE_LIST" \
      NX="$nx" NY="$ny" GAMMA="$GAMMA" STEPS="$steps" SUMMARY_EVERY="$summary_every" \
      THREADS="$THREADS" SEED="$seed" DUMP_STATE_EVERY=0 \
      RUN_ROOT="$root" RUN_TAG="$tag" PROJECTION_BACKEND="$PROJECTION_BACKEND" PROJECTION_ENABLE="$PROJECTION_ENABLE" \
      MPCD_CUDA_RESAMPLING_SHADOW="$shadow" \
      MPCD_CUDA_RESAMPLING_SHADOW_STRICT=1 \
      MPCD_CUDA_RESAMPLING_SHADOW_CSV="$shadow_csv" \
      bash scripts/run_validation_mono_config_0162.sh
}

append_summary() {
  local label=$1 nx=$2 ny=$3 steps=$4 mode=$5 base_root=$6 run_root=$7 shadow_csv=$8 compare_csv=$9 compare_summary=${10}
  python3 - "$label" "$nx" "$ny" "$steps" "$mode" "$base_root/validation_summary_0162.csv" "$run_root/validation_summary_0162.csv" "$shadow_csv" "$compare_csv" "$compare_summary" "$OUT_CSV" <<'PY'
import csv, math, os, sys
label,nx,ny,steps,mode,base_summary,run_summary,shadow_csv,compare_csv,compare_summary,out_csv=sys.argv[1:12]
fields=['grid','NX','NY','steps','mode','baselineWallTime','modeWallTime','wallDelta_s','wallSpeedup','failed_metrics','compared_metrics','verdict','shadowRows','shadowPassRows','shadowPoorMismatch','shadowRichMismatch','shadowDeficitAbsDiffMax','shadowExcessAbsDiffMax','shadowPlannedAbsDiffMax','shadowCsv','compareCsv','compareSummary']

def read_one(path, default=None):
    if path == 'none' or not os.path.exists(path):
        if default is not None: return default
        raise SystemExit(f'missing {path}')
    with open(path,newline='') as f: rows=list(csv.DictReader(f))
    if len(rows)!=1: raise SystemExit(f'expected one row in {path}, got {len(rows)}')
    return rows[0]

def f(r,k,default='nan'):
    try: return float(r.get(k,default) or default)
    except Exception: return float('nan')

def i(r,k,default='0'):
    try: return int(round(float(r.get(k,default) or default)))
    except Exception: return 0
base=read_one(base_summary); run=read_one(run_summary)
cmp=read_one(compare_summary, {'failed_metrics':'0','compared_metrics':'0'})
failed=i(cmp,'failed_metrics','0'); compared=i(cmp,'compared_metrics','0')
shadow_rows=[]
if shadow_csv != 'none' and os.path.exists(shadow_csv):
    with open(shadow_csv,newline='') as fp: shadow_rows=list(csv.DictReader(fp))

def max_float(name):
    vals=[]
    for r in shadow_rows:
        try: vals.append(abs(float(r.get(name,'0') or 0.0)))
        except Exception: pass
    return max(vals) if vals else 0.0
shadow_poor=sum(i(r,'poorMismatch','0') for r in shadow_rows)
shadow_rich=sum(i(r,'richMismatch','0') for r in shadow_rows)
shadow_pass=sum(1 for r in shadow_rows if str(r.get('pass','0')) in ('1','1.0','true','True'))
wall=f(run,'wallTime'); bwall=f(base,'wallTime')
verdict='PASS' if failed==0 and (mode=='cpu_baseline' or (shadow_rows and shadow_pass==len(shadow_rows) and shadow_poor==0 and shadow_rich==0)) else 'FAIL'
row={
 'grid':label,'NX':nx,'NY':ny,'steps':steps,'mode':mode,
 'baselineWallTime':bwall,'modeWallTime':wall,'wallDelta_s':wall-bwall,'wallSpeedup':bwall/wall if wall>0 else float('nan'),
 'failed_metrics':failed,'compared_metrics':compared,'verdict':verdict,
 'shadowRows':len(shadow_rows),'shadowPassRows':shadow_pass,
 'shadowPoorMismatch':shadow_poor,'shadowRichMismatch':shadow_rich,
 'shadowDeficitAbsDiffMax':max_float('deficitAbsDiff'),
 'shadowExcessAbsDiffMax':max_float('excessAbsDiff'),
 'shadowPlannedAbsDiffMax':max_float('plannedAbsDiff'),
 'shadowCsv':shadow_csv,'compareCsv':compare_csv,'compareSummary':compare_summary}
with open(out_csv,'a',newline='') as fcsv: csv.DictWriter(fcsv,fieldnames=fields).writerow(row)
print(f"[0229-resampling-shadow] {verdict} {label}/{mode}: wall={wall:.6g}s baseline={bwall:.6g}s shadowRows={len(shadow_rows)} poorMismatch={shadow_poor} richMismatch={shadow_rich} failed={failed}/{compared}")
if verdict!='PASS': raise SystemExit(1)
PY
}

for spec in $GRID_CASES; do
  IFS=: read -r nx steps <<< "$spec"
  [[ -n "${nx:-}" && -n "${steps:-}" ]] || { echo "[0229-resampling-shadow] invalid GRID_CASES entry $spec" >&2; exit 2; }
  ny=${NY_OVERRIDE:-$nx}
  label="${nx}x${ny}_s${steps}"
  base_root="runs/cuda_resampling_shadow_0229_cpu_baseline_${label}"
  shadow_root="runs/cuda_resampling_shadow_0229_shadow_${label}"
  shadow_csv="$ART_DIR/cuda_resampling_shadow_detail_0229_${label}.csv"
  rm -f "$shadow_csv"

  echo "[0229-resampling-shadow] running baseline $label"
  run_validation "$nx" "$ny" "$steps" "$base_root" "cuda0229_cpu_${label}" 0 "none"
  append_summary "$label" "$nx" "$ny" "$steps" "cpu_baseline" "$base_root" "$base_root" "none" "none" "none"

  echo "[0229-resampling-shadow] running shadow $label"
  run_validation "$nx" "$ny" "$steps" "$shadow_root" "cuda0229_shadow_${label}" 1 "$shadow_csv"
  compare_csv="$ART_DIR/cuda_resampling_shadow_compare_0229_${label}.csv"
  compare_summary="$ART_DIR/cuda_resampling_shadow_compare_summary_0229_${label}.csv"
  python3 scripts/compare_validation_mono_config_0162.py \
    --origin "$base_root" --optimized "$shadow_root" \
    --out "$compare_csv" --summary-out "$compare_summary"
  append_summary "$label" "$nx" "$ny" "$steps" "cuda_resampling_shadow" "$base_root" "$shadow_root" "$shadow_csv" "$compare_csv" "$compare_summary"

done

echo "[0229-resampling-shadow] wrote $OUT_CSV"
