#!/usr/bin/env bash
set -euo pipefail

ROOT="${ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
cd "$ROOT"

# 0493x13ze -- shared base for the two free-surface run_ok demonstrations.
#
# This is intentionally a profile/wrapper around the existing x9s state and
# parameter generator, not a second implementation of droplet impact.  It
# freezes the experimentally retained x12a splash profile at the tagged
# surface-free reference:
#   x10o + CIC + Q2 + x10p/x10q + x10u + x10v full-vector swap + x12a.
#
# The two public runners differ ONLY by TARGET:
#   run_ok_splash.sh -> dry solid wall
#   run_ok_puddle.sh -> initially quiescent liquid layer
# Everything else is common by construction.

BASE_RUNNER="$ROOT/scripts/run_0493x9s_splash.sh"
GENERATOR="$ROOT/scripts/generate_0493x9s_splash_state.py"
[[ -f "$BASE_RUNNER" ]] || { echo "[0493x13ze-run-ok] ERROR missing $BASE_RUNNER" >&2; exit 2; }
[[ -f "$GENERATOR" ]] || { echo "[0493x13ze-run-ok] ERROR missing $GENERATOR" >&2; exit 2; }

TARGET="${RUN_OK_SURFACE_TARGET:-}"
CASE_NAME="${RUN_OK_SURFACE_CASE:-}"
case "$TARGET:$CASE_NAME" in
  wall:splash|puddle:puddle) ;;
  *) echo "[0493x13ze-run-ok] ERROR invalid surface run_ok selector TARGET=$TARGET CASE=$CASE_NAME" >&2; exit 2 ;;
esac

# Surface tension is a Q6-g-f boundary-pressure closure.  Unlike the generic
# run_ok hydrodynamic cases, an SRC/src-q6 comparison would not represent the
# same physical model, so this demonstration has one intentional path.
RUN_MODE="${RUN_MODE:-src-q6-g-f}"
[[ "$RUN_MODE" == "src-q6-g-f" ]] || {
  echo "[0493x13ze-run-ok] ERROR RUN_MODE=$RUN_MODE; surface-impact run_ok is locked to src-q6-g-f" >&2
  exit 2
}
export RUN_MODE

# ---------------------------------------------------------------------------
# USER EDIT ZONE -- same style as the 0434 run_ok collection.
# Defaults reproduce the retained x12a wall/puddle qualification point.
# ---------------------------------------------------------------------------
NX="${NX:-800}"; NY="${NY:-400}"
Lx="${Lx:-3.125}"; Ly="${Ly:-1.5625}"
GAMMA="${GAMMA:-20}"
DT="${DT:-0.002}"
KBT="${KBT:-0.125}"
LIQUID_MASS="${LIQUID_MASS:-1.0}"
PARTICLE_MASS="${PARTICLE_MASS:-$LIQUID_MASS}"
WALL_VP_MASS="${WALL_VP_MASS:-$LIQUID_MASS}"

SIGMA_ACTIVE="${SIGMA_ACTIVE:-2945.0}"
SURFACE_TENSION_MIN_RADIUS_CELLS="${SURFACE_TENSION_MIN_RADIUS_CELLS:-4}"
CONTACT_ANGLE_DEG="${CONTACT_ANGLE_DEG:-90.0}"
KINETIC_REFLECTION_FRACTION="${KINETIC_REFLECTION_FRACTION:-1.0}"
EVAPORATION_TARGET_TYPE="${EVAPORATION_TARGET_TYPE:--1}"

DROP_RADIUS_CELLS="${DROP_RADIUS_CELLS:-40}"
DROP_CENTER_X="${DROP_CENTER_X:-1.5625}"
DROP_CENTER_Y="${DROP_CENTER_Y:-0.5}"
DROP_VX="${DROP_VX:-0.0}"
DROP_VY="${DROP_VY:--1}"
GRAVITY_Y="${GRAVITY_Y:--0.005}"
PUDDLE_DEPTH_CELLS="${PUDDLE_DEPTH_CELLS:-40}"
SEED="${SEED:-493950}"

STEPS="${STEPS:-20000}"
SUMMARY_EVERY="${SUMMARY_EVERY:-100}"
DUMP_STATE_EVERY="${DUMP_STATE_EVERY:-1000}"
DUMP_ROLE_FILTER="${DUMP_ROLE_FILTER:-fluid}"
SUMMARY_ROLE_FILTER="${SUMMARY_ROLE_FILTER:-fluid}"
CLEAN_RUN_ROOT="${CLEAN_RUN_ROOT:-1}"
THREADS="${THREADS:-8}"

BIN="${BIN:-${SRC_MPCD_DEFAULT_BIN_0434:-build/src_mpcd_base_cuda_q6_resident_livevis_0486}}"
LIVE_PROGRESS="${LIVE_PROGRESS:-1}"
PREFLIGHT_ONLY="${PREFLIGHT_ONLY:-0}"
PARTICLE_TYPE_FILTER="${PARTICLE_TYPE_FILTER:-1}"

BASE_RUN_ROOT="${BASE_RUN_ROOT:-runs/0434_${CASE_NAME}_${NX}x${NY}_g${GAMMA}_s${SIGMA_ACTIVE}_r${DROP_RADIUS_CELLS}}"
RUN_ROOT="${RUN_ROOT:-$BASE_RUN_ROOT/$RUN_MODE}"

# LiveVis/recording conventions used by the demonstration collection.
LIVE_VIS_ENABLE="${LIVE_VIS_ENABLE:-1}"
LIVE_VIS_HOLD_ON_EXIT="${LIVE_VIS_HOLD_ON_EXIT:-1}"
LIVE_VIS_FIELD="${LIVE_VIS_FIELD:-mass}"
LIVE_VIS_EVERY="${LIVE_VIS_EVERY:-1}"
LIVE_VIS_COLORMAP="${LIVE_VIS_COLORMAP:-blue_red}"
LIVE_VIS_CLIP="${LIVE_VIS_CLIP:--1}"
LIVE_VIS_GAIN="${LIVE_VIS_GAIN:-1.0}"
LIVE_VIS_SMOOTH_PASSES="${LIVE_VIS_SMOOTH_PASSES:-0}"
LIVE_VIS_NX="${LIVE_VIS_NX:-$NX}"
LIVE_VIS_NY="${LIVE_VIS_NY:-$NY}"
LIVE_VIS_WINDOW_SCALE="${LIVE_VIS_WINDOW_SCALE:-1}"
OVERWRITE_LIVEVIS_CONTROL="${OVERWRITE_LIVEVIS_CONTROL:-1}"

FILTERED_RECORDING_ENABLE="${FILTERED_RECORDING_ENABLE:-1}"
RECORD_ENABLE="${RECORD_ENABLE:-true}"
RECORD_FIELDS="${RECORD_FIELDS:-mass,ux,uy}"
RECORD_EVERY="${RECORD_EVERY:-100}"
RECORD_FORMAT="${RECORD_FORMAT:-f32}"
RECORD_STRIDE="${RECORD_STRIDE:-1}"
FILTER_MODE="${FILTER_MODE:-none}"
FILTER_TAU="${FILTER_TAU:-0.0}"
FILTER_SAMPLE_EVERY="${FILTER_SAMPLE_EVERY:-100}"

# Historical names consumed directly by the x9s base runner.
FILTERED_RECORD_FIELDS="${FILTERED_RECORD_FIELDS:-$RECORD_FIELDS}"
FILTERED_RECORD_EVERY="${FILTERED_RECORD_EVERY:-$RECORD_EVERY}"
FILTERED_RECORD_SAMPLE_EVERY="${FILTERED_RECORD_SAMPLE_EVERY:-$FILTER_SAMPLE_EVERY}"

# Current aliases retained for consistency with later runner families.
LIVE_VIS_RECORD_ENABLE="${LIVE_VIS_RECORD_ENABLE:-1}"
LIVE_VIS_RECORD_FIELDS="${LIVE_VIS_RECORD_FIELDS:-$RECORD_FIELDS}"
LIVE_VIS_RECORD_EVERY="${LIVE_VIS_RECORD_EVERY:-$RECORD_EVERY}"
# ---------------------------------------------------------------------------

# Qualified microscopic profile from the x12a impact campaign.
ROTATION_ANGLE="${ROTATION_ANGLE:-1.5707963267948966}"
RANDOM_ROTATION_SIGN="${RANDOM_ROTATION_SIGN:-true}"
GRID_SHIFT_ENABLE="${GRID_SHIFT_ENABLE:-true}"
THERMOSTAT_ENABLE="${THERMOSTAT_ENABLE:-true}"
THERMOSTAT_MODE="${THERMOSTAT_MODE:-cell_relative_rescale}"
THERMOSTAT_EVERY="${THERMOSTAT_EVERY:-1}"
THERMOSTAT_TARGET_KBT="${THERMOSTAT_TARGET_KBT:-$KBT}"
THERMOSTAT_MIN_PARTICLES="${THERMOSTAT_MIN_PARTICLES:-3}"

# run_ok-style protected Q6 profile: generic inherited shell experiments are
# overwritten.  Only the dedicated RUN_OK_SURFACE_* variables are overrides.
RUN_OK_SURFACE_PROJECTION_BACKEND="${RUN_OK_SURFACE_PROJECTION_BACKEND:-cuda}"
RUN_OK_SURFACE_PROJECTION_OPERATOR="${RUN_OK_SURFACE_PROJECTION_OPERATOR:-auto_fv_cg}"
RUN_OK_SURFACE_PROJECTION_MAX_ITERATIONS="${RUN_OK_SURFACE_PROJECTION_MAX_ITERATIONS:-2000}"
RUN_OK_SURFACE_PROJECTION_TOLERANCE="${RUN_OK_SURFACE_PROJECTION_TOLERANCE:-1.0e-5}"
RUN_OK_SURFACE_PROJECTION_MOMENTUM_CORRECTION_ENABLE="${RUN_OK_SURFACE_PROJECTION_MOMENTUM_CORRECTION_ENABLE:-true}"
RUN_OK_SURFACE_Q6_STRICT="${RUN_OK_SURFACE_Q6_STRICT:-1}"
RUN_OK_SURFACE_Q6_GF_DENSITY_RELAXATION_TIME="${RUN_OK_SURFACE_Q6_GF_DENSITY_RELAXATION_TIME:-0.25}"
RUN_OK_SURFACE_Q6_GF_DENSITY_COMPRESSION_GATE_ENABLE="${RUN_OK_SURFACE_Q6_GF_DENSITY_COMPRESSION_GATE_ENABLE:-1}"
RUN_OK_SURFACE_Q6_GF_DENSITY_COMPRESSION_THRESHOLD_PARTICLES="${RUN_OK_SURFACE_Q6_GF_DENSITY_COMPRESSION_THRESHOLD_PARTICLES:-3.0}"
RUN_OK_SURFACE_Q6_GF_DENSITY_TRACTION_THRESHOLD_PARTICLES="${RUN_OK_SURFACE_Q6_GF_DENSITY_TRACTION_THRESHOLD_PARTICLES:-6.0}"
RUN_OK_SURFACE_Q6_GF_DENSITY_TRACTION_GAIN="${RUN_OK_SURFACE_Q6_GF_DENSITY_TRACTION_GAIN:-1.0}"
RUN_OK_SURFACE_Q6_GF_MIN_FILL_FRACTION="${RUN_OK_SURFACE_Q6_GF_MIN_FILL_FRACTION:-0.10}"

PROJECTION_BACKEND="$RUN_OK_SURFACE_PROJECTION_BACKEND"
PROJECTION_OPERATOR="$RUN_OK_SURFACE_PROJECTION_OPERATOR"
PROJECTION_MAX_ITERATIONS="$RUN_OK_SURFACE_PROJECTION_MAX_ITERATIONS"
PROJECTION_TOLERANCE="$RUN_OK_SURFACE_PROJECTION_TOLERANCE"
PROJECTION_MOMENTUM_CORRECTION_ENABLE="$RUN_OK_SURFACE_PROJECTION_MOMENTUM_CORRECTION_ENABLE"
Q6_STRICT="$RUN_OK_SURFACE_Q6_STRICT"
Q6_GF_DENSITY_RELAXATION_TIME="$RUN_OK_SURFACE_Q6_GF_DENSITY_RELAXATION_TIME"
Q6_GF_DENSITY_COMPRESSION_GATE_ENABLE="$RUN_OK_SURFACE_Q6_GF_DENSITY_COMPRESSION_GATE_ENABLE"
Q6_GF_DENSITY_COMPRESSION_THRESHOLD_PARTICLES="$RUN_OK_SURFACE_Q6_GF_DENSITY_COMPRESSION_THRESHOLD_PARTICLES"
Q6_GF_DENSITY_TRACTION_THRESHOLD_PARTICLES="$RUN_OK_SURFACE_Q6_GF_DENSITY_TRACTION_THRESHOLD_PARTICLES"
Q6_GF_DENSITY_TRACTION_GAIN="$RUN_OK_SURFACE_Q6_GF_DENSITY_TRACTION_GAIN"
SPECIES_Q6_MIN_FILL_FRACTION="$RUN_OK_SURFACE_Q6_GF_MIN_FILL_FRACTION"

# Surface-free production closure frozen at the qualified tag.  x10q is the
# automatic 7x7 fallback reached from x10p and therefore has no separate flag.
export MPCD_X10J_SIMPLE_SPECULAR_ABLATION=0
export MPCD_X10K_LOCAL_FRAME_SPECULAR_ABLATION=0
export MPCD_X10M_MOVING_INTERFACE_WALL=0
export MPCD_X10N_Q6_CONTINUOUS_INTERFACE_WALL=0
export MPCD_X10O_Q6_THERMAL_INTERFACE_WALL=1
export MPCD_X10O_THERMAL_PARTICLE_MASS="$LIQUID_MASS"
export MPCD_X10O_THERMAL_SIGMAS="${RUN_OK_SURFACE_X10O_THERMAL_SIGMAS:-3.0}"
export MPCD_X10O_THERMAL_MAX_CELLS="${RUN_OK_SURFACE_X10O_THERMAL_MAX_CELLS:-0.75}"
export MPCD_X10L_PREWALL_INTERFACE_DIAGNOSTICS=0
export MPCD_X10_KINETIC_INTERFACE_CIC=1
export MPCD_X10_KINETIC_INTERFACE_QUADRATIC=1
export MPCD_X10P_INITIAL_OVERLAP_RESOLUTION=1
export MPCD_X10_KINETIC_INTERFACE_ONE_FOR_ONE=1
export MPCD_X10_KINETIC_INTERFACE_ONE_FOR_ONE_SWAP=1
export MPCD_X10_KINETIC_INTERFACE_ONE_FOR_ONE_NORMAL_ONLY=0
export MPCD_X10R_Q6_THERMAL_FULL_VECTOR_ENDPOINT_VELOCITY=0
export MPCD_X10S_Q6_THERMAL_SEGMENT_NORMAL_KINEMATICS=0
export MPCD_X10T_Q6_THERMAL_RIGID_TANGENTIAL_KINEMATICS=0
export MPCD_X10_KINETIC_INTERFACE_THERMAL_PHASE_LIMITER=0
export MPCD_X12A_LOCAL_THERMAL_COOLING=1
export MPCD_X12A_LOCAL_THERMAL_RADIUS_CELLS="${RUN_OK_SURFACE_X12A_RADIUS_CELLS:-25.298221281347036}"

# No resampling/refill/virial fallback in this demonstration.
SPECIES_RESAMPLING_ENABLE=false
LIQUID_RESAMPLING_ENABLE=false
GAS_RESAMPLING_ENABLE=false
VIRIAL_DENSITY_KICK_ENABLE=false
WEIGHTED_RESAMPLING_ENABLE_OVERRIDE=false
CUDA_EMPTY_REFILL_ENABLE_OVERRIDE=false

export TARGET NX NY Lx Ly GAMMA DT KBT LIQUID_MASS PARTICLE_MASS WALL_VP_MASS
export SIGMA_ACTIVE SURFACE_TENSION_MIN_RADIUS_CELLS CONTACT_ANGLE_DEG
export KINETIC_REFLECTION_FRACTION EVAPORATION_TARGET_TYPE
export DROP_RADIUS_CELLS DROP_CENTER_X DROP_CENTER_Y DROP_VX DROP_VY GRAVITY_Y PUDDLE_DEPTH_CELLS SEED
export STEPS SUMMARY_EVERY DUMP_STATE_EVERY DUMP_ROLE_FILTER SUMMARY_ROLE_FILTER CLEAN_RUN_ROOT THREADS
export BIN LIVE_PROGRESS PREFLIGHT_ONLY PARTICLE_TYPE_FILTER RUN_ROOT
export LIVE_VIS_ENABLE LIVE_VIS_HOLD_ON_EXIT LIVE_VIS_FIELD LIVE_VIS_EVERY LIVE_VIS_COLORMAP LIVE_VIS_CLIP
export LIVE_VIS_GAIN LIVE_VIS_SMOOTH_PASSES LIVE_VIS_NX LIVE_VIS_NY LIVE_VIS_WINDOW_SCALE OVERWRITE_LIVEVIS_CONTROL
export FILTERED_RECORDING_ENABLE RECORD_ENABLE RECORD_FIELDS RECORD_EVERY RECORD_FORMAT RECORD_STRIDE
export FILTER_MODE FILTER_TAU FILTER_SAMPLE_EVERY FILTERED_RECORD_FIELDS FILTERED_RECORD_EVERY FILTERED_RECORD_SAMPLE_EVERY
export LIVE_VIS_RECORD_ENABLE LIVE_VIS_RECORD_FIELDS LIVE_VIS_RECORD_EVERY
export ROTATION_ANGLE RANDOM_ROTATION_SIGN GRID_SHIFT_ENABLE THERMOSTAT_ENABLE THERMOSTAT_MODE THERMOSTAT_EVERY THERMOSTAT_TARGET_KBT THERMOSTAT_MIN_PARTICLES
export PROJECTION_BACKEND PROJECTION_OPERATOR PROJECTION_MAX_ITERATIONS PROJECTION_TOLERANCE PROJECTION_MOMENTUM_CORRECTION_ENABLE Q6_STRICT
export Q6_GF_DENSITY_RELAXATION_TIME Q6_GF_DENSITY_COMPRESSION_GATE_ENABLE Q6_GF_DENSITY_COMPRESSION_THRESHOLD_PARTICLES
export Q6_GF_DENSITY_TRACTION_THRESHOLD_PARTICLES Q6_GF_DENSITY_TRACTION_GAIN SPECIES_Q6_MIN_FILL_FRACTION
export SPECIES_RESAMPLING_ENABLE LIQUID_RESAMPLING_ENABLE GAS_RESAMPLING_ENABLE VIRIAL_DENSITY_KICK_ENABLE
export WEIGHTED_RESAMPLING_ENABLE_OVERRIDE CUDA_EMPTY_REFILL_ENABLE_OVERRIDE

printf '%s\n' \
  "===== RUN_OK ${CASE_NAME^^} / QUALIFIED FREE-SURFACE IMPACT =====" \
  "[0493x13ze-run-ok] target=$TARGET path=$RUN_MODE root=$RUN_ROOT" \
  "[0493x13ze-run-ok] profile=surf-tension-qualified-x13h-20260831 / impact point retained from x12a" \
  "[0493x13ze-run-ok] chain=x10o+CIC+Q2+x10p/q+x10u+x10v-full-vector+x12a" \
  "[0493x13ze-run-ok] impact R/h=$DROP_RADIUS_CELLS vy=$DROP_VY gy=$GRAVITY_Y sigma=$SIGMA_ACTIVE rmin/h=$SURFACE_TENSION_MIN_RADIUS_CELLS kBT=$KBT" \
  "[0493x13ze-run-ok] outputs dumpEvery=$DUMP_STATE_EVERY recordEvery=$RECORD_EVERY liveEvery=$LIVE_VIS_EVERY hold=$LIVE_VIS_HOLD_ON_EXIT" \
  "[0493x13ze-run-ok] scope=qualitative demonstration of impact/lamella/crown/topology; not a critical-We validation"

bash "$BASE_RUNNER"

# Append an explicit run_ok provenance contract after the lower-level x9s
# runner has written its normal environment snapshot.
ENV_FILE="$RUN_ROOT/logs/environment_0493x9s.env"
if [[ -f "$ENV_FILE" ]]; then
  cat >> "$ENV_FILE" <<META_0493X13ZE
RUN_OK_SURFACE_IMPACT_PROFILE=0493x13ze_7655b81_x12a
RUN_OK_SURFACE_CASE=${CASE_NAME}
RUN_OK_SURFACE_TARGET=${TARGET}
RUN_OK_SURFACE_CHAIN=x10o+CIC+Q2+x10p/q+x10u+x10v-full-vector+x12a
RUN_OK_SURFACE_SIGMA=${SIGMA_ACTIVE}
RUN_OK_SURFACE_MIN_RADIUS_CELLS=${SURFACE_TENSION_MIN_RADIUS_CELLS}
RUN_OK_SURFACE_X12A_RADIUS_CELLS=${MPCD_X12A_LOCAL_THERMAL_RADIUS_CELLS}
RUN_OK_SURFACE_NORMAL_ONLY=${MPCD_X10_KINETIC_INTERFACE_ONE_FOR_ONE_NORMAL_ONLY}
RUN_OK_SURFACE_REFERENCE_TAG=surf-tension-qualified-x13h-20260831
META_0493X13ZE
fi

echo "[0493x13ze-run-ok] COMPLETE case=$CASE_NAME run=$RUN_ROOT"
