#!/usr/bin/env bash
# Common helpers for CUDA SRC classic + post-SRC resampling demonstration scripts.
# 0303 keeps the physical SRC classic step unchanged and activates only the
# post-SRC support-control modules validated in 0295--0299.

set -euo pipefail

# Defaults selected from the 0301/0302 backward-step validation campaign.
RESAMPLING_ENABLE="${RESAMPLING_ENABLE:-1}"
RESAMPLING_SURVEY_ENABLE="${RESAMPLING_SURVEY_ENABLE:-1}"
RESAMPLING_SURVEY_EVERY="${RESAMPLING_SURVEY_EVERY:-${SUMMARY_EVERY:-100}}"

MASS_RECONDITION_ENABLE="${MASS_RECONDITION_ENABLE:-1}"
MASS_RECONDITION_EVERY="${MASS_RECONDITION_EVERY:-${GUARD_EVERY:-1}}"
MASS_RECONDITION_STRENGTH="${MASS_RECONDITION_STRENGTH:-1.0}"

GUARD_EVERY="${GUARD_EVERY:-1}"
GUARD_NMIN="${GUARD_NMIN:-12}"
GUARD_NTARGET="${GUARD_NTARGET:-20}"
GUARD_NMAX="${GUARD_NMAX:-32}"
GUARD_SPLIT_FRACTION="${GUARD_SPLIT_FRACTION:-0.5}"

RESTORE_ENABLE="${RESTORE_ENABLE:-1}"
RESTORE_MAX_SCALE="${RESTORE_MAX_SCALE:-4.0}"
RESTORE_ABS_TOL="${RESTORE_ABS_TOL:-1e-14}"
RESTORE_REL_TOL="${RESTORE_REL_TOL:-1e-12}"

BOUNDARY_AWARE="${BOUNDARY_AWARE:-1}"
OPEN_BOUNDARY_HALO_CELLS="${OPEN_BOUNDARY_HALO_CELLS:-1}"
BOUNDARY_HALO_CELLS="${BOUNDARY_HALO_CELLS:-0}"
SOLID_HALO_CELLS="${SOLID_HALO_CELLS:-0}"

INACTIVE_SLOTS=5000000 

resampling_demo_bool_on_0303() {
  case "${1:-0}" in
    1|true|TRUE|yes|YES|on|ON) return 0 ;;
    *) return 1 ;;
  esac
}

resampling_demo_tag_0303() {
  if resampling_demo_bool_on_0303 "$RESAMPLING_ENABLE"; then
    printf 'resampling_guard_nmin%s_nt%s_nmax%s' "$GUARD_NMIN" "$GUARD_NTARGET" "$GUARD_NMAX"
  else
    if resampling_demo_bool_on_0303 "$RESAMPLING_SURVEY_ENABLE"; then
      printf 'classic_survey'
    else
      printf 'classic'
    fi
  fi
}

resampling_demo_root_0303() {
  local case_name=$1
  local base_root=${2:-}
  local tag
  tag=$(resampling_demo_tag_0303)
  if [[ -n "$base_root" ]]; then
    printf '%s/%s' "$base_root" "$tag"
  else
    printf 'runs/demo_src_resampling_cuda_%s_0303/%s' "$case_name" "$tag"
  fi
}

src_gpu_resampling_env_0303() {
  # 0295 passive post-SRC survey.  It remains useful in both classic and
  # resampling runs because it produces support metrics for post-processing.
  export MPCD_CUDA_RESAMPLING_SUPPORT_SURVEY_0295="$RESAMPLING_SURVEY_ENABLE"
  export MPCD_CUDA_RESAMPLING_SUPPORT_SURVEY_0295_EVERY="$RESAMPLING_SURVEY_EVERY"
  export MPCD_CUDA_RESAMPLING_SUPPORT_SURVEY_0295_MODE="${MPCD_CUDA_RESAMPLING_SUPPORT_SURVEY_0295_MODE:-full}"

  if resampling_demo_bool_on_0303 "$RESAMPLING_ENABLE"; then
    export MPCD_CUDA_RESAMPLING_MASS_RECONDITION_0296="$MASS_RECONDITION_ENABLE"
    export MPCD_CUDA_RESAMPLING_MASS_RECONDITION_0296_EVERY="$MASS_RECONDITION_EVERY"
    export MPCD_CUDA_RESAMPLING_MASS_RECONDITION_0296_STRENGTH="$MASS_RECONDITION_STRENGTH"

    export MPCD_CUDA_RESAMPLING_POPULATION_GUARD_0297=1
    export MPCD_CUDA_RESAMPLING_POPULATION_GUARD_0297_EVERY="$GUARD_EVERY"
    export MPCD_CUDA_RESAMPLING_POPULATION_GUARD_0297_NMIN="$GUARD_NMIN"
    export MPCD_CUDA_RESAMPLING_POPULATION_GUARD_0297_NTARGET="$GUARD_NTARGET"
    export MPCD_CUDA_RESAMPLING_POPULATION_GUARD_0297_NMAX="$GUARD_NMAX"
    export MPCD_CUDA_RESAMPLING_POPULATION_GUARD_0297_SPLIT_FRACTION="$GUARD_SPLIT_FRACTION"

    export MPCD_CUDA_RESAMPLING_MOMENT_RESTORE_0298="$RESTORE_ENABLE"
    export MPCD_CUDA_RESAMPLING_MOMENT_RESTORE_0298_MAX_SCALE="$RESTORE_MAX_SCALE"
    export MPCD_CUDA_RESAMPLING_MOMENT_RESTORE_0298_ABS_TOL="$RESTORE_ABS_TOL"
    export MPCD_CUDA_RESAMPLING_MOMENT_RESTORE_0298_REL_TOL="$RESTORE_REL_TOL"

    export MPCD_CUDA_RESAMPLING_POPULATION_GUARD_0299_BOUNDARY_AWARE="$BOUNDARY_AWARE"
    export MPCD_CUDA_RESAMPLING_POPULATION_GUARD_0299_OPEN_BOUNDARY_HALO_CELLS="$OPEN_BOUNDARY_HALO_CELLS"
    export MPCD_CUDA_RESAMPLING_POPULATION_GUARD_0299_BOUNDARY_HALO_CELLS="$BOUNDARY_HALO_CELLS"
    export MPCD_CUDA_RESAMPLING_POPULATION_GUARD_0299_SOLID_HALO_CELLS="$SOLID_HALO_CELLS"
  else
    export MPCD_CUDA_RESAMPLING_MASS_RECONDITION_0296=0
    export MPCD_CUDA_RESAMPLING_POPULATION_GUARD_0297=0
    export MPCD_CUDA_RESAMPLING_MOMENT_RESTORE_0298=0
    export MPCD_CUDA_RESAMPLING_POPULATION_GUARD_0299_BOUNDARY_AWARE=0
  fi
}

write_resampling_demo_metadata_0303() {
  local file=$1
  mkdir -p "$(dirname "$file")"
  cat > "$file" <<META
RESAMPLING_ENABLE=${RESAMPLING_ENABLE}
RESAMPLING_SURVEY_ENABLE=${RESAMPLING_SURVEY_ENABLE}
RESAMPLING_SURVEY_EVERY=${RESAMPLING_SURVEY_EVERY}
MASS_RECONDITION_ENABLE=${MASS_RECONDITION_ENABLE}
MASS_RECONDITION_EVERY=${MASS_RECONDITION_EVERY}
MASS_RECONDITION_STRENGTH=${MASS_RECONDITION_STRENGTH}
GUARD_EVERY=${GUARD_EVERY}
GUARD_NMIN=${GUARD_NMIN}
GUARD_NTARGET=${GUARD_NTARGET}
GUARD_NMAX=${GUARD_NMAX}
GUARD_SPLIT_FRACTION=${GUARD_SPLIT_FRACTION}
RESTORE_ENABLE=${RESTORE_ENABLE}
RESTORE_MAX_SCALE=${RESTORE_MAX_SCALE}
RESTORE_ABS_TOL=${RESTORE_ABS_TOL}
RESTORE_REL_TOL=${RESTORE_REL_TOL}
BOUNDARY_AWARE=${BOUNDARY_AWARE}
OPEN_BOUNDARY_HALO_CELLS=${OPEN_BOUNDARY_HALO_CELLS}
BOUNDARY_HALO_CELLS=${BOUNDARY_HALO_CELLS}
SOLID_HALO_CELLS=${SOLID_HALO_CELLS}
META
}

print_resampling_demo_banner_0303() {
  local case_name=$1 run_root=$2
  echo "[0303-demo] case        : $case_name"
  echo "[0303-demo] run root    : $run_root"
  echo "[0303-demo] mode        : $(resampling_demo_tag_0303)"
  echo "[0303-demo] survey      : enable=$RESAMPLING_SURVEY_ENABLE every=$RESAMPLING_SURVEY_EVERY"
  echo "[0303-demo] guard       : enable=$RESAMPLING_ENABLE every=$GUARD_EVERY nmin=$GUARD_NMIN ntarget=$GUARD_NTARGET nmax=$GUARD_NMAX"
  echo "[0303-demo] restore     : enable=$RESTORE_ENABLE maxScale=$RESTORE_MAX_SCALE"
  echo "[0303-demo] boundary0299: enable=$BOUNDARY_AWARE openHalo=$OPEN_BOUNDARY_HALO_CELLS wallHalo=$BOUNDARY_HALO_CELLS solidHalo=$SOLID_HALO_CELLS"
}
